// GENERATED by scripts/mirror-import.ts from HH-Studio/simple-site-builder:lib/html/attributes.ts
// Do not edit. Run `bun scripts/mirror-import.ts --sync-from-app <appRoot>`.

import { decodeHtmlEntities } from "./entities";

// ---------------------------------------------------------------------------
// Read one attribute out of a tag, respecting the quote that opened it.
//
// Why this exists: the import lane read attributes with `attr=["']([^"']*)["']`,
// a character class that ends the value at the FIRST quote of either kind. An
// apostrophe inside a double-quoted attribute therefore truncated it, silently.
// Measured on a real page in the fidelity corpus, `content="… one of the
// Stockholm's most popular sushi restaurant"` arrived as "… one of the
// Stockholm", and that string is what the draft's hero subheadline showed the
// owner. Prose-carrying attributes - `content`, `alt`, `title` - are exactly the
// ones an apostrophe belongs in, so the bug hits the text most worth keeping.
// Backlog 2643.
// ---------------------------------------------------------------------------

/**
 * The value of `name` in `tag`, entity-decoded and trimmed, or undefined.
 *
 * Handles the three forms HTML allows: double-quoted, single-quoted, and
 * unquoted. The quote that opened the value is the only thing that closes it,
 * so an apostrophe inside `"…"` is kept.
 */
export function attributeValue(tag: string, name: string): string | undefined {
  // The lookbehind, not `\b`: a hyphen is a word boundary, so `\balt=` matches
  // inside `data-alt=` and reads the wrong attribute.
  const re = new RegExp(
    `(?<![-\\w:.])${name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\s*=\\s*(?:"([^"]*)"|'([^']*)'|([^\\s"'>=\`]+))`,
    "i",
  );
  const m = tag.match(re);
  if (!m) return undefined;
  return decodeHtmlEntities(m[1] ?? m[2] ?? m[3] ?? "").trim();
}

/**
 * The first `<meta>` tag whose `name` or `property` is `key`, as raw markup.
 * Returned rather than parsed so the caller reads whichever attribute it wants
 * with `attributeValue`.
 */
export function metaTag(html: string, key: string): string | undefined {
  for (const m of html.matchAll(/<meta\b[^>]*>/gi)) {
    const tag = m[0];
    const id = attributeValue(tag, "name") ?? attributeValue(tag, "property");
    if (id && id.toLowerCase() === key.toLowerCase()) return tag;
  }
  return undefined;
}
