// GENERATED by scripts/mirror-import.ts from HH-Studio/simple-site-builder:lib/scrape/parse.ts
// Do not edit. Run `bun scripts/mirror-import.ts --sync-from-app <appRoot>`.

import { decodeHtmlEntities } from "../html/entities";
import { attributeValue, metaTag } from "../html/attributes";
import { safeDecodeURIComponent } from "../net/url";
import { platformForUrl, type SocialsMap } from "../socials";
import { detectTrackingFromHtml, type TrackingConfig } from "../tracking";
import { detectBookingProvider } from "../booking/embed";
import { parseBokadirekt } from "./bokadirekt";
import { hoursFromJsonLd, type ScrapedHours } from "./jsonLdHours";
import { classifyVertical, textHas } from "./classifyVertical";
import { classifyPlatform, type PlatformId } from "./classifyPlatform";
import {
  detectCommerce,
  mergeCommerceDetections,
  type CommerceDetection,
} from "./detectCommerce";
import { SERVICE_SUGGESTIONS } from "../../convex/model/serviceSuggestions";
import type { Vertical } from "../../../convex/model/business";

// ---------------------------------------------------------------------------
// Pure HTML extraction for the "import from your existing site" flow. No DOM
// (runs in a Convex action), no network - just string parsing - so it's fully
// unit-testable. Best-effort: returns whatever it can find.
// ---------------------------------------------------------------------------

export type ScrapeResult = {
  businessName?: string;
  description?: string;
  phone?: string;
  email?: string;
  /** Street + postal code (+ region/country when no locality is known). */
  address?: string;
  /** Locality, kept separate so it maps to the onboarding "City" field. */
  city?: string;
  /** Service names found on the page (Bokadirekt menu, or known service terms
   *  matched in the page text). */
  services?: string[];
  /** Best-guess business vertical from the page content - a SUGGESTION the user
   *  can override in onboarding. "generic" when there's no clear signal. */
  vertical?: Vertical;
  /** Whether the vertical guess is high-confidence (a clear trade match) vs a
   *  soft suggestion. The UI nudges the user to confirm when this is false. */
  verticalConfident?: boolean;
  /** The best few industry candidates, best first, `vertical` at index 0. The
   *  import preview offers these as one-tap corrections instead of a single
   *  pre-selected guess (owner directive 2026-07-26). */
  verticalAlternatives?: Vertical[];
  /** The owner's REAL weekly opening hours, from the page's schema.org
   *  `openingHoursSpecification` (one row per OPEN weekday; a missing weekday
   *  renders as closed). A split day carries its `breaks`. Never guessed - a
   *  page without the markup simply has none, and generation falls back to the
   *  quick-preset the owner picks in onboarding (backlog 0277). */
  hours?: ScrapedHours;
  /** Day names the page listed that we could not map to a weekday. Surfaced in
   *  the import preview so a discarded day is visible to the owner instead of
   *  disappearing between their old site and their new one (backlog 0277). */
  hoursUnreadableDays?: string[];
  /** An external booking link found on the page (or the page's own URL when it
   *  IS a booking-provider page, e.g. Bokadirekt). Wires the "Boka" button. */
  bookingUrl?: string;
  socials?: SocialsMap;
  /** Third-party tracking ids detected in the page's scripts. */
  tracking?: TrackingConfig;
  /** Best-guess source platform (Wix / one.com / Loopia / …) - tailors the
   *  "what we couldn't move" note + links to the right /migrate guide. */
  platform?: PlatformId;
  /** Whether the platform guess is from a strong, builder-specific signature. */
  platformConfident?: boolean;
  /** The site's logo/icon URL (og:logo / apple-touch-icon / icon), absolutized.
   *  A suggestion the owner can adopt as their brand logo. */
  logoUrl?: string;
  /** The site's declared brand colour (`<meta name="theme-color">` or the
   *  MS tile colour), normalized to #rrggbb. Snapped to the nearest theme
   *  preset in importMerge so an imported site keeps its brand hue (P3). */
  themeColor?: string;
  /** A few real photo URLs from the page (og:image + content `<img>`s),
   *  absolutized, deduped, filtered of icons/sprites/pixels. The owner picks
   *  which to bring in as real site photos. */
  imageUrls?: string[];
  /** The owner's own body copy: heading + paragraph blocks in page order,
   *  bounded. Feeds the AI copywriter as "their own words" so a switcher's
   *  real text carries over instead of template filler. */
  copyBlocks?: Array<{ heading?: string; text: string }>;
  /** Customer quotes found on the page (blockquotes / review-marked markup).
   *  REAL proof from their existing site - may seed a testimonials section. */
  testimonials?: Array<{ text: string; author?: string }>;
  /** Price mentions near service-like labels ("Klippning ... 450 kr"). */
  prices?: Array<{ label: string; priceText: string }>;
  /** Evidence that the owner ALREADY sells online (Shopify/Woo/Ecwid markup, a
   *  cart on the same host, a priced catalogue). Absent when nothing was found.
   *  Information for the owner to review - the import never connects a store,
   *  moves a product or touches a checkout link. See detectCommerce.ts. */
  commerce?: CommerceDetection;
};

/** Assemble address parts into one short line: trims, drops empties/dupes,
 *  caps length. Pure + order-preserving so callers control the field order. */
function formatAddress(parts: (string | undefined)[]): string | undefined {
  const seen = new Set<string>();
  const clean: string[] = [];
  for (const raw of parts) {
    if (typeof raw !== "string") continue;
    const s = raw.replace(/\s+/g, " ").trim();
    if (!s) continue;
    const key = s.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    clean.push(s);
  }
  if (!clean.length) return undefined;
  return clean.join(", ").slice(0, 120);
}

/** Trim-and-decode wrapper over the shared decoder (`lib/html/entities.ts`).
 *  Callers here have always relied on the trim. */
function decodeEntities(s: string): string {
  return decodeHtmlEntities(s).trim();
}

/**
 * A meta tag's content, by `name` or `property`, first key that answers.
 *
 * Reads the value with `attributeValue` rather than a `[^"']*` class, which
 * ended the value at the first quote of EITHER kind: a description written
 * `content="one of the Stockholm's most popular sushi restaurants"` arrived as
 * "one of the Stockholm", and that truncation went straight into the imported
 * hero's subheadline. Backlog 2643.
 */
function meta(html: string, keys: string[]): string | undefined {
  for (const key of keys) {
    const tag = metaTag(html, key);
    const value = tag ? attributeValue(tag, "content") : undefined;
    if (value) return value;
  }
  return undefined;
}

/** Page-name words that appear in a `<title>` beside the real brand. A segment
 *  that is only these is the PAGE, not the business ("Hem - Marketcap"). */
const PAGE_LABEL =
  /^(hem|hemsida|start|startsida|startsidan|f(ö|o)rstasida(n)?|framsida(n)?|forside|home|home\s?page|index|welcome|v(ä|a)lkommen|v(ä|a)lkommen\s+till|om\s+oss|about(\s+us)?|kontakt|contact)$/i;

/** Titles that greet instead of naming: "Välkommen till SATS: träning &
 *  fitness". Strip the greeting, then keep only what precedes a colon when the
 *  head is short enough to be a name rather than a sentence. */
function trimTitleFluff(segment: string): string {
  let s = segment
    .replace(/^(v(ä|a)lkommen\s+till|v(ä|a)lkommen\s+hos|welcome\s+to)\s+/i, "")
    .trim();
  const colon = s.indexOf(":");
  if (colon >= 2 && colon <= 40) s = s.slice(0, colon).trim();
  return s;
}

/** Letters/digits only, lowercased — for comparing a title segment with the
 *  hostname ("Market Cap" vs "marketcap.se"). */
function brandKey(s: string): string {
  return s.toLowerCase().replace(/[^\p{L}\p{N}]/gu, "");
}

/** The registrable-ish host label, minus `www.` and the TLD. */
function hostBrandKey(baseUrl: string): string {
  try {
    const parts = new URL(baseUrl).hostname.replace(/^www\./i, "").split(".");
    return brandKey(parts[0] ?? "");
  } catch {
    return "";
  }
}

/** Pick the business name out of title-ish candidates.
 *
 *  A `<title>` is usually "<page> <sep> <brand>" or "<brand> <sep> <tagline>",
 *  and taking the first segment (the old behaviour) turned the extremely common
 *  Swedish "Hem - Marketcap" into the business name "Hem". We split on the
 *  separators, drop segments that are only a page label, then prefer the
 *  segment that matches the hostname; otherwise the first survivor. Candidates
 *  are tried in order, so `og:site_name` still wins when present. */
function pickBusinessName(
  candidates: (string | undefined)[],
  baseUrl: string,
): string | undefined {
  const host = hostBrandKey(baseUrl);
  for (const raw of candidates) {
    if (!raw) continue;
    const segments = raw
      .split(/\s+[|–—•·–—-]\s+/)
      .map((s) => trimTitleFluff(s))
      .filter(Boolean);
    if (!segments.length) continue;
    const real = segments.filter((s) => !PAGE_LABEL.test(s));
    // Every segment was a page label ("Hem", "Startsida | Hem") — this candidate
    // carries no brand. Fall through so JSON-LD or the next candidate can answer.
    if (!real.length) continue;
    const hostMatch = host
      ? real.find((s) => {
          const k = brandKey(s);
          return k.length >= 3 && (k === host || host.includes(k) || k.includes(host));
        })
      : undefined;
    return (hostMatch ?? real[0]).slice(0, 80).trim();
  }
  return undefined;
}

/** Separators a `<title>` uses between the page name and the brand.
 *
 *  A bare `:` is deliberately absent - "Snickeri: kök och bad" is one title.
 *  So are UNSPACED en/em dashes: they are how Swedish writes a range, and
 *  treating them as separators truncated real titles ("Priser 2025–2026" →
 *  "Priser 2025", "Öppettider Mån–Fre" → "Öppettider Mån", and worst of all
 *  "Massage 60–90 min" → "Massage 60" on a title with no brand in it at all).
 *  A dash only separates when it is spaced, which is the `\s+[-–—]\s+` arm. */
const TITLE_SEPARATORS = /\s*(?:::|[|•·»])\s*|\s+[-–—]\s+/;

/** Turn a document `<title>` into the PAGE's name, by removing the brand.
 *
 *  A `<title>` is "<page> <sep> <brand>" far more often than not, and using it
 *  raw put "Sortiment :: Hantverksbolaget" in the navigation of an imported
 *  site - verified against a real Swedish site on 2026-07-27. The business name
 *  is already known by the time pages are built (`pickBusinessName` reads the
 *  home page), so the brand segment can simply be dropped.
 *
 *  Conservative by design: when removing the brand would leave nothing, the
 *  original title is kept. A single-segment title is returned untouched - the
 *  goal is to delete a repeated brand, never to guess at a name. */
export function pageTitleFromDocumentTitle(
  rawTitle: string | undefined,
  businessName: string | undefined,
  baseUrl?: string,
): string | undefined {
  const raw = rawTitle?.trim();
  if (!raw) return undefined;
  const segments = raw
    .split(TITLE_SEPARATORS)
    .map((s) => s.trim())
    .filter(Boolean);
  if (segments.length < 2) return raw;

  const brand = businessName ? brandKey(businessName) : "";
  const host = baseUrl ? hostBrandKey(baseUrl) : "";
  const isBrand = (s: string) => {
    const k = brandKey(s);
    if (k.length < 3) return false;
    if (brand && (k === brand || brand.includes(k) || k.includes(brand))) return true;
    return !!host && (k === host || host.includes(k) || k.includes(host));
  };

  const kept = segments.filter((s) => !isBrand(s));
  // Every segment was the brand ("Hantverksbolaget | Hantverksbolaget"), or we
  // could not tell them apart - keep what the page actually declared.
  if (!kept.length) return segments[0];
  return kept[0];
}

/** Query params that only cache-bust, so two URLs differing solely in one of
 *  them are the same picture. */
const CACHE_BUST_PARAMS = new Set(["t", "v", "ver", "version", "ts", "cb", "_", "rev"]);

/** Identity key for a scraped image.
 *
 *  Dropping the query string (the old rule) is right for `/photos/team.jpg?v=2`
 *  but catastrophic for an image CDN that puts the filename IN the query —
 *  `…/image/resize?file=283.jpg&t=…`. Every distinct photo on such a site
 *  collapsed to the same key and the import kept exactly one of them. So: strip
 *  the query only when the path itself names an image file; otherwise keep the
 *  query, minus the cache-busting params. */
function imageDedupeKey(abs: string): string {
  const hasFileExtension = /\.(png|jpe?g|webp|gif|avif|bmp|tiff?)$/i.test(
    abs.split("?")[0],
  );
  if (hasFileExtension) return abs.split("?")[0].toLowerCase();
  try {
    const u = new URL(abs);
    for (const p of [...u.searchParams.keys()]) {
      if (CACHE_BUST_PARAMS.has(p.toLowerCase())) u.searchParams.delete(p);
    }
    u.searchParams.sort();
    return u.toString().toLowerCase();
  } catch {
    return abs.toLowerCase();
  }
}

/** Read one attribute off a single tag string. */
function tagAttr(tag: string, name: string): string | undefined {
  const m = tag.match(new RegExp(`\\b${name}\\s*=\\s*["']([^"']*)["']`, "i"));
  return m?.[1];
}

/** Anything that looks like a logo but isn't the owner's: builder badges,
 *  payment marks, app-store buttons, social glyphs. */
const NOT_A_BRAND_LOGO =
  /powered|built\s?with|badge|klarna|swish|visa|mastercard|paypal|app-?store|google-?play|facebook|instagram|linkedin|trustpilot|reco\b/i;

/** The owner's real wordmark: the `<img>` inside the page header/nav whose src,
 *  alt, class or id says "logo". Most small-business sites put their logo top
 *  left in the navbar and declare neither `og:logo` nor a branded favicon, so
 *  without this the import fell back to whatever icon the CMS shipped. */
function findHeaderLogo(html: string, baseUrl: string): string | null {
  const regions = [...html.matchAll(/<(header|nav)\b[\s\S]*?<\/\1>/gi)].map((m) => m[0]);
  // No semantic header (plenty of builder output has none) — the top of the
  // document is the next best bounded scope.
  const scopes = regions.length ? regions : [html.slice(0, 20000)];
  for (const scope of scopes) {
    for (const m of scope.matchAll(/<img\b[^>]*>/gi)) {
      const tag = m[0];
      const src = tagAttr(tag, "src") || tagAttr(tag, "data-src");
      if (!src) continue;
      const haystack = [src, tagAttr(tag, "alt"), tagAttr(tag, "class"), tagAttr(tag, "id")]
        .filter(Boolean)
        .join(" ");
      if (!/logo|logga|wordmark|brandmark/i.test(haystack)) continue;
      if (NOT_A_BRAND_LOGO.test(haystack)) continue;
      const abs = absolutize(decodeEntities(src), baseUrl);
      if (abs && /^https?:/i.test(abs)) return abs;
    }
  }
  return null;
}

function absolutize(href: string, baseUrl: string): string | null {
  try {
    return new URL(href, baseUrl).toString();
  } catch {
    return null;
  }
}

/** Strip tags + scripts/styles to a rough plain-text blob for keyword matching
 *  and the phone-in-text fallback. Best-effort, not a real parser. */
function htmlToText(html: string): string {
  return decodeEntities(
    html
      .replace(/<(script|style|noscript)[^>]*>[\s\S]*?<\/\1>/gi, " ")
      .replace(/<[^>]+>/g, " ")
      .replace(/\s+/g, " "),
  );
}

/** Pull a Swedish/intl phone number out of visible text when no `tel:` link or
 *  JSON-LD telephone was found. Conservative: must start with +46/0046/0 and
 *  hold 8–13 digits, rejecting repeated-digit junk. First plausible hit wins. */
function extractPhoneFromText(text: string): string | undefined {
  const candidates = text.match(/(?:\+46|0046|0)[\d\s().-]{6,16}\d/g) ?? [];
  for (const c of candidates) {
    const digits = c.replace(/\D/g, "");
    if (digits.length < 8 || digits.length > 13) continue;
    if (/^(\d)\1+$/.test(digits)) continue; // 000000…, 111111… - not a number
    return c
      .replace(/[().]/g, " ")
      .replace(/\s+/g, " ")
      .trim()
      .slice(0, 40);
  }
  return undefined;
}

// Flat bilingual lexicon of known service labels (built once). Used to suggest
// services on non-Bokadirekt pages by matching the page text. Each entry keeps
// both language variants so we return the label as it likely appears on-site.
const SERVICE_LEXICON: string[] = (() => {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const list of Object.values(SERVICE_SUGGESTIONS)) {
    for (const { sv, en } of list) {
      for (const label of [sv, en]) {
        const key = label.toLowerCase();
        if (label && !seen.has(key)) {
          seen.add(key);
          out.push(label);
        }
      }
    }
  }
  return out;
})();

/** The sv+en labels a single vertical owns, lowercased. Used to drop services
 *  the page only "matched" because the lexicon is the union of every trade. */
function labelsForVertical(vertical: Vertical): Set<string> {
  const out = new Set<string>();
  for (const { sv, en } of SERVICE_SUGGESTIONS[vertical] ?? []) {
    if (sv) out.add(sv.toLowerCase());
    if (en) out.add(en.toLowerCase());
  }
  return out;
}

/** Suggest services by matching known service labels against the page text.
 *  Best-effort, capped, deduped (case-insensitive). */
function detectServicesFromText(text: string): string[] {
  const found: string[] = [];
  const seen = new Set<string>();
  for (const label of SERVICE_LEXICON) {
    if (found.length >= 12) break;
    const key = label.toLowerCase();
    if (seen.has(key)) continue;
    if (textHas(text, label)) {
      seen.add(key);
      found.push(label);
    }
  }
  return found;
}

// ---------------------------------------------------------------------------
// The paste lane. A small business whose whole web presence is a Facebook or
// Instagram page has nothing for the URL lane to fetch: Meta serves a login
// wall to a fetcher and its ToS forbids scraping it anyway (backlog 0181). The
// owner CAN see their own "Om"/About text, so they paste it.
//
// Deliberately the same extraction as the page lane, minus everything that
// needs markup. There is no structured layer here - no JSON-LD, no meta tags,
// no `tel:` links - so this is the text-fallback half of `extractFromHtml`
// running on its own, over the same helpers, producing the same `ScrapeResult`
// that `scrapeToFactCandidates` already knows how to map. A second extractor
// with its own idea of what a phone number is would drift within a month.
// ---------------------------------------------------------------------------

/** An email in running text. Trailing punctuation is excluded by the character
 *  class rather than trimmed after, so "skriv till oss@x.se." keeps the dot out
 *  of the address. */
const EMAIL_IN_TEXT = /[\w.+-]+@[\w-]+(?:\.[\w-]+)*\.[a-z]{2,}/i;
/** A Swedish postal address line: "Storgatan 4, 753 20 Uppsala". The postal
 *  code (three digits, optional space, two digits) is the anchor - a line with
 *  a street name and no postal code is not an address we are sure of. */
const POSTAL_LINE = /^(.*?)[,\s]*(\d{3}\s?\d{2})\s+([^\d,]{2,40})$/;

/** One display line carrying everything we know about where the business is.
 *
 *  `address` and `city` are separate on `ScrapeResult` because the onboarding
 *  wizard fills two different fields from them, and the structured producers
 *  (schema.org `PostalAddress`, the `og:`/`business:` meta block) deliberately
 *  leave the locality OUT of the line when they have it on its own. That is
 *  right for onboarding and wrong everywhere the line stands alone: the import
 *  review showed an owner "Storgatan 4, 753 20" and asked them to approve it.
 *
 *  Appends the city AFTER the postal code with a space rather than a comma —
 *  the way a Swedish address is written, and the form `parsePostalAddressLine`
 *  can read back. */
export function composeAddressLine(
  address?: string,
  city?: string,
): string | undefined {
  const line = address?.replace(/\s+/g, " ").trim();
  const locality = city?.replace(/\s+/g, " ").trim();
  if (!line) return locality ? locality.slice(0, 160) : undefined;
  if (!locality) return line.slice(0, 160);
  // Already ends with the locality (the paste lane builds it that way).
  if (new RegExp(`(^|[\\s,])${escapeRegExp(locality)}$`, "i").test(line)) {
    return line.slice(0, 160);
  }
  // A trailing postal code takes the city as its own tail; anything else gets
  // a comma, because "Storgatan 1 Uppsala" reads as one street name.
  const sep = /\d{3}\s?\d{2}$/.test(line) ? " " : ", ";
  return `${line}${sep}${locality}`.slice(0, 160);
}

/** Split a display address line back into the structured shape
 *  `websites.contact.address` stores. Inverse of `composeAddressLine`, and it
 *  lives beside it for the same reason `extractFromText` lives beside
 *  `extractFromHtml`: a second idea of what an address line looks like drifts
 *  from this one within a month.
 *
 *  The postal code is the anchor, exactly as in `POSTAL_LINE`. A line without
 *  one ("Storgatan 1, Uppsala") returns null rather than a guess — splitting on
 *  the comma would put an unverified locality into the site's LocalBusiness
 *  JSON-LD, and the caller has a lossless fallback that keeps the line intact. */
export function parsePostalAddressLine(
  line: string,
): { street?: string; postalCode: string; city: string } | null {
  const s = line.replace(/\s+/g, " ").trim();
  if (!s) return null;
  const m = s.match(POSTAL_LINE);
  if (!m) return null;
  const street = m[1].replace(/[,\s]+$/, "").trim();
  const city = m[3].replace(/[,\s]+$/, "").trim();
  if (!city) return null;
  return {
    ...(street ? { street: street.slice(0, 120) } : {}),
    postalCode: m[2].replace(/\s+/g, " ").trim(),
    city: city.slice(0, 80),
  };
}

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/** Facts from text the owner pasted. Nothing is invented: a value the text does
 *  not state is simply absent, exactly as with a page that did not declare it.
 *  The result is reviewed and ticked by the owner before any of it is trusted,
 *  which is the same contract the URL lane has. */
export function extractFromText(input: string): ScrapeResult {
  const result: ScrapeResult = {};
  const raw = input.slice(0, 20_000);
  const lines = raw
    .split(/\r?\n/)
    .map((l) => l.trim())
    .filter((l) => l.length > 0);
  // One flattened blob for the helpers that scan prose (phone, service
  // lexicon, vertical), matching what `htmlToText` hands them.
  const text = raw.replace(/\s+/g, " ").trim();

  const email = text.match(EMAIL_IN_TEXT)?.[0];
  if (email) result.email = email.slice(0, 120);

  const phone = extractPhoneFromText(text);
  if (phone) result.phone = phone;

  // Address: the first line carrying a postal code. When that line is ONLY the
  // postal code and city ("753 20 Uppsala"), the street is the line above it -
  // which is how every Swedish address block is written.
  for (let i = 0; i < lines.length; i += 1) {
    const m = lines[i].match(POSTAL_LINE);
    if (!m) continue;
    const street = m[1].trim() || (i > 0 ? lines[i - 1] : "");
    const city = m[3].trim();
    result.address = [street, `${m[2]} ${city}`].filter(Boolean).join(", ").slice(0, 160);
    result.city = city.slice(0, 80);
    break;
  }

  // Socials: any profile link the text contains, one per platform, first wins.
  const socials: SocialsMap = {};
  for (const m of raw.matchAll(/https?:\/\/[^\s<>"')]+/gi)) {
    const url = m[0].replace(/[.,;:]+$/, "");
    const platform = platformForUrl(url);
    if (platform && !socials[platform]) socials[platform] = url.slice(0, 300);
  }
  if (Object.keys(socials).length > 0) result.socials = socials;

  // The owner's story: the longest blank-line-separated block that is prose
  // rather than a contact line. Falls back to the whole text when the paste is
  // one unbroken paragraph, which is what an Instagram bio actually is.
  const blocks = raw
    .split(/\n\s*\n/)
    .map((b) => b.replace(/\s+/g, " ").trim())
    .filter((b) => b.length >= 40);
  const description = blocks.sort((a, b) => b.length - a.length)[0] ?? (text.length >= 40 ? text : "");
  if (description) result.description = description.slice(0, 600);

  // Services + vertical: the same lexicon pass and the same trade filter the
  // page lane runs, so a pasted description and the same words on a website
  // produce the same suggestions.
  const services = detectServicesFromText(text);
  if (services.length) result.services = services;
  const guess = classifyVertical({
    description: result.description,
    services: result.services,
    text,
  });
  result.vertical = guess.vertical;
  result.verticalConfident = guess.confident;
  if (guess.alternatives.length > 1) result.verticalAlternatives = guess.alternatives;
  if (result.services?.length && result.vertical !== "generic") {
    const owned = labelsForVertical(result.vertical);
    const kept = result.services.filter((s) => owned.has(s.toLowerCase()));
    if (kept.length) result.services = kept;
  }

  return result;
}

export function extractFromHtml(html: string, baseUrl: string): ScrapeResult {
  const result: ScrapeResult = {};

  // --- name + description (og / meta / <title>) ---
  const ogSite = meta(html, ["og:site_name"]);
  const ogTitle = meta(html, ["og:title", "twitter:title"]);
  const titleTag = html.match(/<title[^>]*>([^<]*)<\/title>/i)?.[1];
  const pickedName = pickBusinessName(
    [ogSite, ogTitle, titleTag ? decodeEntities(titleTag) : undefined],
    baseUrl,
  );
  if (pickedName) result.businessName = pickedName;
  const desc = meta(html, ["description", "og:description", "twitter:description"]);
  if (desc) result.description = desc.slice(0, 600);

  // --- links: socials, mailto, tel ---
  const hrefs = [...html.matchAll(/href=["']([^"']+)["']/gi)].map((m) => m[1]);
  const socials: SocialsMap = {};
  for (const href of hrefs) {
    if (/^(mailto|tel):/i.test(href)) continue;
    const abs = absolutize(href, baseUrl);
    if (!abs) continue;
    const p = platformForUrl(abs);
    if (p && !socials[p]) socials[p] = abs;
  }

  const mailto = hrefs.find((h) => /^mailto:/i.test(h));
  if (mailto) {
    const email = safeDecodeURIComponent(mailto.replace(/^mailto:/i, "").split("?")[0]);
    if (/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) result.email = email;
  }
  const tel = hrefs.find((h) => /^tel:/i.test(h));
  if (tel) {
    const phone = safeDecodeURIComponent(tel.replace(/^tel:/i, "")).trim().slice(0, 40);
    // Five digits is the bar because a phone number nobody can dial is worse
    // than no phone number: the owner sees a filled-in field and never checks
    // it. `tel:%ZZ` and `tel:kontakt` both land here.
    if ((phone.match(/\d/g) ?? []).length >= 5) result.phone = phone;
  }

  // --- JSON-LD (name / telephone / email / sameAs) ---
  const ldBlocks = [
    ...html.matchAll(
      /<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi,
    ),
  ];
  for (const block of ldBlocks) {
    try {
      const json = JSON.parse(block[1].trim());
      // `@graph` can be an array, a plain object, or absent. Normalise to an
      // array so the spread never throws "is not iterable".
      const graphRaw = json && typeof json === "object" ? json["@graph"] : undefined;
      const graph = Array.isArray(graphRaw)
        ? graphRaw
        : graphRaw && typeof graphRaw === "object"
          ? [graphRaw]
          : [];
      const nodes = Array.isArray(json) ? json : [json, ...graph];
      for (const node of nodes) {
        if (!node || typeof node !== "object") continue;
        if (!result.businessName && typeof node.name === "string")
          result.businessName = node.name.slice(0, 80);
        if (!result.phone && typeof node.telephone === "string")
          result.phone = node.telephone.slice(0, 40);
        if (!result.email && typeof node.email === "string")
          result.email = node.email;
        if (!result.address || !result.city) {
          // node.address may be a PostalAddress object, a plain string, or an
          // array of either. Take the first usable entry. Fill address + city
          // independently (a later node may carry the street a city-only node
          // lacked), each first-wins like the other fields above.
          const addrRaw = Array.isArray(node.address)
            ? node.address[0]
            : node.address;
          if (typeof addrRaw === "string") {
            if (!result.address) result.address = formatAddress([addrRaw]);
          } else if (addrRaw && typeof addrRaw === "object") {
            const locality =
              typeof addrRaw.addressLocality === "string"
                ? addrRaw.addressLocality.trim()
                : undefined;
            if (locality && !result.city) result.city = locality.slice(0, 80);
            // Street + postcode are the core line; fall back to region/country
            // only when this node has no locality to anchor the address.
            const addr = formatAddress([
              addrRaw.streetAddress,
              addrRaw.postalCode,
              locality ? undefined : addrRaw.addressRegion,
              locality ? undefined : addrRaw.addressCountry,
            ]);
            if (addr && !result.address) result.address = addr;
          }
        }
        // Weekly hours from the standard `openingHoursSpecification`. First
        // node wins, like every other field here. A Bokadirekt profile carries
        // them on the same LocalBusiness node we already read the name and
        // address from, so a salon importing from Bokadirekt no longer arrives
        // with no hours at all (backlog 0277).
        //
        // Gated on `hours` ALONE. Gating on the unreadable-days note too meant a
        // first node we could not read stopped us looking at the rest of the
        // page: a site whose first node writes "Måndag" and whose second
        // carries proper schema.org names imported with no hours and a note
        // blaming days it never used.
        if (!result.hours) {
          const read = hoursFromJsonLd(node);
          if (read?.hours.length) {
            result.hours = read.hours;
            // The note travels with the schedule it describes. Adopting this
            // node's list wholesale (empty included) stops an earlier node's
            // rejected days being reported against a week they never belonged
            // to - the same rule mergeScrapeResults applies across pages.
            result.hoursUnreadableDays = read.unreadableDays.length
              ? read.unreadableDays
              : undefined;
          } else if (read?.unreadableDays.length && !result.hoursUnreadableDays) {
            // No hours from this node, but it did have some it could not read:
            // "we found hours and understood none of them" is the case the
            // owner most needs to see. Kept only until a node supplies a real
            // schedule, which replaces it above.
            result.hoursUnreadableDays = read.unreadableDays;
          }
        }
        const sameAs = Array.isArray(node.sameAs)
          ? node.sameAs
          : typeof node.sameAs === "string"
            ? [node.sameAs]
            : [];
        for (const url of sameAs) {
          if (typeof url !== "string") continue;
          const p = platformForUrl(url);
          if (p && !socials[p]) socials[p] = url;
        }
      }
    } catch {
      // ignore malformed JSON-LD
    }
  }

  if (Object.keys(socials).length > 0) result.socials = socials;

  // --- address fallback: OpenGraph / Facebook business contact meta ---
  if (!result.address || !result.city) {
    const street = meta(html, [
      "og:street-address",
      "business:contact_data:street_address",
    ]);
    const locality = meta(html, [
      "og:locality",
      "business:contact_data:locality",
    ]);
    const postal = meta(html, [
      "og:postal-code",
      "business:contact_data:postal_code",
    ]);
    const region = meta(html, [
      "og:region",
      "business:contact_data:region",
    ]);
    const country = meta(html, [
      "og:country-name",
      "business:contact_data:country_name",
    ]);
    if (locality && !result.city) result.city = locality.slice(0, 80);
    const addr = formatAddress([
      street,
      postal,
      locality ? undefined : region,
      locality ? undefined : country,
    ]);
    if (addr && !result.address) result.address = addr;
  }

  // --- booking link: any href to a known provider (Bokadirekt / Calendly / …) ---
  for (const href of hrefs) {
    const abs = absolutize(href, baseUrl);
    if (!abs) continue;
    if (detectBookingProvider(abs) !== "other") {
      result.bookingUrl = abs;
      break;
    }
  }
  // The page itself may BE a booking-provider page (e.g. a Bokadirekt profile).
  if (!result.bookingUrl && detectBookingProvider(baseUrl) !== "other") {
    result.bookingUrl = baseUrl;
  }

  // --- Bokadirekt profile: purpose-built extraction (services + cleaner info) ---
  // Its values win for the fields it finds (the generic og/meta name keeps the
  // city suffix; Bokadirekt gives a clean name + the price-listed service menu).
  if (detectBookingProvider(baseUrl) === "bokadirekt") {
    const bd = parseBokadirekt(html, baseUrl);
    // Override the name: the generic pass picks `og:site_name` = "Bokadirekt"
    // (the platform); the JSON-LD/title gives the real place name.
    if (bd.businessName) result.businessName = bd.businessName;
    // Generic JSON-LD already fills address/city cleanly when present - only
    // fall back to the text-scraped values if it didn't.
    if (!result.address && bd.address) result.address = bd.address;
    if (!result.city && bd.city) result.city = bd.city;
    if (bd.services?.length) result.services = bd.services;
    // Only the profile's structured data carries these; no heuristic can reach
    // them. The reviews are the salon's own, already written, already earned —
    // the one thing a new site otherwise starts with none of.
    if (!result.email && bd.email) result.email = bd.email;
    if (bd.testimonials?.length) result.testimonials = bd.testimonials;
    // Bokadirekt masks phone numbers (e.g. "+467352151" with the last digits
    // hidden) - drop an obviously-truncated one rather than import a dead number.
    if (result.phone && result.phone.replace(/\D/g, "").length < 10) {
      result.phone = undefined;
    }
    result.bookingUrl = baseUrl;
  }

  // --- third-party tracking tags (GTM / GA4 / Meta / LinkedIn / HubSpot / Hotjar) ---
  const tracking = detectTrackingFromHtml(html);
  if (Object.keys(tracking).length > 0) result.tracking = tracking;

  // --- text fallbacks + vertical guess (run last, over the whole page text) ---
  // Structured sources (JSON-LD / meta / Bokadirekt) win; these only fill gaps
  // so the import works on plain marketing sites too.
  const text = htmlToText(html);
  if (!result.phone) {
    const phone = extractPhoneFromText(text);
    if (phone) result.phone = phone;
  }
  // Tracked so the vertical filter below only touches lexicon guesses — a
  // Bokadirekt menu is the owner's REAL service list and is never filtered.
  let lexiconServices = false;
  if (!result.services?.length) {
    const services = detectServicesFromText(text);
    if (services.length) {
      result.services = services;
      lexiconServices = true;
    }
  }
  const guess = classifyVertical({
    name: result.businessName,
    description: result.description,
    services: result.services,
    text,
    url: baseUrl,
  });
  result.vertical = guess.vertical;
  result.verticalConfident = guess.confident;
  if (guess.alternatives.length > 1) result.verticalAlternatives = guess.alternatives;

  // SERVICE_LEXICON is the union of EVERY vertical's service list, because the
  // detected services are themselves an input to the classifier above. That
  // breadth is right for guessing the trade and wrong for what we show the
  // owner: marketcap.se, a leadership consultancy, was offered "Behandling" — a
  // clinic word (backlog 0976). Now that the trade IS known, drop the ones that
  // belong to a different trade. Keep everything when the filter would empty
  // the list: a correctly-guessed trade wording its services unusually should
  // not end up with none.
  if (lexiconServices && result.services?.length && result.vertical !== "generic") {
    const owned = labelsForVertical(result.vertical);
    const kept = result.services.filter((s) => owned.has(s.toLowerCase()));
    if (kept.length) result.services = kept;
  }

  const platformGuess = classifyPlatform(html, baseUrl);
  if (platformGuess.platform !== "other") {
    result.platform = platformGuess.platform;
    result.platformConfident = platformGuess.confident;
  }

  // --- real images: logo + photos the owner can reuse ----------------------
  // Logo, best source first: og:logo (declared), then the wordmark in the
  // header/nav (what the owner actually recognises as "my logo"), and only then
  // the apple-touch-icon / favicon, which on most CMS templates is the
  // platform's stock icon rather than the business's mark.
  const ogLogo = meta(html, ["og:logo"]);
  let logo = ogLogo ? absolutize(ogLogo, baseUrl) : null;
  if (!logo) logo = findHeaderLogo(html, baseUrl);
  if (!logo) {
    for (const rel of ["apple-touch-icon", "shortcut icon", "icon"]) {
      const m =
        html.match(
          new RegExp(
            `<link[^>]+rel=["'][^"']*${rel}[^"']*["'][^>]*href=["']([^"']+)["']`,
            "i",
          ),
        ) ??
        html.match(
          new RegExp(
            `<link[^>]+href=["']([^"']+)["'][^>]*rel=["'][^"']*${rel}[^"']*["']`,
            "i",
          ),
        );
      if (m?.[1]) {
        logo = absolutize(decodeEntities(m[1]), baseUrl);
        if (logo) break;
      }
    }
  }
  if (logo && /^https?:/i.test(logo)) result.logoUrl = logo;

  // Photos: og:image first (usually the hero/share image), then content <img>s.
  // Filter out anything that looks like an icon / sprite / logo / tracking pixel.
  const photos: string[] = [];
  const seenImg = new Set<string>();
  const pushImg = (raw?: string | null) => {
    if (!raw || photos.length >= 8) return;
    const abs = absolutize(decodeEntities(raw), baseUrl);
    if (!abs || !/^https?:/i.test(abs)) return;
    if (/\.svg(\?|$)/i.test(abs)) return;
    if (/sprite|favicon|\bicon\b|\blogo\b|pixel|tracking|spacer|1x1|blank/i.test(abs)) return;
    const key = imageDedupeKey(abs);
    if (seenImg.has(key)) return;
    seenImg.add(key);
    photos.push(abs);
  };
  pushImg(meta(html, ["og:image", "twitter:image"]));
  for (const m of html.matchAll(/<img[^>]+src=["']([^"']+)["']/gi)) {
    if (photos.length >= 8) break;
    pushImg(m[1]);
  }
  if (photos.length) result.imageUrls = photos;

  // Import v2: the owner's actual content (bounded extractors below).
  const copyBlocks = extractCopyBlocks(html);
  if (copyBlocks.length) result.copyBlocks = copyBlocks;

  // Description fallback: plenty of small-business sites ship no meta
  // description at all, and an empty description meant onboarding showed the
  // owner a blank "what you do" and the AI copywriter got nothing to work from.
  // Their own <h1> is the closest thing to a tagline; the first body paragraph
  // is the next best.
  if (!result.description) {
    const h1 = firstHeadingText(html);
    const fallback = h1 && h1.length >= 10 ? h1 : copyBlocks[0]?.text;
    if (fallback && fallback.length >= 10) result.description = fallback.slice(0, 600);
  }
  const testimonials = extractTestimonials(html);
  if (testimonials.length) result.testimonials = testimonials;
  const prices = extractPrices(html);
  if (prices.length) result.prices = prices;

  // An existing store is a FINDING, not an outcome: recorded here so the import
  // can ask the owner about it, never acted on.
  const commerce = detectCommerce({ html, baseUrl });
  if (commerce) result.commerce = commerce;

  // Brand colour: the site's declared theme-color (or MS tile colour). A
  // suggestion only — snapped to the nearest AA-safe theme preset downstream,
  // never injected as raw hex (P3).
  const themeColor = normalizeHexColor(
    meta(html, ["theme-color", "msapplication-TileColor"]),
  );
  if (themeColor) result.themeColor = themeColor;

  return result;
}

/** Accept a 3- or 6-digit hex colour (with/without `#`) and return #rrggbb,
 *  else undefined. Named CSS colours and non-hex values are ignored — only an
 *  unambiguous hex is a reliable brand signal. */
function normalizeHexColor(raw: string | undefined): string | undefined {
  if (!raw) return undefined;
  const h = raw.trim().replace(/^#/, "");
  if (/^[0-9a-fA-F]{3}$/.test(h)) {
    return (
      "#" +
      h
        .split("")
        .map((c) => c + c)
        .join("")
        .toLowerCase()
    );
  }
  if (/^[0-9a-fA-F]{6}$/.test(h)) return "#" + h.toLowerCase();
  return undefined;
}

/** Same-host content links for the bounded crawl: nav/anchor hrefs that look
 *  like content pages (no files/mailto/anchors), deduped, ≤6. */
/** Paths carrying the owner's real business facts, in crawl order. A bounded
 *  crawl must reach these BEFORE deep archive pages — taking links in DOM order
 *  (the previous behaviour) spent the budget on whatever the nav happened to
 *  list first, so a site whose menu starts with a blog imported no services.
 *  sv + en + common builder slugs. Lower rank crawls first. */
const PRIORITY_PATTERNS: RegExp[] = [
  /^\/?$/,
  /(tjanster|tjänster|services|behandlingar|priser|prices|pricing|prislista)/i,
  /(om-oss|om_oss|about|omoss|historia|team|personal|medarbetare)/i,
  /(kontakt|contact|hitta-hit|find-us|oppettider|öppettider|hours)/i,
  /(boka|booking|book|tidsbokning|offert|quote)/i,
  /(galleri|gallery|portfolio|arbeten|case|referenser|recensioner|reviews)/i,
];

/** Rank a URL for crawl order. Shared by the onboarding scrape and the
 *  whole-site import provider so both agree on what matters. */
export function urlPriority(url: string): number {
  let path: string;
  try {
    path = new URL(url).pathname;
  } catch {
    return PRIORITY_PATTERNS.length + 6;
  }
  for (let i = 0; i < PRIORITY_PATTERNS.length; i++) {
    if (PRIORITY_PATTERNS[i].test(path)) return i;
  }
  // Unmatched: shallower paths still beat deep archive URLs.
  const depth = path.split("/").filter(Boolean).length;
  return PRIORITY_PATTERNS.length + Math.min(depth, 5);
}

export function extractInternalLinks(html: string, baseUrl: string): string[] {
  const base = (() => {
    try {
      return new URL(baseUrl);
    } catch {
      return null;
    }
  })();
  if (!base) return [];
  // Honour <base href>: builder exports emit relative hrefs that only resolve
  // against it, and resolving against the page URL yields dead links.
  let resolveAgainst: URL = base;
  const baseTag = html.match(/<base[^>]+href=["']([^"']+)["']/i)?.[1];
  if (baseTag) {
    try {
      resolveAgainst = new URL(baseTag, base);
    } catch {
      /* malformed base href — keep the page URL */
    }
  }
  const out: string[] = [];
  const seen = new Set<string>([base.origin + base.pathname.replace(/\/$/, "")]);
  for (const m of html.matchAll(/<a[^>]+href=["']([^"'#?]+)["']/gi)) {
    const href = m[1];
    if (/^(mailto:|tel:|javascript:|data:)/i.test(href)) continue;
    let abs: URL;
    try {
      abs = new URL(href, resolveAgainst);
    } catch {
      continue;
    }
    if (abs.hostname !== base.hostname) continue;
    if (/\.(png|jpe?g|webp|svg|gif|pdf|zip|css|js|xml|ico)$/i.test(abs.pathname)) continue;
    const key = abs.origin + abs.pathname.replace(/\/$/, "");
    if (seen.has(key)) continue;
    // Prefer content-ish paths; skip login/cart/etc. A cart or checkout page is
    // still never crawled - it is a signal, not content - but it is no longer
    // simply thrown away either: detectCommerce counts it from the same HTML.
    if (/(login|cart|checkout|admin|wp-json|privacy|cookie|terms)/i.test(abs.pathname)) continue;
    seen.add(key);
    out.push(key);
  }
  // Rank the whole set, then cap — so the cap keeps the BEST links, not the
  // first ones encountered.
  return out.sort((a, b) => urlPriority(a) - urlPriority(b)).slice(0, 6);
}

/** Merge a subpage's extraction into the main result: content accumulates
 *  (bounded), scalar facts keep the FIRST (landing page) value. */
export function mergeScrapeResults(
  main: ScrapeResult,
  sub: ScrapeResult,
): ScrapeResult {
  const merged: ScrapeResult = { ...main };
  merged.copyBlocks = [...(main.copyBlocks ?? []), ...(sub.copyBlocks ?? [])].slice(0, 12);
  if (!merged.copyBlocks.length) delete merged.copyBlocks;
  const seenQuotes = new Set((main.testimonials ?? []).map((q) => q.text.slice(0, 60).toLowerCase()));
  merged.testimonials = [
    ...(main.testimonials ?? []),
    ...(sub.testimonials ?? []).filter((q) => !seenQuotes.has(q.text.slice(0, 60).toLowerCase())),
  ].slice(0, 6);
  if (!merged.testimonials.length) delete merged.testimonials;
  const seenPrices = new Set((main.prices ?? []).map((p) => p.label.toLowerCase()));
  merged.prices = [
    ...(main.prices ?? []),
    ...(sub.prices ?? []).filter((p) => !seenPrices.has(p.label.toLowerCase())),
  ].slice(0, 12);
  if (!merged.prices.length) delete merged.prices;
  const seenImgs = new Set(main.imageUrls ?? []);
  merged.imageUrls = [
    ...(main.imageUrls ?? []),
    ...(sub.imageUrls ?? []).filter((u) => !seenImgs.has(u)),
  ].slice(0, 8);
  if (!merged.imageUrls.length) delete merged.imageUrls;
  // A store found on ANY crawled page counts - a shop's cart link often lives
  // on /butik, not on the landing page - so the stronger finding wins.
  const commerce = mergeCommerceDetections(main.commerce, sub.commerce);
  if (commerce) merged.commerce = commerce;
  // Fill scalar gaps only (landing page wins).
  for (const key of ["phone", "email", "address", "city", "bookingUrl"] as const) {
    if (!merged[key] && sub[key]) merged[key] = sub[key];
  }
  if ((!merged.services || merged.services.length === 0) && sub.services) {
    merged.services = sub.services;
  }
  // Hours are a whole weekly schedule, so a subpage's set is taken only when
  // the landing page had none - never merged row by row, which would splice two
  // businesses' weeks together on a page that links out to a partner. The
  // "couldn't read" note travels with the schedule it describes, or it would
  // report days against a week it did not come from.
  if (!merged.hours?.length && sub.hours?.length) {
    merged.hours = sub.hours;
    merged.hoursUnreadableDays = sub.hoursUnreadableDays;
  }
  return merged;
}


// ---------------------------------------------------------------------------
// Import v2 extractors: the switcher's actual CONTENT (copy, proof, prices),
// not just the business card. Pure regex over raw HTML - bounded everywhere.
// ---------------------------------------------------------------------------

/** Strip tags/scripts and collapse whitespace for a text fragment. */
function plainText(fragment: string): string {
  return decodeEntities(
    fragment
      .replace(/<script[\s\S]*?<\/script>/gi, " ")
      .replace(/<style[\s\S]*?<\/style>/gi, " ")
      .replace(/<[^>]+>/g, " ")
      .replace(/\s+/g, " ")
      .trim(),
  );
}

/** Menu/CTA chrome inside a copy fragment. Many builders (Framer, Squarespace
 *  templates…) render their nav as plain links inside a div/p with no semantic
 *  <header>/<nav>, so the tag-strip above never catches it - and "Hem Kontakt
 *  Boka nu" leaked into the About seed as if it were the owner's own words.
 *  Strategy: always drop <button> content; drop <a> content too when links
 *  dominate the block (link-density heuristic, same idea as readability). A
 *  legit paragraph with one inline link keeps it. */
function stripChrome(fragment: string): string {
  let cleaned = fragment.replace(/<button[\s\S]*?<\/button>/gi, " ");
  // Leading anchors ("Anna Hedin", "Kontakt"…) before any real text are chrome
  // (logo + menu), never the owner's words - strip them one by one until the
  // block starts with non-link text. An inline link later in a sentence stays.
  for (;;) {
    const m = /<a\b[\s\S]*?<\/a>/i.exec(cleaned);
    if (!m || plainText(cleaned.slice(0, m.index)).length > 0) break;
    cleaned = `${cleaned.slice(0, m.index)} ${cleaned.slice(m.index + m[0].length)}`;
  }
  const full = plainText(cleaned);
  if (full.length === 0) return full;
  // Remaining links: keep them unless they dominate the block (a menu row that
  // happens to carry some plain text) - readability's link-density idea.
  const noLinks = plainText(cleaned.replace(/<a\b[\s\S]*?<\/a>/gi, " "));
  const linkShare = 1 - noLinks.length / full.length;
  return linkShare > 0.35 ? noLinks : full;
}

/** The owner's body copy as heading+paragraph blocks, in page order. Bounded:
 *  ≤8 blocks, ≤400 chars each, ≤2400 chars total. Skips boilerplate (cookie/
 *  copyright/menu-ish short strings). */
export function extractCopyBlocks(
  html: string,
): Array<{ heading?: string; text: string }> {
  const body = html.replace(/<(header|nav|footer)[\s\S]*?<\/\1>/gi, " ");
  const blocks: Array<{ heading?: string; text: string }> = [];
  let total = 0;
  const re = /<(h[1-3])[^>]*>([\s\S]*?)<\/\1>|<p\b[^>]*>([\s\S]*?)<\/p>/gi;
  let pendingHeading: string | undefined;
  let match: RegExpExecArray | null;
  const boilerplate = /cookie|copyright|©|integritet|privacy|villkor|terms/i;
  while ((match = re.exec(body)) && blocks.length < 8 && total < 2400) {
    if (match[1]) {
      const heading = stripChrome(match[2] ?? "").slice(0, 90);
      if (heading.length >= 3 && !boilerplate.test(heading)) pendingHeading = heading;
      continue;
    }
    const text = stripChrome(match[3] ?? "").slice(0, 400);
    if (text.length < 60 || boilerplate.test(text)) continue;
    blocks.push({ ...(pendingHeading ? { heading: pendingHeading } : {}), text });
    pendingHeading = undefined;
    total += text.length;
  }
  return blocks;
}


// ---------------------------------------------------------------------------
// "Read this page for me" - the chat agent's page reader.
//
// `extractFromHtml` above answers a different question ("who is this business,
// so we can pre-fill onboarding"), and it caps body copy at 8 blocks / 2400
// characters, so it cannot answer a question ABOUT a page. This one can.
//
// It is an ALLOW-LIST, not a deny-list, and that is the whole security design:
// the returned object has exactly four fields and nothing else from the source
// document can reach the model by accident. No images, no logo, no brand
// colour, no tracking ids, no socials, no commerce flags - not because each is
// stripped, but because none is ever read.
// ---------------------------------------------------------------------------

/** Everything the chat agent is ever given about someone else's page. */
export type ReadablePage = {
  /** The document title, trimmed. */
  title?: string;
  /** The meta/og description, trimmed. */
  description?: string;
  /** `h1`-`h3` in page order, so the model can describe the page's structure. */
  outline: Array<{ level: 1 | 2 | 3; text: string }>;
  /** Body copy with script/style/nav/header/footer removed, hard-capped. */
  text: string;
};

/** Body text handed to the model, in characters (~2000 tokens). The cap is a
 *  cost control as much as a context one - the page text is re-sent with every
 *  later message in the same thread. */
export const READABLE_TEXT_LIMIT = 8000;

/** The readable content of an arbitrary web page: title, description, heading
 *  outline and body text. Returns `null` when the page yields nothing worth
 *  reading, so a caller can say "I could not read that page" instead of
 *  answering confidently about an empty string. */
export function extractReadableText(html: string): ReadablePage | null {
  const titleTag = html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1];
  const title = titleTag ? plainText(titleTag).slice(0, 200) : undefined;
  const description = meta(html, [
    "description",
    "og:description",
    "twitter:description",
  ])?.slice(0, 400);

  // Chrome is dropped before anything is read: a nav row repeated on every page
  // of a site is not what the owner pointed at, and it crowds out the cap.
  const body = html
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<noscript[\s\S]*?<\/noscript>/gi, " ")
    .replace(/<svg[\s\S]*?<\/svg>/gi, " ")
    .replace(/<!--[\s\S]*?-->/g, " ")
    .replace(/<(header|nav|footer|form)[\s\S]*?<\/\1>/gi, " ");

  const outline: Array<{ level: 1 | 2 | 3; text: string }> = [];
  const headingRe = /<h([1-3])[^>]*>([\s\S]*?)<\/h\1>/gi;
  let hm: RegExpExecArray | null;
  while ((hm = headingRe.exec(body)) && outline.length < 40) {
    const text = plainText(hm[2] ?? "").slice(0, 160);
    if (text.length < 2) continue;
    outline.push({ level: Number(hm[1]) as 1 | 2 | 3, text });
  }

  // Block-level text in page order. Headings stay in the flow so a paragraph
  // still reads under the heading it belongs to.
  const parts: string[] = [];
  let total = 0;
  const blockRe =
    /<(h[1-6]|p|li|blockquote|td|th|dd|dt|figcaption)[^>]*>([\s\S]*?)<\/\1>/gi;
  let bm: RegExpExecArray | null;
  while ((bm = blockRe.exec(body)) && total < READABLE_TEXT_LIMIT) {
    const text = plainText(bm[2] ?? "");
    if (text.length < 2) continue;
    parts.push(text);
    total += text.length + 1;
  }
  // A page whose copy lives in bare divs (many builders) yields no block match
  // at all. Fall back to the whole body as one run rather than reporting an
  // empty read - an empty read is the failure this whole lane exists to avoid.
  const joined =
    parts.length > 0 ? parts.join("\n") : plainText(body);
  const text = joined.slice(0, READABLE_TEXT_LIMIT).trim();

  if (text.length < 40 && outline.length === 0 && !title) return null;
  return {
    ...(title ? { title } : {}),
    ...(description ? { description } : {}),
    outline,
    text,
  };
}

/** The page's first real `<h1>` (or `<h2>` when it has none), outside header/
 *  nav/footer chrome. Used only as a description fallback. */
export function firstHeadingText(html: string): string | undefined {
  const body = html.replace(/<(header|nav|footer)[\s\S]*?<\/\1>/gi, " ");
  for (const tag of ["h1", "h2"]) {
    const re = new RegExp(`<${tag}[^>]*>([\\s\\S]*?)</${tag}>`, "gi");
    let m: RegExpExecArray | null;
    while ((m = re.exec(body))) {
      const text = stripChrome(m[1] ?? "").slice(0, 300);
      if (text.length >= 10) return text;
    }
  }
  return undefined;
}

/** Customer quotes: blockquotes and elements whose class names look like
 *  reviews/testimonials. Bounded ≤5, 40-320 chars, deduped. */
export function extractTestimonials(
  html: string,
): Array<{ text: string; author?: string }> {
  const out: Array<{ text: string; author?: string }> = [];
  const seen = new Set<string>();
  const push = (raw: string, author?: string) => {
    const text = plainText(raw).slice(0, 320);
    if (text.length < 40) return;
    const key = text.toLowerCase().slice(0, 60);
    if (seen.has(key)) return;
    seen.add(key);
    out.push({ text, ...(author ? { author: author.slice(0, 60) } : {}) });
  };
  const bq = /<blockquote[^>]*>([\s\S]*?)<\/blockquote>/gi;
  let match: RegExpExecArray | null;
  while ((match = bq.exec(html)) && out.length < 5) {
    const inner = match[1] ?? "";
    const cite = /<(?:cite|footer)[^>]*>([\s\S]*?)<\/(?:cite|footer)>/i.exec(inner);
    push(inner.replace(/<(?:cite|footer)[\s\S]*$/i, ""), cite ? plainText(cite[1]) : undefined);
  }
  const cls = /<(div|p|li)[^>]*class="[^"]*(?:testimonial|review|omdome|omdöme|recension)[^"]*"[^>]*>([\s\S]*?)<\/\1>/gi;
  while ((match = cls.exec(html)) && out.length < 5) {
    push(match[2] ?? "");
  }
  return out;
}

/** Price mentions: a short label followed by an SEK amount on the same line
 *  ("Klippning 450 kr", "Flyttstädning från 1 500 kr"). Bounded ≤10. */
export function extractPrices(
  html: string,
): Array<{ label: string; priceText: string }> {
  const text = plainText(html.replace(/<\/(p|li|td|h[1-6]|div|tr)>/gi, "\n$&"));
  const out: Array<{ label: string; priceText: string }> = [];
  const seen = new Set<string>();
  const re = /([A-ZÅÄÖ][\p{L} &-]{2,40}?)[\s:.…-]*((?:från\s+)?\d[\d\s.,]{0,8}\s?(?:kr|:-|SEK)(?:\/(?:tim|h|mån|st))?)/gu;
  let match: RegExpExecArray | null;
  while ((match = re.exec(text)) && out.length < 10) {
    const label = match[1].trim().replace(/\s+/g, " ");
    const priceText = match[2].trim().replace(/\s+/g, " ");
    if (label.length < 3 || /cookie|copyright|moms|vat|orgnr/i.test(label)) continue;
    const key = label.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push({ label, priceText });
  }
  return out;
}
