// GENERATED by scripts/mirror-import.ts from HH-Studio/simple-site-builder:lib/import/bandContent.ts
// Do not edit. Run `bun scripts/mirror-import.ts --sync-from-app <appRoot>`.

import type { SectionType } from "../../../convex/model/sections";
import { decodeHtmlEntities } from "../html/entities";
import { attributeValue } from "../html/attributes";
import { proseKey } from "./structureDetect";

// ---------------------------------------------------------------------------
// Build a section from ONE band of a source page.
//
// Why this exists, measured. `buildPageSections` runs a ladder of detectors
// over the WHOLE page, and a band no detector recognises produces nothing at
// all. Over 14 pages of 9 real Swedish small-business sites
// (`scripts/import/measure-import-fidelity.ts`), that meant **54% of the
// source's block-level text runs of 40+ characters reached the draft**. The
// losses were not page furniture: on one dentist's home page they were the
// invoicing policy, the payment-reminder fee, the late-cancellation fee, the door code, how to
// book, and a farewell letter from a departing dentist. A person rebuilding
// that site by hand does not get a starting point; they get a rewrite.
//
// So: every band the ladder passed over is offered here, and what comes back is
// a real section built from THAT band's markup. Nothing is invented — each
// builder below either finds what its type needs in the band or returns null,
// and `richText` is the catch-all that keeps the words even when no shape fits.
// A plain text block carrying the owner's own policy beats a prettier page that
// silently dropped it.
//
// Pure and regex-based like the rest of `lib/import`, so it runs inside a
// Convex action and is unit-testable.
// ---------------------------------------------------------------------------

/** A picture the caller has already put in the asset registry. */
export type BandImage = { assetId: string; alt: string };

export type BandInput = {
  /** The band's own markup, nothing else. */
  html: string;
  baseUrl: string;
  /** Register an image and get its export id, or null once the cap is hit. */
  register: (url: string, alt: string) => string | null;
  /** Prose already used by another section, so a band cannot repeat it. */
  claimed: ReadonlySet<string>;
  /**
   * The markup's links are already OURS, so a root-relative one is kept.
   *
   * Set when a captured band graduates: the capture's links were rewritten to
   * local paths when the site was imported, and `graduateImportedSection` has
   * only the source's own address to offer as `baseUrl`. Resolving `/kontakt`
   * against it sent the visitor back to the provider the owner migrated away
   * from, and broke the link outright once that hosting was cancelled.
   */
  keepSitePaths?: boolean;
  /** Only retain content left over after another detector claimed this band. */
  residualOnly?: boolean;
};

export type BandSection = { type: SectionType; content: Record<string, unknown> };

// --- primitives -------------------------------------------------------------

function text(html: string): string {
  return decodeHtmlEntities(html.replace(/<[^>]+>/g, " "))
    .replace(/\s+/g, " ")
    .trim();
}

/** The band's own heading, and where it ended, so the rest can be read after
 *  it rather than including it twice. */
function headingOf(html: string): { text: string; end: number } | null {
  const m = html.match(/<h([1-4])[^>]*>([\s\S]*?)<\/h\1>/i);
  if (!m) return null;
  const value = text(m[2]);
  if (!value || value.length > 160) return null;
  return { text: value, end: (m.index ?? 0) + m[0].length };
}

/** Every subheading below the band's own, in order. */
function subheadings(html: string, after: number): Array<{ text: string; at: number }> {
  const out: Array<{ text: string; at: number }> = [];
  for (const m of html.matchAll(/<h([2-6])[^>]*>([\s\S]*?)<\/h\1>/gi)) {
    const at = m.index ?? 0;
    if (at < after) continue;
    const value = text(m[2]);
    if (value && value.length <= 160) out.push({ text: value, at });
  }
  return out;
}

function paragraphs(html: string, min = 40): Array<{ text: string; at: number }> {
  const out: Array<{ text: string; at: number }> = [];
  for (const m of html.matchAll(/<p\b[^>]*>([\s\S]*?)<\/p>/gi)) {
    const value = text(m[1]);
    if (value.length >= min) out.push({ text: value, at: m.index ?? 0 });
  }
  return out;
}

/** Block-level tags whose end is a line break to a reader. */
const BLOCK_END =
  /<\/(p|div|section|article|header|footer|li|td|th|tr|h[1-6]|blockquote|figcaption|dd|dt|br)\s*>|<br\s*\/?>/gi;

/**
 * Runs of readable text in the band, whatever tag holds them.
 *
 * `paragraphs` only sees `<p>`, and a great deal of the real web does not use
 * it: Wix, Squarespace and most page builders emit `<div>` for body copy, and
 * three of the nine sites in the fidelity corpus kept every word of their page
 * outside a single `<p>` tag. Those pages scored 0% word survival until this
 * existed - not because the importer could not place the text, but because it
 * could not SEE it.
 *
 * Links are dropped: a run that is entirely a link is navigation or a button,
 * and it arrives through the CTA and menu paths instead.
 */
function textRuns(html: string, min = 40): Array<{ text: string; at: number }> {
  const out: Array<{ text: string; at: number }> = [];
  const withoutLinks = html.replace(/<a\b[^>]*>[\s\S]*?<\/a>/gi, (m) => " ".repeat(m.length));
  let cursor = 0;
  for (const m of withoutLinks.matchAll(BLOCK_END)) {
    const end = m.index ?? 0;
    const value = text(withoutLinks.slice(cursor, end));
    if (value.length >= min) out.push({ text: value, at: cursor });
    cursor = end + m[0].length;
  }
  const tail = text(withoutLinks.slice(cursor));
  if (tail.length >= min) out.push({ text: tail, at: cursor });
  return out;
}

function listBlocks(html: string): Array<{ items: string[]; at: number }> {
  const out: Array<{ items: string[]; at: number }> = [];
  for (const m of html.matchAll(/<(ul|ol)\b[^>]*>([\s\S]*?)<\/\1>/gi)) {
    const items = [...m[2].matchAll(/<li\b[^>]*>([\s\S]*?)<\/li>/gi)]
      .map((li) => text(li[1]))
      .filter((v) => v.length >= 2 && v.length <= 300);
    // A list that is mostly links is navigation wearing a different tag.
    const linked = [...m[2].matchAll(/<a\b[^>]*>/gi)].length;
    if (items.length >= 2 && linked < items.length) out.push({ items, at: m.index ?? 0 });
  }
  return out;
}

function quotes(html: string): string[] {
  return [...html.matchAll(/<(blockquote|q)\b[^>]*>([\s\S]*?)<\/\1>/gi)]
    .map((m) => text(m[2]))
    .filter((v) => v.length >= 20);
}

const DECORATIVE = /(icon|logo|sprite|favicon|avatar|badge|pixel|spacer|blank|placeholder)/i;

/** A picture this site already hosts, named by its asset row rather than by an
 *  address. `nativeTwin` writes it for a captured image the import re-hosted,
 *  and the caller's `register` hook is the only thing that reads it - so it has
 *  to reach that hook instead of being refused here for not looking like a URL.
 *  Refusing it graduated a band without its own photograph and reported
 *  nothing lost. */
const ASSET_SCHEME = /^asset:[A-Za-z0-9_-]+$/;

/** An address the site itself serves, kept as written. */
function sitePath(href: string): boolean {
  return href.startsWith("/") && !href.startsWith("//");
}

/** Every picture in the band, with WHERE each one sits, so a card can be paired
 *  with the photograph that belongs to it. Callers that only want the pictures
 *  ignore `at`. (2643) */
function images(html: string, baseUrl: string): Array<{ url: string; alt: string; at: number }> {
  const out: Array<{ url: string; alt: string; at: number }> = [];
  for (const m of html.matchAll(/<img[^>]*>/gi)) {
    const tag = m[0];
    const at = m.index ?? 0;
    if (DECORATIVE.test(tag)) continue;
    const src = tag.match(/\ssrc=["']([^"']+)["']/i)?.[1];
    if (!src) continue;
    if (ASSET_SCHEME.test(src)) {
      out.push({ url: src, alt: text(attributeValue(tag, "alt") ?? ""), at });
      continue;
    }
    try {
      const abs = new URL(decodeHtmlEntities(src), baseUrl).toString();
      if (!/^https?:/i.test(abs)) continue;
      out.push({ url: abs, alt: text(attributeValue(tag, "alt") ?? ""), at });
    } catch {
      // An unparseable src is not a picture we can carry.
    }
  }
  return out;
}

/** The band's most CTA-like link: a real destination with a short label. */
function ctaOf(
  html: string,
  baseUrl: string,
  keepSitePaths = false,
): { label: string; url: string } | null {
  for (const m of html.matchAll(/<a\b([^>]*)>([\s\S]*?)<\/a>/gi)) {
    const href = m[1].match(/\shref=["']([^"']+)["']/i)?.[1];
    if (!href) continue;
    const label = text(m[2]);
    if (!label || label.length > 40) continue;
    const decoded = decodeHtmlEntities(href);
    if (keepSitePaths && sitePath(decoded)) return { label, url: decoded };
    try {
      const abs = new URL(decodeHtmlEntities(href), baseUrl).toString();
      if (!/^https?:|^mailto:|^tel:/i.test(abs)) continue;
      return { label, url: abs };
    } catch {
      continue;
    }
  }
  return null;
}

function unclaimed(value: string, claimed: ReadonlySet<string>): boolean {
  return !claimed.has(proseKey(value));
}

// --- per-type builders ------------------------------------------------------
//
// Each returns null unless the band genuinely holds what its type needs. Order
// matters only in `AUTO_ORDER` below; a proposal names its type directly.

function statement(input: BandInput): BandSection | null {
  const found = quotes(input.html);
  const value = found.find((q) => q.length <= 320 && unclaimed(q, input.claimed));
  if (!value) return null;
  return { type: "statement", content: { type: "statement", text: value } };
}

function ctaBand(input: BandInput): BandSection | null {
  const heading = headingOf(input.html);
  if (!heading) return null;
  const cta = ctaOf(input.html, input.baseUrl, input.keepSitePaths);
  if (!cta) return null;
  const paras = paragraphs(input.html, 30).filter((p) => unclaimed(p.text, input.claimed));
  // A cta-band is a heading, at most one line, and an action. More prose than
  // that and the band is an article that happens to end in a link.
  if (paras.length > 1) return null;
  return {
    type: "cta-band",
    content: {
      type: "cta-band",
      headline: heading.text,
      ...(paras[0] ? { subtext: paras[0].text } : {}),
      primaryCta: { label: cta.label, target: { kind: "url", url: cta.url } },
    },
  };
}

function gallery(input: BandInput): BandSection | null {
  const found = images(input.html, input.baseUrl);
  if (found.length < 3) return null;
  // A band with a lot of prose is an article with pictures, not a gallery.
  if (paragraphs(input.html).length > 1) return null;
  const registered = found
    .map((i) => ({ id: input.register(i.url, i.alt), alt: i.alt }))
    .filter((r): r is { id: string; alt: string } => r.id !== null);
  if (registered.length < 3) return null;
  return {
    type: "gallery",
    content: {
      type: "gallery",
      images: registered.map((r) => ({ assetId: r.id, alt: r.alt })),
    },
  };
}

function image(input: BandInput): BandSection | null {
  const found = images(input.html, input.baseUrl);
  if (found.length !== 1) return null;
  if (paragraphs(input.html).length > 0) return null;
  const id = input.register(found[0].url, found[0].alt);
  if (!id) return null;
  return {
    type: "image",
    content: {
      type: "image",
      image: { assetId: id },
      ...(found[0].alt ? { caption: found[0].alt } : {}),
    },
  };
}

/**
 * Subheading + prose pairs, which is what a "cards" band looks like in markup
 * once the wrapper classes are gone.
 *
 * A card takes EVERY paragraph under its subheading, not just the first one.
 * Taking only the first is how the dentist home page lost its payment terms:
 * the announcement band paired each heading with one line and dropped the four
 * paragraphs that followed, and because a cards builder outranks `richText`
 * nothing else ever saw them. A genuine three-card band has one paragraph per
 * card, so joining changes nothing there. (2643)
 */
function cards(input: BandInput): Array<{ title: string; description: string }> {
  const heading = headingOf(input.html);
  const heads = subheadings(input.html, heading ? heading.end : 0);
  if (heads.length < 2) return [];
  const paras = paragraphs(input.html, 20);
  const out: Array<{ title: string; description: string }> = [];
  for (let i = 0; i < heads.length; i++) {
    const from = heads[i].at;
    const to = heads[i + 1]?.at ?? Number.POSITIVE_INFINITY;
    const body = paras
      .filter((p) => p.at > from && p.at < to && unclaimed(p.text, input.claimed))
      .map((p) => p.text);
    if (body.length === 0) continue;
    out.push({ title: heads[i].text, description: body.join("\n\n") });
  }
  return out;
}

/**
 * A grid of LINKS under one heading: "Våra behandlingar" over nine buttons,
 * each going to that treatment's own page.
 *
 * This is what a services row looks like on a page builder that renders each
 * card as a button module, and it is the single most common thing the corpus
 * labelled `services` and the importer produced nothing for (backlog 2643). The
 * band has almost no prose - the label IS the content - so `cards` finds no
 * subheading-plus-paragraph pairs, `richText` finds no run to keep, and the
 * heading came back later as a title-only card under "Det vi gör" while the
 * links themselves were dropped.
 *
 * Nothing is invented: each card is one link's own label and its own
 * destination. The gates are structural. Three or more distinct destinations,
 * because two links under a heading is a paragraph with a "read more". Distinct
 * LABELS, because three buttons all saying "Läs mer" name nothing a visitor
 * could choose between - that band is a picture grid whose labels live in the
 * pictures, and it is not this one. At most one paragraph, because a band with
 * real prose is an article that happens to end in links.
 *
 * The band's heading has to read as a heading. The restaurant in the corpus
 * keeps a copy of its menu in the body, under a "heading" that is the whole of
 * one branch's address: name, phone number, street and opening hours, 100
 * characters of it. That imported as five services called "HEM", "Om Mogge
 * Sushi" and so on. A row of what a business sells is titled in a few words,
 * and a title carrying a phone number or a postcode is not a title.
 */
/** A phone number or a Swedish postcode: the marks of an address block wearing
 *  a heading tag. Exported because the leftover-heading card list in
 *  `htmlToSections` needs the same test on the same corpus page. (2643) */
export const CONTACT_DETAIL = /(\b\d{3}\s?\d{2}\b|\btel\b|\+46|\b0\d{1,3}[-\s]\d)/i;

function linkGrid(input: BandInput): BandSection | null {
  const heading = headingOf(input.html);
  if (!heading) return null;
  if (heading.text.length > 60 || CONTACT_DETAIL.test(heading.text)) return null;
  if (paragraphs(input.html, 40).length > 1) return null;
  const seenUrl = new Set<string>();
  const seenLabel = new Set<string>();
  const items: Array<{ title: string; cta: { label: string; target: { kind: "url"; url: string } } }> =
    [];
  for (const m of input.html.matchAll(/<a\b([^>]*)>([\s\S]*?)<\/a>/gi)) {
    if ((m.index ?? 0) < heading.end) continue;
    const href = m[1].match(/\shref=["']([^"']+)["']/i)?.[1];
    if (!href) continue;
    const label = text(m[2]);
    // A label long enough to be a sentence is prose wearing a link, and one too
    // short to read is an icon.
    if (label.length < 2 || label.length > 48) continue;
    let url: string;
    const decoded = decodeHtmlEntities(href);
    if (input.keepSitePaths && sitePath(decoded)) {
      url = decoded;
    } else {
      try {
        url = new URL(decoded, input.baseUrl).toString();
      } catch {
        continue;
      }
      if (!/^https?:/i.test(url)) continue;
    }
    const key = proseKey(label);
    if (seenUrl.has(url) || seenLabel.has(key)) continue;
    seenUrl.add(url);
    seenLabel.add(key);
    items.push({ title: label, cta: { label, target: { kind: "url", url } } });
  }
  if (items.length < 3) return null;
  return {
    type: "services",
    content: { type: "services", heading: heading.text, items: items.slice(0, 12) },
  };
}

/**
 * A row of PICTURE cards: a photograph, a title, and usually a caption,
 * repeated across the band.
 *
 * Measured gap (backlog 2643, `theskinlab`). The source shows one row of cards
 * with a photograph on each. The importer produced TWO sections from it: a
 * `gallery` of unlabelled photos, because `gallery` runs first and a card row
 * carries three or more pictures with almost no prose, and then a `highlights`
 * of the captions with no pictures at all. One row of the source became two
 * bands on our side, and neither of them is what the owner had.
 *
 * The pairing is deliberately strict rather than clever: the band must hold
 * exactly as many pictures as it holds card titles, and they are then zipped in
 * document order. That reads both of the two common markups - the photograph
 * above its title, and the title above its photograph - and it refuses the
 * ambiguous case (a hero picture plus three cards) instead of guessing which
 * photograph belongs to which card. A wrong photograph on a card is worse than
 * the two-band split it replaces, because nobody looking at the page can see
 * that it is wrong.
 *
 * Nothing is invented: every title, caption and picture is the band's own.
 */
function pictureCards(input: BandInput): BandSection | null {
  const heading = headingOf(input.html);
  if (!heading) return null;
  const heads = subheadings(input.html, heading.end);
  if (heads.length < 2) return null;
  const pictures = images(input.html, input.baseUrl).filter((i) => i.at > heading.end);
  if (pictures.length !== heads.length) return null;

  const paras = paragraphs(input.html, 20);
  const items: Array<{ title: string; description: string; media: { assetId: string } }> = [];
  for (let i = 0; i < heads.length; i++) {
    const from = heads[i].at;
    const to = heads[i + 1]?.at ?? Number.POSITIVE_INFINITY;
    const body = paras
      .filter((p) => p.at > from && p.at < to && unclaimed(p.text, input.claimed))
      .map((p) => p.text)
      .join("\n\n");
    // Every card says something. Measured against `dinatandlakare`'s home band,
    // which is a hero: two decorative pictures under two headings that are both
    // the practice's own name, with not one word between them. Without this bar
    // it arrived as a two-card row titled "Dina Tandläkare" twice, which is
    // worse than the rich text it used to become.
    if (!body) return null;
    const assetId = input.register(pictures[i].url, pictures[i].alt);
    // One picture we cannot carry and the row stops being a picture row. Fall
    // through and let `gallery` or the plain card builder have it.
    if (!assetId) return null;
    items.push({ title: heads[i].text, description: body, media: { assetId } });
  }
  if (items.length < 2) return null;
  // Cards a visitor could not tell apart are not cards. Same band as above: a
  // repeated site name under each photograph names nothing to choose between.
  if (new Set(items.map((i) => proseKey(i.title))).size !== items.length) return null;

  return {
    type: "highlights",
    content: { type: "highlights", heading: heading.text, items },
  };
}

function cardSection(type: "highlights" | "services" | "process") {
  return (input: BandInput): BandSection | null => {
    const heading = headingOf(input.html);
    if (!heading) return null;
    const items = cards(input);
    if (items.length < 2) return null;
    const key = type === "process" ? "steps" : "items";
    return {
      type,
      content: { type, heading: heading.text, [key]: items },
    };
  };
}

/**
 * The catch-all, and the reason the words survive at all.
 *
 * Anything the band holds that a reader would read: its heading, its
 * subheadings, its paragraphs and its lists, in document order. It is the last
 * builder tried and it deliberately has the loosest bar, because the
 * alternative for a band nothing else recognised is that the owner's writing is
 * silently dropped.
 */
function richText(input: BandInput): BandSection | null {
  const foundHeading = headingOf(input.html);
  const heading =
    foundHeading && unclaimed(foundHeading.text, input.claimed) ? foundHeading : null;
  const headingEnd = foundHeading?.end ?? 0;
  type Block =
    | { at: number; block: { kind: "h"; level: 2 | 3; text: string } }
    | { at: number; block: { kind: "p"; text: string } }
    | { at: number; block: { kind: "ul"; items: string[] } };
  const blocks: Block[] = [];

  for (const h of subheadings(input.html, headingEnd)) {
    if (!unclaimed(h.text, input.claimed)) continue;
    blocks.push({ at: h.at, block: { kind: "h", level: 3, text: h.text } });
  }
  // Runs, not `<p>`: see `textRuns`. Deduplicated by prose key, because a run
  // and a paragraph inside it are the same words twice.
  const seen = new Set<string>();
  for (const p of textRuns(input.html, 30)) {
    if (p.at < headingEnd) continue;
    if (!unclaimed(p.text, input.claimed)) continue;
    const key = proseKey(p.text);
    if (seen.has(key)) continue;
    seen.add(key);
    blocks.push({ at: p.at, block: { kind: "p", text: p.text } });
  }
  for (const list of listBlocks(input.html)) {
    if (list.at < headingEnd) continue;
    const items = list.items.filter((v) => unclaimed(v, input.claimed));
    if (items.length < 2) continue;
    blocks.push({ at: list.at, block: { kind: "ul", items } });
  }

  blocks.sort((a, b) => a.at - b.at);
  const body = blocks.map((b) => b.block);
  // A lone subheading is not an article. Require something a reader reads.
  if (!body.some((b) => b.kind === "p" || b.kind === "ul")) return null;

  return {
    type: "rich-text",
    content: {
      type: "rich-text",
      ...(heading ? { heading: heading.text } : {}),
      blocks: body,
    },
  };
}

type Builder = (input: BandInput) => BandSection | null;

/** Builders by the type a proposal can name. */
const BY_TYPE: Partial<Record<SectionType, Builder>> = {
  statement,
  "cta-band": ctaBand,
  gallery,
  image,
  highlights: (input: BandInput) => pictureCards(input) ?? cardSection("highlights")(input),
  services: (input: BandInput) => cardSection("services")(input) ?? linkGrid(input),
  process: cardSection("process"),
  "rich-text": richText,
};

/**
 * Tried in order when no proposal names a type, most specific first.
 *
 * `rich-text` is last and always will be: it accepts almost anything, so any
 * builder placed after it would never run.
 */
const AUTO_ORDER: Builder[] = [
  statement,
  // Before `gallery` and `ctaBand` on purpose. A link grid usually carries a
  // picture per card, which `gallery` would take as a row of unlabelled photos,
  // and its first link would satisfy `ctaBand` - both of which throw away the
  // other eight destinations.
  linkGrid,
  // Before `gallery`: a row of picture cards is three or more photographs with
  // almost no prose, which is exactly what `gallery` accepts - and taking it
  // there threw the titles and the captions into a second band. (2643)
  pictureCards,
  gallery,
  image,
  cardSection("highlights"),
  ctaBand,
  richText,
];

/**
 * Build a section from a band the detector ladder passed over, or null when the
 * band holds nothing a reader would read.
 *
 * `prefer` is the type a model proposed for this band. It is tried FIRST and it
 * is only a preference: a proposal for a type whose builder finds nothing in the
 * band falls through to the deterministic order, so a wrong label costs a
 * better-shaped block and never the content.
 */
/**
 * The link grid alone, for a band another section already spoke for.
 *
 * A band that produced a gallery of its own card photos still holds the nine
 * destinations those cards linked to, and the residue pass keeps words rather
 * than links, so they were dropped. Exposed so the caller can offer a claimed
 * band its links as well - see the residue handling in `htmlToSections`. (2643)
 */
export function buildLinkGrid(input: BandInput): BandSection | null {
  return linkGrid(input);
}

export function buildFromBand(input: BandInput, prefer?: SectionType): BandSection | null {
  if (input.residualOnly) return richText(input);
  const preferred = prefer ? BY_TYPE[prefer] : undefined;
  if (preferred) {
    const built = preferred(input);
    if (built) return built;
  }
  for (const builder of AUTO_ORDER) {
    const built = builder(input);
    if (built) return built;
  }
  return null;
}
