// GENERATED by scripts/mirror-import.ts from HH-Studio/simple-site-builder:lib/import/designExtract.ts
// Do not edit. Run `bun scripts/mirror-import.ts --sync-from-app <appRoot>`.

// ---------------------------------------------------------------------------
// Design extraction for site import. Turns a source page's raw HTML + CSS into
// the design signals that make an imported site LOOK like its original: the
// brand colour (as a generated light+dark Surface pair), heading/body fonts,
// corner radius, and hero layout. Pure + dependency-light (regex + math), like
// htmlToSections.ts, so it runs inside a Convex action and is unit-testable.
//
// This does NOT clone CSS. It infers a small set of bounded, pre-validated
// tokens and lets our own renderer draw them - so the result stays safe and
// editable while reading as "my site" instead of a generic template.
// ---------------------------------------------------------------------------

import type { Palette, Surface } from "../../../lib/palettes";
import { safeDecodeURIComponent } from "../net/url";
import type { CustomTypeRole, ThemeTokens } from "../../../convex/model/theme";
import {
  extractMotion,
  type ExtractedParallax,
  type MotionNote,
} from "./motionExtract";

/** The type roles an import can actually MEASURE off a source page. The theme
 *  carries eight (see `TYPE_ROLE_KEYS`); `sm` and `eyebrow` have no reliable
 *  source element, so they stay on the preset scale rather than being guessed. */
export type MeasuredRole =
  | "display"
  | "h1"
  | "h2"
  | "h3"
  | "lead"
  | "body"
  | "quote";

/** One measured role. Identical shape to the theme's `customTypeRole` minus
 *  `family`, which is decided from the FONT roles, not from the element. */
export type MeasuredTypeRole = Omit<CustomTypeRole, "family">;

export type HeroLayout = "image-right" | "image-left" | "centered" | "overlay";

export type ExtractedDesign = {
  /** Generated custom palette (light + dark), ready to feed the renderer. */
  palette: Pick<Palette, "light" | "dark">;
  /** The source brand colour as OKLCH parts, for debugging / reporting.
   *  `detected` is false when the page declared no
   *  usable colour and we fell back to neutral - the import must not then tell
   *  the owner "we kept your colour", because there wasn't one to keep. */
  brand: { L: number; C: number; H: number; hex: string; detected: boolean };
  /** The site's second colour, when it had one. Reported so the import receipt
   *  can say "we kept your blue AND your coral" rather than leaving the owner to
   *  notice one of them missing. Absent on the great majority of sites. */
  accentHex?: string;
  fonts: { heading: string; body: string; display?: string };
  /** Present when the source page loads its typefaces from an Adobe Fonts kit.
   *  The import then registers the REAL families against that kit instead of
   *  snapping them to the nearest curated Google font. */
  adobeKitId?: string;
  radius: ThemeTokens["radius"];
  density: ThemeTokens["density"];
  heroLayout: HeroLayout;
  /** The source page's header treatment: floating over the first section, or
   *  sitting in the flow. Absent when the page's own header is in the flow,
   *  which is the default everywhere. */
  navOverlay?: ThemeTokens["navOverlay"];
  /** Measured per-role type + section rhythm, present only when the page was
   *  actually rendered and read (`applyComputedSample`). Static extraction can
   *  not produce these: a stylesheet does not say which rule won. */
  type?: Partial<Record<MeasuredRole, MeasuredTypeRole>>;
  layout?: ThemeTokens["customLayout"];
  /** The source page's own animation, read out of its scripts by PARSING them
   *  (never executing - see lib/import/motionExtract). Absent when the page had
   *  no motion we could read, in which case the site keeps whichever preset
   *  `motion` step the import chose. */
  motion?: ThemeTokens["customMotion"];
  /** Scroll-driven drifts the source page had, keyed by ITS selectors. Kept
   *  separate from `motion` because landing one on a rewritten section is a
   *  different decision; unmapped ones are reported, not dropped silently. */
  motionParallax?: ExtractedParallax[];
  /** What the page's motion had that we could not carry (see `MotionNote`). */
  motionNotes?: MotionNote[];
};

// ---- sRGB <-> OKLCH -------------------------------------------------------
// Standard sRGB -> linear -> OKLab -> OKLCH (Björn Ottosson). Kept inline so
// import has zero colour-library dependencies.

type RGB = { r: number; g: number; b: number }; // 0..255

function srgbToLinear(c: number): number {
  const x = c / 255;
  return x <= 0.04045 ? x / 12.92 : Math.pow((x + 0.055) / 1.055, 2.4);
}

export function rgbToOklch({ r, g, b }: RGB): { L: number; C: number; H: number } {
  const lr = srgbToLinear(r);
  const lg = srgbToLinear(g);
  const lb = srgbToLinear(b);
  const l = 0.4122214708 * lr + 0.5363325363 * lg + 0.0514459929 * lb;
  const m = 0.2119034982 * lr + 0.6806995451 * lg + 0.1073969566 * lb;
  const s = 0.0883024619 * lr + 0.2817188376 * lg + 0.6299787005 * lb;
  const l_ = Math.cbrt(l);
  const m_ = Math.cbrt(m);
  const s_ = Math.cbrt(s);
  const L = 0.2104542553 * l_ + 0.793617785 * m_ - 0.0040720468 * s_;
  const a = 1.9779984951 * l_ - 2.428592205 * m_ + 0.4505937099 * s_;
  const bb = 0.0259040371 * l_ + 0.7827717662 * m_ - 0.808675766 * s_;
  const C = Math.sqrt(a * a + bb * bb);
  let H = (Math.atan2(bb, a) * 180) / Math.PI;
  if (H < 0) H += 360;
  return { L, C, H };
}

function linearToSrgb(c: number): number {
  const v = c <= 0.0031308 ? 12.92 * c : 1.055 * Math.pow(c, 1 / 2.4) - 0.055;
  return Math.max(0, Math.min(255, Math.round(v * 255)));
}

/** OKLCH -> sRGB (inverse of rgbToOklch). Used to score brand colours that a
 *  Tailwind/shadcn site declares as `oklch()` custom properties. */
function oklchToRgb(L: number, C: number, H: number): RGB {
  const hr = (H * Math.PI) / 180;
  const a = Math.cos(hr) * C;
  const b = Math.sin(hr) * C;
  const l_ = L + 0.3963377774 * a + 0.2158037573 * b;
  const m_ = L - 0.1055613458 * a - 0.0638541728 * b;
  const s_ = L - 0.0894841775 * a - 1.291485548 * b;
  const l = l_ ** 3;
  const m = m_ ** 3;
  const s = s_ ** 3;
  const lr = 4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s;
  const lg = -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s;
  const lb = -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s;
  return { r: linearToSrgb(lr), g: linearToSrgb(lg), b: linearToSrgb(lb) };
}

/** HSL (h in deg, s/l in 0..1) -> sRGB. Tailwind stores brand tokens as bare
 *  `H S% L%` triplets and shadcn uses `hsl(var(--x))`. */
function hslToRgb(h: number, s: number, l: number): RGB {
  const c = (1 - Math.abs(2 * l - 1)) * s;
  const hp = ((h % 360) + 360) % 360 / 60;
  const x = c * (1 - Math.abs((hp % 2) - 1));
  let r = 0, g = 0, b = 0;
  if (hp < 1) [r, g, b] = [c, x, 0];
  else if (hp < 2) [r, g, b] = [x, c, 0];
  else if (hp < 3) [r, g, b] = [0, c, x];
  else if (hp < 4) [r, g, b] = [0, x, c];
  else if (hp < 5) [r, g, b] = [x, 0, c];
  else [r, g, b] = [c, 0, x];
  const m = l - c / 2;
  return {
    r: Math.round((r + m) * 255),
    g: Math.round((g + m) * 255),
    b: Math.round((b + m) * 255),
  };
}

const rgbToHex = ({ r, g, b }: RGB) =>
  "#" + [r, g, b].map((v) => Math.max(0, Math.min(255, Math.round(v))).toString(16).padStart(2, "0")).join("");

const round = (n: number, d = 3) => Number(n.toFixed(d));
const oklch = (L: number, C: number, H: number) =>
  `oklch(${round(L)} ${round(C)} ${round(H, 1)})`;

// ---- colour parsing -------------------------------------------------------

/** `#rgb` / `#rrggbb` -> RGB, or null. Exported so a caller that lets the owner
 *  pick a brand colour (the post-import refine panel) can run it through the
 *  SAME palette generator the import used, instead of inventing a second one. */
export function parseHexColor(hex: string): RGB | null {
  return parseHex(hex);
}

/** Any colour a surface token can hold -> RGB. A surface is either measured
 *  (hex, straight off the rendered page) or generated (`oklch(...)`), and a
 *  readability check has to be able to read BOTH - checking only the hex half
 *  would silently pass every generated palette. Alpha forms
 *  ("oklch(0 0 0 / 5%)") return null: they have no standalone colour to score. */
export function parseSurfaceColor(value: string): RGB | null {
  const raw = value.trim();
  if (raw.startsWith("#")) return parseHex(raw);
  const ok = raw.match(/^oklch\(\s*([\d.]+%?)\s+([\d.]+)\s+([\d.]+)\s*\)$/i);
  if (ok) {
    const L = ok[1].endsWith("%") ? parseFloat(ok[1]) / 100 : parseFloat(ok[1]);
    const C = parseFloat(ok[2]);
    const H = parseFloat(ok[3]);
    if ([L, C, H].some(Number.isNaN)) return null;
    return oklchToRgb(L, C, H);
  }
  const rgb = raw.match(/^rgba?\(([^)]+)\)$/i);
  if (rgb) {
    const p = rgb[1].split(/[\s,/]+/).filter(Boolean).map((n) => parseFloat(n));
    if (p.length >= 3 && p.slice(0, 3).every((n) => !Number.isNaN(n))) {
      return { r: p[0], g: p[1], b: p[2] };
    }
  }
  return null;
}

/** Build an `oklch()` token from RGB. Lets a readability fix nudge a measured
 *  colour along ONE axis (lightness) without changing its hue or saturation -
 *  the owner keeps their grey, it just stops being too pale to read. */
export function rgbToOklchString(rgb: RGB): string {
  const { L, C, H } = rgbToOklch(rgb);
  return oklch(L, C, H);
}

export function oklchStringFrom(L: number, C: number, H: number): string {
  return oklch(L, C, H);
}

export function oklchToRgbParts(L: number, C: number, H: number): RGB {
  return oklchToRgb(L, C, H);
}

export type { RGB };

function parseHex(hex: string): RGB | null {
  let h = hex.replace("#", "").trim();
  if (h.length === 3) h = h.split("").map((c) => c + c).join("");
  if (h.length !== 6) return null;
  const n = parseInt(h, 16);
  if (Number.isNaN(n)) return null;
  return { r: (n >> 16) & 255, g: (n >> 8) & 255, b: n & 255 };
}

type ColorHit = { rgb: RGB; hex: string; weight: number };

/** Pull every colour literal from CSS with a context weight - colours used on
 *  buttons / links / primary tokens score higher than incidental ones. When
 *  several stylesheets are given, later ones (the site's own CSS, loaded after
 *  framework resets like normalize/webflow) are weighted higher, so a stock
 *  framework accent never out-votes the real brand colour. */
function collectColors(cssSources: string | string[]): ColorHit[] {
  const sheets = Array.isArray(cssSources) ? cssSources : [cssSources];
  const hits = new Map<string, ColorHit>();
  const add = (rgb: RGB, hex: string, weight: number) => {
    const key = hex.toLowerCase();
    const prev = hits.get(key);
    if (prev) prev.weight += weight;
    else hits.set(key, { rgb, hex: key, weight });
  };
  // Context bonus: a colour declared in a rule that mentions these keywords is
  // more likely to be the brand accent.
  const CONTEXT = /(button|btn|\.w-button|primary|--[\w-]*primary|link|\ba\b|cta|accent|brand|nav|badge)/i;

  sheets.forEach((css, i) => {
    // Recency weight: last sheet (site CSS) counts most.
    const originWeight = 1 + i * 2;
    const declRe = /([^{}]*)\{([^{}]*)\}/g;
    let m: RegExpExecArray | null;
    while ((m = declRe.exec(css))) {
      const selector = m[1] || "";
      const body = m[2] || "";
      const ctx = CONTEXT.test(selector) || CONTEXT.test(body) ? 3 : 0;
      const isText = /(^|[^-])color\s*:/.test(body) ? 1 : 0;
      const isBg = /background(-color)?\s*:/.test(body) ? 1 : 0;
      const base = (1 + isText + isBg + ctx) * originWeight;
      // Strong signal: a colour assigned to a CSS custom property (`--brand:...`)
      // is almost always a deliberate brand token, so weight those heavily. This
      // covers hex, and the bare-number token forms Tailwind/shadcn use:
      //   --primary: 222.2 47.4% 11.2%   (HSL triplet)
      //   --primary: oklch(0.52 0.13 245)
      const varHexes = new Set<string>();
      const VAR = base * 6;
      for (const vm of body.matchAll(/--[\w-]+\s*:\s*([^;]+)/g)) {
        const val = vm[1].trim();
        const hexM = val.match(/^#[0-9a-fA-F]{3,6}\b/);
        if (hexM) { varHexes.add(hexM[0].toLowerCase()); continue; }
        // bare HSL triplet: "222.2 47.4% 11.2%"
        const hsl = val.match(/^(-?[\d.]+)\s+(-?[\d.]+)%\s+(-?[\d.]+)%/);
        if (hsl) {
          const rgb = hslToRgb(parseFloat(hsl[1]), parseFloat(hsl[2]) / 100, parseFloat(hsl[3]) / 100);
          add(rgb, rgbToHex(rgb), VAR);
          continue;
        }
        // bare OKLCH triplet: "0.52 0.13 245" (L in 0..1, then C, then H)
        const okt = val.match(/^(0?\.\d+|[01](?:\.\d+)?)\s+([\d.]+)\s+([\d.]+)/);
        if (okt && parseFloat(okt[1]) <= 1 && parseFloat(okt[2]) <= 0.5) {
          const rgb = oklchToRgb(parseFloat(okt[1]), parseFloat(okt[2]), parseFloat(okt[3]));
          add(rgb, rgbToHex(rgb), VAR);
        }
      }
      for (const hx of body.match(/#[0-9a-fA-F]{3,6}\b/g) || []) {
        const rgb = parseHex(hx);
        if (rgb) add(rgb, hx, varHexes.has(hx.toLowerCase()) ? VAR : base);
      }
      for (const rm of body.match(/rgba?\(([^)]+)\)/g) || []) {
        const parts = rm.replace(/rgba?\(|\)/g, "").split(/[,\s/]+/).map((s) => parseFloat(s));
        if (parts.length >= 3 && parts.slice(0, 3).every((n) => !Number.isNaN(n))) {
          const rgb = { r: parts[0], g: parts[1], b: parts[2] };
          add(rgb, rgbToHex(rgb), base);
        }
      }
      for (const hm of body.matchAll(/hsla?\(([^)]+)\)/g)) {
        const p = hm[1].split(/[,\s/]+/).filter(Boolean);
        const h = parseFloat(p[0]), s = parseFloat(p[1]), l = parseFloat(p[2]);
        if (![h, s, l].some(Number.isNaN)) {
          const rgb = hslToRgb(h, s / 100, l / 100);
          add(rgb, rgbToHex(rgb), base);
        }
      }
      for (const om of body.matchAll(/oklch\(([^)]+)\)/g)) {
        const p = om[1].split(/[,\s/]+/).filter(Boolean);
        let L = parseFloat(p[0]);
        if (p[0].endsWith("%")) L = parseFloat(p[0]) / 100;
        const C = parseFloat(p[1]), H = parseFloat(p[2]);
        if (![L, C, H].some(Number.isNaN) && L <= 1) {
          const rgb = oklchToRgb(L, C, H);
          add(rgb, rgbToHex(rgb), base);
        }
      }
    }
  });
  return [...hits.values()];
}

// Stock accent colours shipped by site builders / CSS frameworks. They flood a
// framework stylesheet by frequency but are rarely the real brand, so they only
// win if nothing else saturated exists.
const FRAMEWORK_DEFAULTS = new Set([
  "#3898ec", // Webflow default link/button blue
  "#007bff", // Bootstrap 4 primary
  "#0d6efd", // Bootstrap 5 primary
  "#1a73e8", // Google Material default
]);

/** Choose the brand accent: a saturated, mid-lightness colour that is used
 *  prominently. Neutrals (grey/near-white/near-black) are excluded, and stock
 *  framework accents are demoted below any real brand colour. */
export function pickBrandColor(css: string | string[]): { rgb: RGB; hex: string } | null {
  return rankBrandColors(css)[0] ?? null;
}

/** How far apart two hues must be before the second one is a DIFFERENT colour
 *  rather than a shade of the first. 40 degrees is about the point where a
 *  person stops calling both "the blue one" — a navy and a royal blue sit well
 *  inside it, a blue and a teal sit on the edge, a blue and a coral do not. */
const SECOND_HUE_MIN_DELTA = 40;

/** A second colour has to be genuinely used, not a stray. Below this share of
 *  the leader's score it is one designer's one-off border and promoting it to a
 *  site-wide accent would be louder than the site is. */
const SECOND_MIN_SCORE_SHARE = 0.15;

/** Circular hue distance in degrees. */
function hueDelta(a: number, b: number): number {
  const d = Math.abs(a - b) % 360;
  return d > 180 ? 360 - d : d;
}

/**
 * The page's brand colours, best first.
 *
 * Same scoring `pickBrandColor` always used; it is exported as a list so a
 * SECOND accent can be found. Sites routinely carry two: a brand blue for the
 * furniture and a coral for the calls to action, and deriving all thirteen
 * surface tokens from one hue loses the coral entirely.
 */
export function rankBrandColors(
  css: string | string[],
): Array<{ rgb: RGB; hex: string; score: number }> {
  const scored: Array<{ rgb: RGB; hex: string; score: number }> = [];
  for (const hit of collectColors(css)) {
    const { L, C } = rgbToOklch(hit.rgb);
    if (C < 0.05) continue; // neutral
    if (L < 0.2 || L > 0.9) continue; // too dark / too light to be an accent
    let score = hit.weight * (0.5 + C); // frequency+context, biased by saturation
    if (FRAMEWORK_DEFAULTS.has(hit.hex)) score *= 0.01; // demote stock defaults
    scored.push({ rgb: hit.rgb, hex: hit.hex, score });
  }
  return scored.sort((a, b) => b.score - a.score);
}

/**
 * The site's SECOND colour, when it genuinely has one.
 *
 * Returns null far more often than not, and that is the point: most small
 * business sites have one colour, and inventing a second would put a hue on
 * their page that nobody chose. It has to clear three bars — a different hue
 * from the leader, a real share of its score, and enough chroma to read as a
 * colour at all.
 */
export function pickSecondAccent(
  css: string | string[],
): { rgb: RGB; hex: string } | null {
  const ranked = rankBrandColors(css);
  const leader = ranked[0];
  if (!leader) return null;
  const leadHue = rgbToOklch(leader.rgb).H;
  for (const candidate of ranked.slice(1)) {
    if (candidate.score < leader.score * SECOND_MIN_SCORE_SHARE) break;
    const { C, H } = rgbToOklch(candidate.rgb);
    if (C < 0.07) continue;
    if (hueDelta(H, leadHue) < SECOND_HUE_MIN_DELTA) continue;
    return { rgb: candidate.rgb, hex: candidate.hex };
  }
  return null;
}

// ---- surface generation ---------------------------------------------------

/** Build a light+dark Surface pair from a brand colour, following the authoring
 *  rules in lib/palettes.ts (hue-matched off-white bg, white cards, AA-legible
 *  foregrounds). */
/** WCAG relative luminance from gamma-encoded sRGB channels (0-255). */
export function srgbLuminance({ r, g, b }: RGB): number {
  const lin = (v: number) => {
    const x = v / 255;
    return x <= 0.03928 ? x / 12.92 : ((x + 0.055) / 1.055) ** 2.4;
  };
  return 0.2126 * lin(r) + 0.7152 * lin(g) + 0.0722 * lin(b);
}

/** WCAG contrast ratio, 1..21. Lives here rather than in `readability.ts`
 *  because `surfacesFromBrand` below needs it and readability already imports
 *  FROM this module — the other direction would be a cycle. `readability.ts`
 *  re-exports both so its own callers are unaffected. */
export function wcagContrast(a: RGB, b: RGB): number {
  const la = srgbLuminance(a);
  const lb = srgbLuminance(b);
  const [hi, lo] = la >= lb ? [la, lb] : [lb, la];
  return (hi + 0.05) / (lo + 0.05);
}

/** WCAG AA for normal text. A button label and the pricing card's "Popular"
 *  badge are both small text on the primary fill, so the fill is held to the
 *  normal-text bar rather than the large-text one. */
const AA_ON_FILL = 4.5;

/**
 * What the SEARCH below aims for, above the contract itself.
 *
 * A fill is scored by re-parsing the `oklch()` string we will emit, and
 * `oklchToRgb` clips each channel to 0-255. Roughly a fifth of fills at
 * `chroma <= 0.16` are outside the sRGB gamut, and a browser implementing CSS
 * Color 4 maps those by reducing CHROMA rather than clipping per channel — a
 * different colour, and a slightly different contrast. Sweeping the cube under
 * chroma-reduction mapping, a couple of hundred fills landed at 4.487-4.499:
 * passing our own arithmetic while rendering just under AA. The margin makes
 * both readings clear the bar, at the cost of a barely perceptible extra step
 * of darkening on the hues that need it. Found in independent review,
 * 2026-08-05.
 */
const AA_SEARCH_TARGET = AA_ON_FILL + 0.1;

/**
 * The fill lightness that carries `fgHex` at AA, starting from `startL` and
 * moving AWAY from the foreground.
 *
 * `surfacesFromBrand` derives `primary` and `primaryFg` from a single measured
 * hue — neither is a colour the source page chose — so a pair that fails AA is
 * OUR arithmetic being wrong, not the owner's design being overridden. That is
 * why this clamps at the source instead of being reported by
 * `reviewReadability` the way genuinely MEASURED colours are (backlog 0362).
 *
 * Only lightness moves; hue and chroma are untouched, so the brand still reads
 * as the brand. Returns `startL` unchanged when it already clears, and gives up
 * at the end of the range rather than looping — a fully saturated fill on its
 * own tint can be unsolvable, and a wrong answer is worse than an honest miss.
 */
function fillLForContrast(startL: number, chroma: number, hue: number, fg: RGB): number {
  // Scored through the EMITTED string, not the raw floats. `oklch()` rounds the
  // hue to one decimal, which moves the colour just enough to turn a computed
  // 4.50 into a shipped 4.45 — nine of 8192 sampled brands landed exactly there
  // when this searched on unrounded values.
  const at = (l: number) => {
    const rgb = parseSurfaceColor(oklch(l, chroma, hue));
    return rgb ? wcagContrast(rgb, fg) : 0;
  };
  if (at(startL) >= AA_SEARCH_TARGET) return startL;
  // Away from the foreground: a white label needs a darker fill, a near-black
  // label a lighter one.
  const darker = srgbLuminance(fg) > 0.5;
  for (let step = 1; step <= 100; step++) {
    const l = darker ? startL - step / 100 : startL + step / 100;
    if (l < 0 || l > 1) break;
    if (at(l) >= AA_SEARCH_TARGET) return Number(l.toFixed(3));
  }
  return startL;
}

export function surfacesFromBrand(
  rgb: RGB,
  /** The site's SECOND colour, when it has one (`pickSecondAccent`). Only the
   *  `accent` pair takes its hue; the primary fill, the paper, the ink and the
   *  borders all stay on the brand hue, so a site keeps one voice and gains a
   *  highlight rather than becoming two-tone.
   *
   *  Its LIGHTNESS and CHROMA are deliberately not taken from the source. The
   *  accent pair's contrast comes from the large lightness gap between the two
   *  tokens (0.94 against 0.35 on paper), which is what keeps it AA-safe on
   *  every hue; borrowing a source colour's own lightness would put that
   *  guarantee in the hands of whatever hex somebody happened to pick. */
  accentRgb?: RGB,
): Pick<Palette, "light" | "dark"> {
  const { L, C, H } = rgbToOklch(rgb);
  const chroma = Math.min(C, 0.16); // cap so fills never scream

  // Primary fill lightness + foreground, hue-aware (mirrors the authored
  // palettes in lib/palettes.ts): most hues keep a DEEP fill (L<=0.55) that
  // carries white text, exactly like `ocean`/`midnight`. Warm hues (yellow/
  // amber/lime) can't go deep without turning muddy, so they stay light and
  // take near-black text, like `amber`.
  // The accent pair's hue, which is the second colour when the site has one and
  // the brand hue otherwise. Everything else on both surfaces stays on `H`.
  const accentOklch = accentRgb ? rgbToOklch(accentRgb) : null;
  const accentH = accentOklch ? accentOklch.H : H;
  const accentChroma = accentOklch ? Math.min(accentOklch.C, 0.16) : chroma;

  const isWarmLight = H >= 40 && H <= 110 && L > 0.6;
  const startFillL = isWarmLight ? Math.min(L, 0.66) : Math.max(0.4, Math.min(L, 0.55));
  const primaryFgLight = isWarmLight ? oklch(0.2, 0.03, H) : oklch(0.99, 0, 0);
  // The hue rules above target AA and mostly hit it, but a deep green or teal
  // at L=0.55 lands around 4.3-4.5 against white — under the bar, and nothing
  // downstream checks this pair (`reviewReadability` covers ink and muted text,
  // never the fill). Every button label and the pricing "Popular" badge is
  // small text on this fill, so it is nudged until it clears (backlog 0362).
  const fillL = fillLForContrast(
    startFillL,
    chroma,
    H,
    isWarmLight ? oklchToRgbParts(0.2, 0.03, H) : oklchToRgbParts(0.99, 0, 0),
  );
  // Primary-as-text on white (eyebrows/links) must stay legible: warm light
  // fills get a darkened text variant; the fill itself is unchanged.
  const primaryText = isWarmLight ? oklch(0.5, chroma, H) : undefined;

  const light: Surface = {
    bg: oklch(0.992, 0.004, H),
    fg: oklch(0.22, 0.03, H),
    muted: oklch(0.965, 0.012, H),
    mutedFg: oklch(0.48, 0.03, H),
    primary: oklch(fillL, chroma, H),
    primaryFg: primaryFgLight,
    ...(primaryText ? { primaryText } : {}),
    accent: oklch(0.94, Math.min(accentChroma, 0.03), accentH),
    accentFg: oklch(0.35, Math.min(accentChroma, 0.09), accentH),
    border: oklch(0.92, 0.012, H),
    card: oklch(1, 0, 0),
    cardFg: oklch(0.22, 0.03, H),
    cardBorder: "oklch(0 0 0 / 5%)",
  };
  const dark: Surface = {
    bg: oklch(0.23, 0.04, H),
    fg: oklch(0.97, 0.012, H),
    muted: oklch(0.29, 0.04, H),
    mutedFg: oklch(0.78, 0.02, H),
    // Same clamp on the night surface: its fill is lighter and its label darker,
    // so the walk goes the other way on its own.
    primary: oklch(
      fillLForContrast(0.72, Math.min(chroma, 0.13), H, oklchToRgbParts(0.2, 0.04, H)),
      Math.min(chroma, 0.13),
      H,
    ),
    primaryFg: oklch(0.2, 0.04, H),
    accent: oklch(0.33, 0.05, accentH),
    accentFg: oklch(0.97, 0.012, accentH),
    border: "oklch(1 0 0 / 13%)",
    card: oklch(0.27, 0.04, H),
    cardFg: oklch(0.97, 0.012, H),
    cardBorder: "oklch(1 0 0 / 10%)",
  };
  return { light, dark };
}

// ---- font / radius / hero inference --------------------------------------

const GENERIC_FONTS = /^(inherit|sans-serif|serif|monospace|system-ui|ui-sans-serif|ui-serif|-apple-system|blinkmacsystemfont|"?arial"?|"?helvetica"?|"?helvetica neue"?|"?segoe ui"?|"?roboto"?|unset|initial|var\(.*\))$/i;

// Icon / utility fonts that are never the site's real typeface.
const ICON_FONTS = /^(webflow-icons|fontawesome|font\s?awesome|"?font awesome[^"]*"?|icomoon|material icons|material symbols[^"]*|glyphicons|ionicons|dashicons|feather)$/i;

/** The Adobe Fonts (Typekit) project id a page loads its typefaces from, if any.
 *
 *  This matters because `resolveFont` in htmlToSections snaps an unrecognised
 *  family to the nearest CURATED GOOGLE font, which is the only way to guarantee
 *  something loads - but it also means a site built on Adobe Fonts arrives in a
 *  typeface it has never used. With the kit id we can register the real family
 *  against the real kit instead. The kit stays the OWNER'S: Adobe locks a kit to
 *  its allowed domains, so the import has to tell them to add the new one
 *  (see the `adobe_fonts_kit` note the report carries), and until they do the
 *  page falls back through the font stack rather than breaking. */
export function extractAdobeKitId(html: string): string | undefined {
  // Both served forms — `use.typekit.net/<kit>.css` (the stylesheet link) and
  // `use.typekit.net/<kit>.js` (the loader script, which is what Typekit's own
  // embed code has shipped for years) — plus the older `use.typekit.com` host.
  // The `.js` form was missing until 2026-08-08, and the loose fallback below
  // then answered in its place with the FIRST quoted token within 200 chars of
  // the word "typekit" — which the URL itself contains. On the reference import
  // that was the next `font-family` value, so the owner was told to add their
  // domain to a kit named "calluna". `lib/import/importActions.ts` reads the
  // same two forms; keep the two patterns in step.
  const direct = html.match(/use\.typekit\.(?:net|com)\/([a-z0-9]{4,20})\.(?:js|css)/i);
  if (direct) return direct[1].toLowerCase();
  // The scripted loader (`Typekit.load({ kitId: "…" })` and the p.typekit.net
  // `k=<kit>` query form). Anchored on the KEY, never on proximity to the word
  // "Typekit" — a quoted string near a URL is not a kit id.
  const loader = html.match(/\bkit(?:Id|_id)\b["'\s:=]{1,6}["']([a-z0-9]{4,20})["']/i);
  if (loader) return loader[1].toLowerCase();
  const query = html.match(/p\.typekit\.net\/p\.css\?[^"'>]*\bk=([a-z0-9]{4,20})/i);
  return query ? query[1].toLowerCase() : undefined;
}

/** First real (non-generic) font family named on headings, then body. */
export function extractFonts(html: string, css: string): { heading: string; body: string } {
  const clean = (fam: string) =>
    fam
      .split(",")[0]
      .replace(/!important/gi, "")
      .trim()
      .replace(/^["']|["']$/g, "")
      .trim();
  const families: string[] = [];
  // Google Fonts / Typekit hints in <head>.
  for (const m of html.matchAll(/fonts\.googleapis\.com\/css2?\?family=([^&"'>]+)/gi)) {
    families.push(safeDecodeURIComponent(m[1].split(":")[0].replace(/\+/g, " ")));
  }
  for (const m of html.matchAll(/WebFont\.load[\s\S]*?families\s*:\s*\[([^\]]+)\]/gi)) {
    // Each family is a quoted string like "Open Sans:300,400,700" - the commas
    // after the colon are WEIGHTS, not extra families, so match quoted names
    // and drop the ":<weights>" suffix.
    for (const q of m[1].matchAll(/["']([^"']+)["']/g)) families.push(q[1].split(":")[0].trim());
  }
  // font-family declarations in CSS, in source order.
  const decls = [...css.matchAll(/font-family\s*:\s*([^;}]+)/gi)].map((m) => clean(m[1]));
  const real = [...families, ...decls].filter(
    (f) => f && !GENERIC_FONTS.test(f) && !ICON_FONTS.test(f),
  );
  const heading = real[0] || "";
  const body = real.find((f) => f !== heading) || heading || "";
  return { heading, body };
}

export function inferRadius(css: string): ThemeTokens["radius"] {
  // Read `border-radius` and the shadcn/Tailwind `--radius` token, in px OR rem
  // (rem * 16). Ignore pill/9999px and percentage rounding (avatars).
  const px: number[] = [];
  for (const m of css.matchAll(/(?:border-radius|--radius[\w-]*)\s*:\s*([\d.]+)(px|rem)/gi)) {
    const v = parseFloat(m[1]) * (m[2].toLowerCase() === "rem" ? 16 : 1);
    if (v > 0 && v < 100) px.push(v);
  }
  if (px.length === 0) return "sharp";
  const max = Math.max(...px);
  if (max >= 16) return "round";
  if (max >= 5) return "soft";
  return "sharp";
}

export function inferHeroLayout(html: string): HeroLayout {
  const head = html.slice(0, 12000).toLowerCase();
  if (/hero[^>]*(overlay|full-?bleed|bg-image)|section[^>]*hero[\s\S]{0,400}background-image/.test(head))
    return "overlay";
  // A hero with a side image: look for an <img> near the top inside a hero-ish block.
  const heroBlock = head.match(/<[^>]*(hero|banner|masthead)[\s\S]{0,1600}/);
  if (heroBlock) {
    const idx = heroBlock[0].search(/<img|background-image/);
    if (idx >= 0) {
      // crude left/right: image markup before the headline => left, else right.
      const beforeH = heroBlock[0].search(/<h1/);
      return beforeH === -1 || idx < beforeH ? "image-left" : "image-right";
    }
  }
  return "centered";
}

/** Is this CSS colour fully transparent?
 *
 *  Not just the keyword: Webflow writes a see-through header as a FOUR-digit
 *  hex whose last digit is the alpha, and the reference import's navbar is
 *  exactly that. Matching only `transparent` missed the one real page this was
 *  written for. Also covers the eight-digit form and a zero-alpha rgba/hsla. */
export function isTransparentColor(value: string): boolean {
  const v = value.trim().toLowerCase();
  if (v === "transparent" || v === "none") return true;
  const hex4 = /^#[0-9a-f]{3}([0-9a-f])$/.exec(v);
  if (hex4) return hex4[1] === "0";
  const hex8 = /^#[0-9a-f]{6}([0-9a-f]{2})$/.exec(v);
  if (hex8) return hex8[1] === "00";
  const fn = /^(?:rgba?|hsla?)\(([^)]*)\)$/.exec(v);
  if (fn) {
    const parts = fn[1]!.split(/[,/]/).map((p) => p.trim());
    if (parts.length === 4) return parseFloat(parts[3]!) === 0;
  }
  return false;
}

/** Does the source page's header FLOAT over its first section?
 *
 *  Read from the page's own CSS, because that is where it is decided: a header
 *  that is `position: absolute` or `fixed` with no background of its own is
 *  sitting on top of the hero, and its hero therefore starts at y=0. Ours is
 *  sticky and pushes the page down by its own height, which was ~65px at every
 *  width on the reference import - the largest single layout difference left.
 *
 *  Conservative on purpose: a header with a real background colour is NOT an
 *  overlay however it is positioned, and no match means `none`, which is what
 *  every site renders today. */
export function inferNavOverlay(
  css: string,
): NonNullable<ThemeTokens["navOverlay"]> | undefined {
  // Rules whose selector names a header/nav/navbar element or class.
  // No word boundary: Webflow names the bar `.navbar_component`, and `\bnavbar\b`
  // does not match that (an underscore is a word character). The other two
  // conditions - positioned out of the flow AND see-through - carry the weight,
  // so a loose selector match cannot produce a false positive on its own.
  const rules = css.matchAll(
    /(^|[},])\s*([^{}]*(?:header|nav)[^{}]*)\{([^{}]*)\}/gi,
  );
  for (const rule of rules) {
    const body = rule[3]!.toLowerCase();
    if (!/position\s*:\s*(absolute|fixed)/.test(body)) continue;
    // A gradient IS the overlay treatment most of these pages ship.
    if (/background(-image)?\s*:\s*[^;]*gradient/.test(body)) return "gradient";
    const bg = /background(?:-color)?\s*:\s*([^;}]+)/.exec(body)?.[1]?.trim();
    // No background at all is an overlay by omission.
    if (bg === undefined) return "transparent";
    if (isTransparentColor(bg)) return "transparent";
  }
  return undefined;
}

export function inferDensity(css: string): ThemeTokens["density"] {
  const pads = [...css.matchAll(/padding(-top|-bottom)?\s*:\s*([\d.]+)rem/gi)].map((m) =>
    parseFloat(m[2]),
  );
  const big = pads.filter((v) => v >= 4).length;
  if (big >= 3) return "spacious";
  if (pads.filter((v) => v >= 2).length >= 3) return "comfortable";
  return "compact";
}

// ---- entry point ----------------------------------------------------------

/**
 * @param html   Source page HTML.
 * @param css    One CSS string, or an ORDERED list of stylesheets. Order the
 *               list as the page loads them (framework/reset first, the site's
 *               own stylesheet last) so the brand colour beats stock defaults.
 */
/** Pull CSS the page carries inside the HTML itself: <style> blocks (Next.js /
 *  Tailwind inline their critical CSS + :root token vars here) and style=""
 *  attributes (wrapped as a rule so the declaration parser sees them). */
export function harvestInlineCss(html: string): string {
  const styleBlocks = [...html.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/gi)].map((m) => m[1]);
  const inlineAttrs = [...html.matchAll(/\sstyle\s*=\s*"([^"]+)"/gi)].map((m) => `.inline{${m[1]}}`);
  return [...styleBlocks, ...inlineAttrs].join("\n");
}

/**
 * The absolute URLs of the page's linked stylesheets, in document order.
 *
 * Everything below can already read a brand colour, typeface, radius and density
 * out of CSS — `collectColors` even weights later sheets over earlier ones so
 * the site's own stylesheet beats a framework reset. But the whole-site crawl
 * built its `ImportPageInput` with **no `css` field at all**, so all of that ran
 * on `harvestInlineCss` alone: `<style>` blocks and `style=""` attributes. A
 * site that links a stylesheet — i.e. nearly every site not built by Next.js —
 * had its design read from almost nothing, and `designSource` stayed `"static"`
 * with a neutral fallback palette.
 *
 * Ordered as the document loads them, because that order is load-bearing for
 * `pickBrandColor`. Bounded by `max` since each one is a network fetch, and
 * capped at same-scheme http(s) — a `data:` or `blob:` href has nothing to get.
 */
export function linkedStylesheetHrefs(
  html: string,
  baseUrl: string,
  max = 6,
): string[] {
  const out: string[] = [];
  const seen = new Set<string>();
  for (const tag of html.matchAll(/<link\b[^>]*>/gi)) {
    const el = tag[0];
    // `rel` may carry several tokens ("preload stylesheet"), and attribute order
    // is not guaranteed, so match the attribute rather than the tag shape.
    if (!/\brel=["']?[^"'>]*\bstylesheet\b/i.test(el)) continue;
    const href = el.match(/\bhref=["']([^"']+)["']/i)?.[1];
    if (!href) continue;
    let abs: string;
    try {
      abs = new URL(href, baseUrl).toString();
    } catch {
      continue;
    }
    if (!/^https?:/i.test(abs)) continue;
    if (seen.has(abs)) continue;
    seen.add(abs);
    out.push(abs);
    if (out.length >= max) break;
  }
  return out;
}

/** Vendor bundles: big, minified, and never where a page's own animation
 *  lives. Fetching them would spend the import's budget on jQuery. */
const VENDOR_SCRIPT =
  /(jquery|gsap|scrolltrigger|split-type|lenis|swiper|lottie|three|bootstrap|popper|analytics|gtag|gtm|hotjar|clarity|recaptcha|gsap|aos)[.\-/]/i;

/**
 * Script FILES worth reading for a page's animation. Webflow keeps its whole
 * interaction payload (`Webflow.require("ix2").init({...})`) in `js/webflow.js`,
 * so a motion read from the HTML alone sees the GSAP half of an export and none
 * of the Webflow half.
 *
 * Same-origin only and vendor bundles skipped: the page's own script is the only
 * one that can hold its own interactions, and every fetch is a network round
 * trip inside a Convex action.
 */
export function linkedScriptSrcs(
  html: string,
  baseUrl: string,
  max = 2,
): string[] {
  let origin: string;
  try {
    origin = new URL(baseUrl).origin;
  } catch {
    return [];
  }
  const out: string[] = [];
  const seen = new Set<string>();
  for (const tag of html.matchAll(/<script\b[^>]*\bsrc=["']([^"']+)["'][^>]*>/gi)) {
    const src = tag[1]!;
    let abs: string;
    try {
      abs = new URL(src, baseUrl).toString();
    } catch {
      continue;
    }
    if (!abs.startsWith(origin + "/")) continue;
    if (VENDOR_SCRIPT.test(abs)) continue;
    if (seen.has(abs)) continue;
    seen.add(abs);
    out.push(abs);
    if (out.length >= max) break;
  }
  return out;
}

/**
 * A design snapshot read from the RENDERED page via `getComputedStyle` (a
 * headless browser / crawler-with-render step). Computed styles resolve CSS
 * variables, cascade and framework defaults, so they are far more accurate than
 * parsing source CSS - they report the colour/fonts a visitor actually sees.
 * Every field is optional; only the ones present override the static guess.
 */
export type ComputedSample = {
  /** Brand accent actually painted on buttons/links (e.g. "#112032"). */
  brandHex?: string;
  headingFont?: string;
  bodyFont?: string;
  /** Family used on SECTION headings. When it differs from `headingFont` (the
   *  h1's family) the source uses three typefaces, and the import promotes the
   *  h1 family to the third `display` role instead of dropping one. */
  sectionHeadingFont?: string;
  /** True when the hero renders a background image (=> overlay layout). */
  heroBackgroundImage?: boolean;
  /** Per-role measured type. */
  type?: Partial<Record<MeasuredRole, MeasuredTypeRole>>;
  /** Measured section padding and container widths, as CSS lengths. */
  layout?: ThemeTokens["customLayout"];
  /** Page colours as painted (hex). */
  colors?: { bg?: string; fg?: string; mutedFg?: string; muted?: string };
  /** Geometry measured per BAND, keyed by that band's own heading. Site-level
   *  `layout` above is one median for the whole page; this is what lets a hero
   *  breathing at 200px sit over a band at 96px, which is what the source did.
   *  Lands on `section.layout.measured`, never on the theme. */
  sections?: MeasuredSectionSample[];
};

/** One band of a source page as measured, plus the key it is matched by. */
export type MeasuredSectionSample = {
  /** The band's heading, whitespace-collapsed and lower-cased. */
  key: string;
  paddingTop?: string;
  paddingBottom?: string;
  maxWidth?: string;
  gap?: string;
  align?: "center" | "end";
  /** How many columns the band's repeated region actually renders in, measured
   *  from the painted page. 2-6; anything outside that is not a card grid.
   *
   *  This is the first measurement that changes WHICH VARIANT a section gets
   *  rather than how it is spaced. The importer's own guess reads item COUNT
   *  ("four services must be a three-column grid"), which is wrong exactly when
   *  the source made a deliberate choice - four services in two columns is a
   *  composition, and a count cannot see it. */
  columns?: number;
};

/** Overlay measured page colours onto a generated surface pair.
 *
 *  `surfacesFromBrand` derives thirteen tokens from ONE hue, which is the right
 *  fallback but is never the source page's actual paper and ink: a warm-grey
 *  body colour becomes a hue-tinted derivative, and a pure-white page becomes a
 *  faintly tinted off-white. Only the light surface is overlaid - the dark one
 *  is our own night mode, which the source page did not have.
 *
 *  Exported because `lib/import/measuredTheme.ts` overlays the same measured
 *  colours onto a BUILT-IN palette when a bundle's source page had readable
 *  paper and ink but no resolvable brand (backlog 1789). Two overlays with
 *  different card-lift rules would be two answers to one question. */
export function applyMeasuredColors(
  palette: Pick<Palette, "light" | "dark">,
  colors: NonNullable<ComputedSample["colors"]>,
): Pick<Palette, "light" | "dark"> {
  const light: Surface = { ...palette.light };
  if (colors.bg) light.bg = colors.bg;
  if (colors.fg) {
    light.fg = colors.fg;
    light.cardFg = colors.fg;
  }
  if (colors.mutedFg) light.mutedFg = colors.mutedFg;
  if (colors.muted) light.muted = colors.muted;

  // Cards sit ON the page. Run AFTER muted is overlaid so a white-on-white
  // lift can use the measured muted plate (oklch(1 0 0) vs #ffffff must
  // compare as colours, not strings — string-only equality was a no-op).
  if (colors.bg) {
    const cardRgb = parseSurfaceColor(light.card);
    const bgRgb = parseSurfaceColor(colors.bg);
    const same =
      light.card.toLowerCase() === colors.bg.toLowerCase() ||
      (cardRgb !== null &&
        bgRgb !== null &&
        cardRgb.r === bgRgb.r &&
        cardRgb.g === bgRgb.g &&
        cardRgb.b === bgRgb.b);
    if (same) {
      const mutedRgb = parseSurfaceColor(light.muted);
      const mutedMatchesBg =
        mutedRgb !== null &&
        bgRgb !== null &&
        mutedRgb.r === bgRgb.r &&
        mutedRgb.g === bgRgb.g &&
        mutedRgb.b === bgRgb.b;
      if (!mutedMatchesBg) light.card = light.muted;
    }
  }
  return { light, dark: palette.dark };
}

/**
 * Merge a rendered-page computed sample over a static `ExtractedDesign`. This is
 * the accuracy upgrade: the brand colour becomes the *painted* colour, fonts
 * become the *resolved* families, and a background-image hero becomes an
 * overlay. Pure, so it is unit-testable without a browser.
 */
export function applyComputedSample(design: ExtractedDesign, sample: ComputedSample): ExtractedDesign {
  const next: ExtractedDesign = { ...design, fonts: { ...design.fonts } };
  const rgb = sample.brandHex ? parseHex(sample.brandHex) : null;
  if (rgb) {
    const { L, C, H } = rgbToOklch(rgb);
    next.palette = surfacesFromBrand(rgb);
    // A measured colour off the rendered page is by definition detected.
    next.brand = {
      L: round(L),
      C: round(C),
      H: round(H, 1),
      hex: sample.brandHex!.toLowerCase(),
      detected: true,
    };
  }
  if (sample.headingFont && !GENERIC_FONTS.test(sample.headingFont) && !ICON_FONTS.test(sample.headingFont))
    next.fonts.heading = sample.headingFont;
  if (sample.bodyFont && !GENERIC_FONTS.test(sample.bodyFont) && !ICON_FONTS.test(sample.bodyFont))
    next.fonts.body = sample.bodyFont;
  // Three typefaces. The h1's family becomes the DISPLAY role and the section
  // headings keep `heading`, because that is the role most of the page's
  // headings are set in - promoting the rarer face would misreport the site.
  const usable = (f: string | undefined): f is string =>
    !!f && !GENERIC_FONTS.test(f) && !ICON_FONTS.test(f);
  if (
    usable(sample.sectionHeadingFont) &&
    usable(sample.headingFont) &&
    sample.sectionHeadingFont.toLowerCase() !== sample.headingFont.toLowerCase()
  ) {
    next.fonts.display = sample.headingFont;
    next.fonts.heading = sample.sectionHeadingFont;
  }
  if (sample.type && Object.keys(sample.type).length > 0) {
    next.type = { ...sample.type };
    // A role's own ink is only worth carrying when it DIFFERS from the page's
    // ink, and only on the hero. Pinning every role to a measured colour would
    // freeze the text on a DARK band to the light page's ink - the tone system
    // exists precisely so a band can flip both - and carrying a colour equal to
    // the body ink adds a declaration that changes nothing.
    const pageInk = sample.colors?.fg?.trim().toLowerCase();
    for (const role of Object.keys(next.type) as MeasuredRole[]) {
      const measured = next.type[role];
      if (!measured?.color) continue;
      const same = pageInk && measured.color.trim().toLowerCase() === pageInk;
      if (role !== "display" || same) {
        const rest = { ...measured };
        delete rest.color;
        next.type[role] = rest;
      }
    }
  }
  if (sample.layout && Object.keys(sample.layout).length > 0) next.layout = { ...sample.layout };
  if (sample.colors && Object.keys(sample.colors).length > 0) {
    next.palette = applyMeasuredColors(next.palette, sample.colors);
  }
  if (sample.heroBackgroundImage) next.heroLayout = "overlay";
  return next;
}

export function extractDesign(
  html: string,
  css: string | string[] = [],
  /** Script FILES the caller fetched. Webflow keeps its interaction payload in
   *  `js/webflow.js`, so a motion read from the HTML alone sees only half a
   *  Webflow page. Empty is fine: inline scripts are read either way. */
  scripts: string[] = [],
): ExtractedDesign {
  const motion = extractMotion(html, scripts);
  const inline = harvestInlineCss(html);
  // Order matters: framework/linked CSS first, then the page's own inline CSS
  // (highest recency weight - it holds the deliberate brand tokens).
  const sheets = [...(Array.isArray(css) ? css : [css]), inline].filter(Boolean);
  const cssJoined = sheets.join("\n");
  const brand = pickBrandColor(sheets);
  const rgb = brand?.rgb ?? { r: 39, g: 39, b: 42 }; // fallback: neutral slate-ish
  const { L, C, H } = rgbToOklch(rgb);
  // A site's SECOND colour, when it genuinely has one. Only the accent pair
  // takes its hue - see `surfacesFromBrand`. Null on most sites, which is the
  // honest answer: inventing a second colour would put a hue on somebody's page
  // that nobody chose.
  const second = brand ? pickSecondAccent(sheets) : null;
  return {
    palette: surfacesFromBrand(rgb, second?.rgb),
    ...(second ? { accentHex: second.hex } : {}),
    brand: {
      L: round(L),
      C: round(C),
      H: round(H, 1),
      hex: brand?.hex ?? "#27272a",
      detected: !!brand,
    },
    fonts: extractFonts(html, cssJoined),
    ...(extractAdobeKitId(html) ? { adobeKitId: extractAdobeKitId(html) } : {}),
    radius: inferRadius(cssJoined),
    density: inferDensity(cssJoined),
    heroLayout: inferHeroLayout(html),
    ...(inferNavOverlay(cssJoined) ? { navOverlay: inferNavOverlay(cssJoined) } : {}),
    ...(motion.motion ? { motion: motion.motion } : {}),
    ...(motion.parallax.length > 0 ? { motionParallax: motion.parallax } : {}),
    ...(motion.notes.length > 0 ? { motionNotes: motion.notes } : {}),
  };
}
