// GENERATED by scripts/mirror-import.ts from HH-Studio/simple-site-builder:lib/import/importActions.ts
// Do not edit. Run `bun scripts/mirror-import.ts --sync-from-app <appRoot>`.

// ---------------------------------------------------------------------------
// "What you still need to do" after an import.
//
// The import summary (importSummary.ts) tells an owner what we KEPT, REBUILT
// and DROPPED. That is a receipt, and a receipt is not a to-do list: a source
// site that loaded an Adobe Fonts kit imports "successfully" and then renders
// in a fallback face until somebody adds the new domain to that kit - and
// nothing in the product ever said so.
//
// This module reads the SOURCE page for signals we can honestly act on, and
// turns them into a small, ordered list of concrete follow-ups. Rules:
//   - every action names the thing to do, not the thing that happened
//   - never invent work: a signal we did not actually see produces no action
//   - "blocker" is reserved for things that stop a publish; everything an owner
//     can ship without is "action" or "info"
//
// Pure + presentation-agnostic (same reason as importSummary): the preview
// panel, the post-import screen and the import report all render this list.
// ---------------------------------------------------------------------------

import {
  detectCommerce,
  STORE_PROVIDER_LABELS,
  type CommerceDetection,
} from "../scrape/detectCommerce";
import type { MeasureSkipReason } from "./measureSource";
import type { MotionNote } from "./motionExtract";

export type ImportActionCode =
  | "adobe_fonts_kit"
  | "placeholder_text"
  | "store_detected"
  | "assets_skipped"
  | "embeds_dropped"
  | "motion_rebuilt"
  | "contact_missing"
  | "design_not_measured"
  | "source_barely_readable";

export type ImportActionSeverity = "blocker" | "action" | "info";

export type ImportAction = {
  code: ImportActionCode;
  severity: ImportActionSeverity;
  /** One line, imperative: what the owner should do. */
  title: string;
  /** One or two sentences: why, and what happens if they don't. */
  detail: string;
  /** Where it gets done, in the owner's words. Absent when it is off-product
   *  (an Adobe Fonts account) or purely informational. */
  where?: string;
};

/** How readable the served document was. */
export type SourceContentQuality = {
  /** Words of visible text in the HTML as served (scripts/styles removed). */
  words: number;
  /** True when there is far too little text for this to be a real page. */
  thin: boolean;
  /** The client-side builder or framework whose empty shell we recognised.
   *  Absent when the page is thin for some other reason - we name the tool only
   *  when we are actually sure which one it is. */
  shell?: string;
};

/** Client-rendered shells, most specific first. Each entry is [label, marker].
 *  The label is shown to the owner, so it names the product they know. */
const SHELL_SIGNALS: Array<[string, RegExp]> = [
  ["Wix", /\bwix-|static\.wixstatic\.com|_wixCssStates\b/i],
  ["Squarespace", /squarespace\.com|static1\.squarespace|Static\.SQUARESPACE_CONTEXT/i],
  ["Next.js", /id=["']__next["']|__NEXT_DATA__/i],
  ["Nuxt", /__NUXT__|id=["']__nuxt["']/i],
  ["Gatsby", /id=["']___gatsby["']/i],
  ["Angular", /\bng-version=|<app-root\b/i],
  ["Vue", /id=["']app["'][^>]*>\s*<\/div>|data-v-app/i],
  ["React", /data-reactroot|id=["']root["'][^>]*>\s*<\/div>/i],
];

/** Visible words in the document as served. Scripts, styles, SVG and comments
 *  are removed first: a React bundle is a megabyte of "text" that no visitor
 *  ever reads, and counting it would hide exactly the pages this is for. */
export function readableWordCount(html: string): number {
  const text = html
    .replace(/<!--[\s\S]*?-->/g, " ")
    .replace(/<(script|style|noscript|svg|template)\b[\s\S]*?<\/\1>/gi, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/&[a-z]+;|&#\d+;/gi, " ")
    .replace(/\s+/g, " ")
    .trim();
  return text ? text.split(" ").filter((w) => w.length > 1).length : 0;
}

/** Below this a page cannot be a real small-business page. A genuinely short
 *  contact page still clears it comfortably; a framework shell does not come
 *  close. Deliberately generous - a false "your site is empty" is worse than a
 *  missed one. */
export const THIN_WORDS = 60;

export function assessSourceContent(html: string): SourceContentQuality {
  const words = readableWordCount(html);
  const thin = words < THIN_WORDS;
  // Only name a shell when the page is ALSO thin. A server-rendered Next.js
  // site carries `__NEXT_DATA__` and all of its text, and telling that owner
  // their page "builds itself in the browser" would be wrong and alarming.
  const shell = thin ? SHELL_SIGNALS.find(([, re]) => re.test(html))?.[0] : undefined;
  return { words, thin, ...(shell ? { shell } : {}) };
}

/** What we could actually observe on the source page. Everything is a count or
 *  a concrete id so no downstream label has to hedge. */
export type SourceSignals = {
  /** Adobe Fonts (Typekit) kit ids the page loaded, e.g. ["wyt4frb"]. */
  adobeKitIds: string[];
  /** Motion libraries / attribute conventions detected, e.g. ["GSAP"]. */
  motionLibs: string[];
  /** Third-party embeds that could not come over, ALREADY net of the ones the
   *  typed conversion carried across as native blocks (`withCarriedEmbeds` in
   *  htmlToSections.ts). Counts every element the capture treats as an embed -
   *  `<iframe>`, `<object>`, `<embed>` - because the captured lane promotes all
   *  three and its receipt reconciles against this number. */
  embeds: number;
  /** How many of the source's embed elements the TYPED conversion turned into
   *  blocks of ours, i.e. how much `embeds` above was reduced by. The captured
   *  lane builds a different draft from the same source, so its receipt has to
   *  reconcile against the raw embed count (`embeds + embedsCarried`) rather
   *  than subtract its own promotions from a number the typed lane already
   *  discounted - see `lostEmbedCount`. */
  embedsCarried?: number;
  /** How many of `embedsCarried` sit on the page a capture REPLACES (the home
   *  page). Every other page keeps its typed sections in the captured draft
   *  (`withCapturedSections`), so those carried films are still blocks there
   *  and adding them back to the raw count would report a working video as
   *  lost. Absent on a single-page conversion, where the only page is that
   *  page. */
  embedsCarriedHome?: number;
  /** Template placeholder runs still present in the copy ("Lorem ipsum"). */
  placeholders: number;
  /** How much readable text the SERVED document actually carried, and whether
   *  it looks like a page that builds itself in the browser. A site behind a
   *  client-side framework serves a near-empty shell to a fetcher, so the
   *  import "succeeds" and produces a business name and nothing else - the
   *  worst outcome in the product, and until now a completely silent one. */
  content?: SourceContentQuality;
  /** Evidence that the owner already sells online (see detectCommerce.ts).
   *  `null` when nothing was detected. Optional so callers that assemble their
   *  own signal object across a crawl keep compiling; those simply produce no
   *  store action. Detection only - nothing here activates commerce. */
  commerce?: CommerceDetection | null;
};

/**
 * How many of the source's embeds this draft really lost.
 *
 * Two lanes ask, and they are different drafts built from one source, so they
 * cannot share a subtraction:
 *
 * - The TYPED conversion carried some iframes over as native blocks, and
 *   `signals.embeds` is already net of those. Nothing more to subtract.
 * - The CAPTURED draft replaces the HOME page with the source's own DOM, with
 *   `capturedEmbeds` promoting the films and maps IT recognised. Subtracting
 *   its promotions from the typed lane's already reduced count discounted the
 *   same embed twice, so a home-page video plus one unsupported widget
 *   elsewhere reported nothing lost while the widget was simply absent. It adds
 *   back the raw embed elements of the page it replaced instead - `<iframe>`,
 *   `<object>` and `<embed>` alike, because the capture promotes all three and
 *   subtracting an `<object>` promotion from a count of iframes alone hid a
 *   real loss.
 *
 *   Only that page, though: `withCapturedSections` keeps every OTHER page's
 *   typed sections, so a subpage's YouTube iframe is still a native video in
 *   the captured draft. Adding it back to the raw count reported one loss for a
 *   film the owner can see - `embedsCarriedHome` is what keeps the two apart,
 *   and a signal that predates it falls back to the whole carried count.
 *
 * `embedsPromoted` is what tells the two lanes apart, so it is read for
 * PRESENCE: a captured draft that promoted nothing still lost every iframe on
 * the page it replaced.
 *
 * `embedsReplaced` is what is SUBTRACTED, because the count being reduced is a
 * count of source ELEMENTS. A page that ships the same film twice - a desktop
 * copy and a phone copy of one iframe - is two of those elements, and the
 * capture answers it with one logical block projected into both source boxes.
 * Subtracting the block count instead reported that
 * pair as one dropped embed while the film plays on every width. Absent (an
 * older caller) falls back to the block count, which is what it always was.
 */
export function lostEmbedCount(
  signals:
    | Pick<SourceSignals, "embeds" | "embedsCarried" | "embedsCarriedHome">
    | undefined,
  embedsPromoted?: number,
  embedsReplaced?: number,
): number {
  const netOfTyped = Math.max(0, signals?.embeds ?? 0);
  if (embedsPromoted === undefined) return netOfTyped;
  const carriedOnCapturedPage = Math.max(
    0,
    signals?.embedsCarriedHome ?? signals?.embedsCarried ?? 0,
  );
  const raw = netOfTyped + carriedOnCapturedPage;
  // Never fewer than the blocks built: a collapse count that arrives short (a
  // mark the sanitiser dropped before the box could be hidden) must not make a
  // promoted film read as lost.
  const accountedFor = Math.max(
    Math.max(0, embedsPromoted),
    Math.max(0, embedsReplaced ?? 0),
  );
  return Math.max(0, raw - accountedFor);
}

export const EMPTY_SIGNALS: SourceSignals = {
  adobeKitIds: [],
  motionLibs: [],
  embeds: 0,
  placeholders: 0,
  commerce: null,
};

// use.typekit.net/<kit>.js|css, and the older //use.typekit.com/<kit>.js form.
const TYPEKIT_RE = /use\.typekit\.(?:net|com)\/([a-z0-9]+)\.(?:js|css)/gi;
// Every element the capture treats as an embed, not only `<iframe>`. The
// capture's `markBehaviours` replaces `iframe,object,embed` alike and promotes
// whichever of them it recognises, so counting iframes alone let one promoted
// `<object>` cancel out an unsupported iframe that really did disappear: the
// receipt said nothing was lost while the widget was simply gone. The typed
// conversion drops `<object>` and `<embed>` too, so the wider count is the
// honest one on both lanes.
const EMBED_ELEMENT_RE = /<(?:iframe|object|embed)\b/gi;
// "Lorem ipsum" is the near-universal marker of an untouched template block
// (page-builder templates ship it); matching the two words together avoids flagging a
// page that happens to use the word "lorem" in prose.
const PLACEHOLDER_RE = /lorem\s+ipsum/gi;

/** Motion signals, most specific first. Each entry is [label, detector]. The
 *  label is shown to the owner, so it names the library, not the file. */
const MOTION_SIGNALS: Array<[string, RegExp]> = [
  ["GSAP", /\bgsap(?:\.min)?\.js|cdnjs[^"']*gsap/i],
  ["ScrollTrigger", /ScrollTrigger(?:\.min)?\.js/i],
  ["Lenis", /\blenis(?:\.min)?\.js/i],
  ["AOS", /\baos(?:\.min)?\.(?:js|css)|\bdata-aos=/i],
  ["Webflow", /\bdata-w-id=|\banimation-(?:fade|scroll)-/i],
  ["Framer Motion", /framer-motion/i],
];

const countOf = (html: string, re: RegExp) => (html.match(re) ?? []).length;

/**
 * Read a source page for everything the import can honestly act on. Cheap
 * regex only (no DOM): this runs inside a Convex action alongside the rest of
 * the import, and every signal is a "did we see this string" question.
 */
export function detectSourceSignals(
  html: string,
  css: string | string[] = [],
  /** The page's own URL. Optional: without it a cart link only counts when it
   *  is relative, because an absolute one could be somebody else's shop. */
  baseUrl?: string,
): SourceSignals {
  const styles = Array.isArray(css) ? css.join("\n") : css;
  const all = `${html}\n${styles}`;

  const adobeKitIds = [
    ...new Set([...html.matchAll(TYPEKIT_RE)].map((m) => m[1].toLowerCase())),
  ];
  const motionLibs = MOTION_SIGNALS.filter(([, re]) => re.test(all)).map(([label]) => label);

  return {
    adobeKitIds,
    motionLibs,
    embeds: countOf(html, EMBED_ELEMENT_RE),
    placeholders: countOf(html, PLACEHOLDER_RE),
    content: assessSourceContent(html),
    commerce: detectCommerce({ html, baseUrl }),
  };
}

type ActionLocale = "sv" | "en" | "pl";

type Copy = {
  adobeTitle: (kits: string) => string;
  adobeDetail: string;
  adobeWhere: string;
  motionTitle: string;
  motionDetail: (libs: string) => string;
  /** Used instead of `motionDetail` when we actually read the source page's
   *  own timing rather than only detecting that it had a motion library. */
  motionMeasuredDetail: (libs: string) => string;
  motionWhere: string;
  motionNoteBlur: (loadPx: number, scrollPx: number) => string;
  motionNoteParallax: (count: number) => string;
  motionNoteAttrs: (families: string) => string;
  motionNoteSmoothScroll: string;
  placeholderTitle: string;
  placeholderDetail: string;
  placeholderWhere: string;
  assetsTitle: (n: number) => string;
  assetsDetail: string;
  assetsWhere: string;
  embedsTitle: (n: number) => string;
  embedsDetail: string;
  /** High confidence: we can name the shop, so the advice is concrete. */
  storeTitleHigh: (provider: string) => string;
  storeDetailHigh: (provider: string, products: number | null) => string;
  /** Low confidence: we know they sell, not what on. Ask, don't assume. */
  storeTitleLow: string;
  storeDetailLow: (found: string) => string;
  contactTitle: string;
  contactDetail: string;
  contactWhere: string;
  /** Why the design was read out of source CSS instead of measured off a real
   *  render, in the owner's words. One entry per skip reason, so a new reason
   *  cannot ship without copy. */
  design: Record<MeasureSkipReason, { title: string; detail: string; where?: string }>;
  /** The served page carried almost no readable text. Two versions: one where
   *  we can name the tool that builds the page in the browser, one where we
   *  cannot and must not guess. */
  thinTitle: string;
  thinShellDetail: (shell: string) => string;
  thinDetail: (words: number) => string;
  thinWhere: string;
};

const COPY: Record<ActionLocale, Copy> = {
  sv: {
    adobeTitle: (kits) => `Vi har bytt ut typsnitten från Adobe Fonts (${kits})`,
    adobeDetail:
      "Sidan hämtade sina typsnitt från Adobe Fonts. Ett sådant kit fungerar bara på de domäner kitets ägare har lagt in hos Adobe, och det kan vi inte göra åt dig — så vi har valt de närmaste typsnitt vi kan visa. Har du filerna till originaltypsnitten kan du ladda upp dem, annars går det bra att byta till ett av våra.",
    adobeWhere: "Redigeraren → Design → Typsnitt",
    motionTitle: "Se över rörelsen på sidan",
    motionDetail: (libs) =>
      `Originalet animerade innehållet med ${libs}. Vi har satt på Snabbsites egen rörelse i stället, så sidan inte blir helt stilla – men den är inte identisk med originalet. Titta igenom och justera styrkan, eller stäng av den.`,
    motionMeasuredDetail: (libs) =>
      `Originalet animerade innehållet med ${libs}. Vi läste av hur långt, hur snabbt och med vilken kurva innehållet rör sig och byggde om det med Snabbsites egen rörelse - utan någon extra kod på din hemsida. Titta igenom och justera, eller stäng av den.`,
    motionWhere: "Utseende → Rörelse",
    motionNoteBlur: (loadPx, scrollPx) =>
      `Sidan gjorde innehållet suddigt ${loadPx} px när den laddades och ${scrollPx} px vid scroll. Vi har en oskärpa, så båda använder ${scrollPx} px.`,
    motionNoteParallax: (count) =>
      count === 1
        ? "Ett element gled i annan takt än sidan (parallax). Rörelsen finns kvar som inställning, men vi kunde inte peka ut exakt vilken sektion den satt på."
        : `${count} element gled i annan takt än sidan (parallax). Rörelsen finns kvar som inställning, men vi kunde inte peka ut exakt vilka sektioner de satt på.`,
    motionNoteAttrs: (families) =>
      `Sidan hade animationer (${families}) som vi inte kunde läsa, så hemsidan använder Snabbsites standardrörelse i stället.`,
    motionNoteSmoothScroll:
      "Sidan använde ett skript för mjuk scroll. Snabbsite scrollar mjukt till länkar på sidan utan extra kod, men själva sidan scrollar normalt.",
    placeholderTitle: "Byt ut mallens platshållartext",
    placeholderDetail:
      "Vi hittade ”Lorem ipsum” kvar från mallen originalet byggdes på. Den följde med som den var – skriv över den med din egen text innan du publicerar.",
    placeholderWhere: "Redigeraren",
    assetsTitle: (n) => `${n} ${n === 1 ? "bild kom" : "bilder kom"} inte över`,
    assetsDetail:
      "Importen har en gräns för hur många bilder som följer med. Resten laddar du upp själv där du vill ha dem.",
    assetsWhere: "Redigeraren → bildplatserna",
    embedsTitle: (n) =>
      `${n} ${n === 1 ? "inbäddning" : "inbäddningar"} följde inte med`,
    embedsDetail:
      "Kartor, videor och bokningsfönster från andra tjänster kan inte flyttas automatiskt. Lägg tillbaka dem med rätt sektion.",
    storeTitleHigh: (provider) => `Behåll butiken i ${provider} – länka till den härifrån`,
    storeDetailHigh: (provider, products) =>
      `Du säljer redan via ${provider}${products ? ` – minst ${products} produkter` : ""}. Vi har inte flyttat, ändrat eller aktiverat någonting: produkter, lager och ordrar ligger kvar där de är. Enklast är att låta butiken vara kvar och länka till den från nya hemsidan.`,
    storeTitleLow: "Bestäm om kunderna ska kunna handla direkt på hemsidan",
    storeDetailLow: (found) =>
      `Sidan ser ut att sälja något redan (${found}). Vi har inte flyttat eller aktiverat någonting. Säg till så visar vi exakt vad vi hittade.`,
    contactTitle: "Fyll i dina kontaktuppgifter",
    contactDetail:
      "Vi hittade varken e-post eller telefonnummer på sidan. Utan dem kan besökare inte höra av sig.",
    contactWhere: "Inställningar → Kontakt",
    thinTitle: "Vi fick nästan ingen text från din sida",
    thinShellDetail: (shell) =>
      `Din sida byggs ihop i besökarens webbläsare (${shell}), så koden vi hämtade är nästan tom. Det vi kunde läsa har följt med, men det blir en tunn hemsida. Skriv in texten själv i redigeraren, eller hör av dig så hämtar vi sidan på ett annat sätt.`,
    thinDetail: (words) =>
      `Vi hittade bara ${words} ord på sidan. Antingen ligger texten i bilder eller i kod som inte följer med, eller så var sidan tom när vi läste den. Kontrollera resultatet och fyll på med din egen text.`,
    thinWhere: "Redigeraren",
    design: {
      "no-live-url": {
        title: "Importera med webbadressen om du vill ha exakt samma design",
        detail:
          "Vi mäter typsnitt, storlekar och avstånd genom att öppna din riktiga sida. Den här importen kom från en fil eller inklistrad kod, så vi läste designen ur koden i stället – det är en kvalificerad gissning, inte en mätning. Kör om importen med adressen till sidan så blir den mer lik originalet.",
        where: "Importera → Från webbadress",
      },
      "no-renderer": {
        title: "Designen är läst ur koden, inte mätt på sidan",
        detail:
          "Vi kunde inte öppna din sida i en webbläsare den här gången, så typsnitt, storlekar och avstånd är lästa ur källkoden. Sidan fungerar, men den kan skilja sig från originalet. Justera färg och typsnitt här nedanför om något ser fel ut.",
      },
      "render-failed": {
        title: "Vi kom inte in på din sida för att mäta designen",
        detail:
          "Sidan svarade inte, tog för lång tid eller blockerade oss, så vi läste designen ur koden i stället. Kontrollera att sidan är öppen för besökare och kör om importen om du vill att vi mäter den på riktigt.",
        where: "Importera → Från webbadress",
      },
    },
  },
  en: {
    adobeTitle: (kits) => `We replaced the fonts that came from Adobe Fonts (${kits})`,
    adobeDetail:
      "The page loaded its fonts from Adobe Fonts. A kit only works on the domains its owner has added inside Adobe, and we cannot do that for you — so we picked the closest faces we can actually serve. If you have the original font files you can upload them; otherwise one of ours works fine.",
    adobeWhere: "Editor → Design → Fonts",
    motionTitle: "Check the motion on the page",
    motionDetail: (libs) =>
      `The original animated its content with ${libs}. We turned on Snabbsite's own motion instead, so the page isn't completely still - but it is not identical to the original. Look it over and adjust the strength, or turn it off.`,
    motionMeasuredDetail: (libs) =>
      `The original animated its content with ${libs}. We read how far, how fast and on what curve the content moves, and rebuilt it with Snabbsite's own motion - with no extra code on your site. Look it over and adjust, or turn it off.`,
    motionWhere: "Appearance → Motion",
    motionNoteBlur: (loadPx, scrollPx) =>
      `The page blurred content by ${loadPx}px on load and ${scrollPx}px on scroll. We carry one blur, so both use ${scrollPx}px.`,
    motionNoteParallax: (count) =>
      count === 1
        ? "One element drifted at a different speed to the page (a parallax). The movement is kept as a setting, but we could not tell which section it belonged to."
        : `${count} elements drifted at a different speed to the page (a parallax). The movement is kept as a setting, but we could not tell which sections they belonged to.`,
    motionNoteAttrs: (families) =>
      `The page declared animations (${families}) we could not read, so this site uses Snabbsite's standard motion instead.`,
    motionNoteSmoothScroll:
      "The page used a smooth-scroll script. Snabbsite scrolls smoothly to in-page links without extra code, but the page itself scrolls normally.",
    placeholderTitle: "Replace the template's placeholder text",
    placeholderDetail:
      "We found “Lorem ipsum” left over from the template the original was built on. It came across as-is - write over it before you publish.",
    placeholderWhere: "The editor",
    assetsTitle: (n) => `${n} ${n === 1 ? "image" : "images"} didn't come over`,
    assetsDetail:
      "There is a limit on how many images one import carries. Upload the rest yourself where you want them.",
    assetsWhere: "The editor → the image slots",
    embedsTitle: (n) => `${n} ${n === 1 ? "embed" : "embeds"} didn't come over`,
    embedsDetail:
      "Maps, videos and booking widgets from other services can't be moved automatically. Add them back with the matching section.",
    storeTitleHigh: (provider) => `Keep your shop on ${provider} - link to it from here`,
    storeDetailHigh: (provider, products) =>
      `You already sell through ${provider}${products ? ` - at least ${products} products` : ""}. We have not moved, changed or switched anything on: products, stock and orders are still where they were. The simplest thing is to leave the shop where it is and link to it from the new site.`,
    storeTitleLow: "Decide whether customers should be able to buy directly on the site",
    storeDetailLow: (found) =>
      `The page looks like it already sells something (${found}). We have not moved or switched anything on. Say the word and we'll show you exactly what we found.`,
    contactTitle: "Fill in your contact details",
    contactDetail:
      "We found neither an email address nor a phone number on the page. Without them visitors can't reach you.",
    contactWhere: "Settings → Contact",
    thinTitle: "We got almost no text from your page",
    thinShellDetail: (shell) =>
      `Your page is assembled in the visitor's browser (${shell}), so the code we fetched is nearly empty. What we could read came across, but the result is thin. Type the text in yourself in the editor, or get in touch and we'll fetch the page a different way.`,
    thinDetail: (words) =>
      `We found only ${words} words on the page. Either the text lives in images or in code that doesn't come across, or the page was empty when we read it. Check the result and fill in your own text.`,
    thinWhere: "The editor",
    design: {
      "no-live-url": {
        title: "Import by web address if you want the design to match exactly",
        detail:
          "We measure fonts, sizes and spacing by opening your real page. This import came from a file or pasted code, so we read the design out of the code instead - an educated guess, not a measurement. Run the import again with the page's address and it will come closer to the original.",
        where: "Import → From a web address",
      },
      "no-renderer": {
        title: "The design was read from code, not measured on the page",
        detail:
          "We couldn't open your page in a browser this time, so fonts, sizes and spacing were read out of the source code. The site works, but it may differ from the original. Adjust the colour and fonts below if anything looks off.",
      },
      "render-failed": {
        title: "We couldn't reach your page to measure the design",
        detail:
          "The page didn't answer, took too long, or blocked us, so we read the design out of the code instead. Check that the page is open to visitors and run the import again if you want us to measure it for real.",
        where: "Import → From a web address",
      },
    },
  },
  pl: {
    adobeTitle: (kits) => `Zamieniliśmy czcionki z Adobe Fonts (${kits})`,
    adobeDetail:
      "Strona ładowała czcionki z Adobe Fonts. Zestaw działa tylko na domenach dodanych przez jego właściciela w Adobe, a tego nie zrobimy za Ciebie — wybraliśmy więc najbliższe czcionki, które możemy pokazać. Jeśli masz pliki oryginalnych czcionek, możesz je wgrać; w przeciwnym razie jedna z naszych w zupełności wystarczy.",
    adobeWhere: "Edytor → Design → Czcionki",
    motionTitle: "Sprawdź ruch na stronie",
    motionDetail: (libs) =>
      `Oryginał animował treść przy użyciu ${libs}. Włączyliśmy zamiast tego własny ruch Snabbsite, żeby strona nie była całkiem statyczna - ale nie jest identyczny z oryginałem. Przejrzyj go i dostosuj siłę albo wyłącz.`,
    motionMeasuredDetail: (libs) =>
      `Oryginał animował treść przy użyciu ${libs}. Odczytaliśmy, jak daleko, jak szybko i po jakiej krzywej porusza się treść, i odtworzyliśmy to własnym ruchem Snabbsite - bez dodatkowego kodu na Twojej stronie. Przejrzyj i dostosuj albo wyłącz.`,
    motionWhere: "Wygląd → Ruch",
    motionNoteBlur: (loadPx, scrollPx) =>
      `Strona rozmywała treść o ${loadPx} px przy ładowaniu i o ${scrollPx} px przy przewijaniu. Mamy jedno rozmycie, więc oba używają ${scrollPx} px.`,
    motionNoteParallax: (count) =>
      count === 1
        ? "Jeden element przesuwał się w innym tempie niż strona (paralaksa). Ruch pozostaje jako ustawienie, ale nie mogliśmy wskazać dokładnej sekcji."
        : `${count} elementy przesuwały się w innym tempie niż strona (paralaksa). Ruch pozostaje jako ustawienie, ale nie mogliśmy wskazać dokładnych sekcji.`,
    motionNoteAttrs: (families) =>
      `Strona deklarowała animacje (${families}), których nie udało się odczytać, więc ta witryna używa standardowego ruchu Snabbsite.`,
    motionNoteSmoothScroll:
      "Strona używała skryptu płynnego przewijania. Snabbsite płynnie przewija do linków na stronie bez dodatkowego kodu, ale sama strona przewija się normalnie.",
    placeholderTitle: "Zamień tekst zastępczy z szablonu",
    placeholderDetail:
      "Znaleźliśmy „Lorem ipsum” pozostawione z szablonu. Przeniosło się bez zmian - zastąp je własnym tekstem przed publikacją.",
    placeholderWhere: "Edytor",
    assetsTitle: (n) => `${n} ${n === 1 ? "obraz nie został" : "obrazów nie zostało"} przeniesionych`,
    assetsDetail:
      "Jeden import przenosi ograniczoną liczbę obrazów. Resztę wgraj samodzielnie tam, gdzie mają się znaleźć.",
    assetsWhere: "Edytor → miejsca na obrazy",
    embedsTitle: (n) =>
      `${n} ${n === 1 ? "osadzenie nie zostało" : "osadzeń nie zostało"} przeniesionych`,
    embedsDetail:
      "Mapy, filmy i widgety rezerwacji z innych usług nie mogą zostać przeniesione automatycznie. Dodaj je ponownie odpowiednią sekcją.",
    storeTitleHigh: (provider) => `Zostaw sklep w ${provider} - podlinkuj go stąd`,
    storeDetailHigh: (provider, products) =>
      `Sprzedajesz już przez ${provider}${products ? ` - co najmniej ${products} produktów` : ""}. Niczego nie przenieśliśmy, nie zmieniliśmy ani nie włączyliśmy: produkty, stany magazynowe i zamówienia zostają tam, gdzie były. Najprościej zostawić sklep na miejscu i podlinkować go z nowej strony.`,
    storeTitleLow: "Zdecyduj, czy klienci mają móc kupować bezpośrednio na stronie",
    storeDetailLow: (found) =>
      `Strona wygląda, jakby już coś sprzedawała (${found}). Niczego nie przenieśliśmy ani nie włączyliśmy. Daj znać, a pokażemy dokładnie, co znaleźliśmy.`,
    contactTitle: "Uzupełnij dane kontaktowe",
    contactDetail:
      "Nie znaleźliśmy ani adresu e-mail, ani numeru telefonu. Bez nich odwiedzający nie mogą się skontaktować.",
    contactWhere: "Ustawienia → Kontakt",
    thinTitle: "Z twojej strony pobraliśmy prawie żaden tekst",
    thinShellDetail: (shell) =>
      `Twoja strona składana jest w przeglądarce odwiedzającego (${shell}), więc pobrany kod jest niemal pusty. To, co udało się odczytać, zostało przeniesione, ale wynik jest ubogi. Wpisz tekst samodzielnie w edytorze albo napisz do nas, a pobierzemy stronę inaczej.`,
    thinDetail: (words) =>
      `Znaleźliśmy tylko ${words} słów na stronie. Albo tekst jest w obrazach lub w kodzie, który się nie przenosi, albo strona była pusta, gdy ją odczytywaliśmy. Sprawdź wynik i uzupełnij własny tekst.`,
    thinWhere: "Edytor",
    design: {
      "no-live-url": {
        title: "Zaimportuj przez adres strony, jeśli chcesz identyczny wygląd",
        detail:
          "Czcionki, rozmiary i odstępy mierzymy, otwierając twoją prawdziwą stronę. Ten import pochodził z pliku lub wklejonego kodu, więc wygląd odczytaliśmy z kodu - to przybliżenie, nie pomiar. Uruchom import ponownie z adresem strony, a wynik będzie bliższy oryginałowi.",
        where: "Import → Z adresu strony",
      },
      "no-renderer": {
        title: "Wygląd odczytano z kodu, a nie zmierzono na stronie",
        detail:
          "Tym razem nie mogliśmy otworzyć twojej strony w przeglądarce, więc czcionki, rozmiary i odstępy odczytaliśmy z kodu źródłowego. Strona działa, ale może różnić się od oryginału. Popraw kolor i czcionki poniżej, jeśli coś wygląda źle.",
      },
      "render-failed": {
        title: "Nie udało nam się wejść na stronę, żeby zmierzyć wygląd",
        detail:
          "Strona nie odpowiedziała, trwało to za długo albo nas zablokowano, więc wygląd odczytaliśmy z kodu. Sprawdź, czy strona jest dostępna dla odwiedzających, i uruchom import ponownie, jeśli chcesz, żebyśmy ją naprawdę zmierzyli.",
        where: "Import → Z adresu strony",
      },
    },
  },
};

/** Most-blocking first, then by how likely the owner is to be embarrassed by
 *  it in front of a visitor. */
const ORDER: ImportActionCode[] = [
  // Nothing else matters if the page we read was empty.
  "source_barely_readable",
  "adobe_fonts_kit",
  // A design read from code instead of measured is the single biggest reason an
  // import "looks nearly right but not quite", so it ranks above cosmetics.
  "design_not_measured",
  "placeholder_text",
  // Visible defects first, then the biggest business decision the import puts
  // in front of the owner, then the rest.
  "store_detected",
  "contact_missing",
  "assets_skipped",
  "embeds_dropped",
  "motion_rebuilt",
];

/**
 * Turn observed signals + import outcome into the owner's follow-up list.
 * Every branch is gated on something we actually saw, so an import with
 * nothing to fix honestly returns an empty array.
 */
export function buildImportActions(input: {
  signals?: SourceSignals;
  /** Images the import had to skip (asset cap). */
  droppedAssets?: number;
  /** True when the imported site ended up with motion switched on. */
  motionCarried?: boolean;
  /** True when the source page's OWN timing was read (`theme.customMotion`),
   *  rather than motion merely being switched on because a library was seen. */
  motionMeasured?: boolean;
  /** What the source page's motion had that we could not carry across. */
  motionNotes?: MotionNote[];
  /** False when neither email nor phone was found on the source. */
  hasContact?: boolean;
  /** Embeds the CAPTURED lane turned into a block of ours (a film, a map).
   *  `signals.embeds` counts what the source declared, so without this the
   *  owner reads "your embeds were dropped" underneath a working map. */
  embedsPromoted?: number;
  /** Source boxes those blocks stand in for - two, for a film shipped once per
   *  layout. See `lostEmbedCount`: the subtraction is in elements, not blocks. */
  embedsReplaced?: number;
  /** Why the design was NOT measured off a real render of the source. Absent
   *  means it was measured (or the caller predates the boundary) - either way
   *  no action, because "we did the accurate thing" is not a follow-up. */
  designSkipped?: MeasureSkipReason;
  locale?: ActionLocale;
}): ImportAction[] {
  const L = COPY[input.locale ?? "sv"];
  const s = input.signals ?? EMPTY_SIGNALS;
  const out: ImportAction[] = [];

  if (s.adobeKitIds.length > 0) {
    out.push({
      code: "adobe_fonts_kit",
      // Informational since 2026-08-08: there is nothing the owner MUST do.
      // The import no longer waits on a kit it cannot be allowed into — it
      // substitutes, and the receipt says which face replaced which.
      severity: "info",
      title: L.adobeTitle(s.adobeKitIds.join(", ")),
      detail: L.adobeDetail,
      where: L.adobeWhere,
    });
  }

  // Nothing else on this list matters if the page we read was empty. A site
  // behind a client-side framework serves a shell to a fetcher, so the import
  // "succeeds" and the owner opens a site with their name on it and nothing
  // else, with no idea why.
  const content = s.content;
  if (content?.thin) {
    out.push({
      code: "source_barely_readable",
      severity: "action",
      title: L.thinTitle,
      detail: content.shell ? L.thinShellDetail(content.shell) : L.thinDetail(content.words),
      where: L.thinWhere,
    });
  }

  // The silent degrade this exists to end: four of the six import lanes never
  // reached the measured-design path, and an owner whose import came out
  // approximate was never told why or what to do about it.
  if (input.designSkipped) {
    const copy = L.design[input.designSkipped];
    out.push({
      code: "design_not_measured",
      // Only the reasons the OWNER can act on are an action. A missing renderer
      // is our configuration, not their to-do list.
      // The usable typed import already exists. A renderer miss is our
      // diagnostic, not work the owner must complete before continuing.
      severity: "info",
      title: copy.title,
      detail: copy.detail,
      ...(copy.where ? { where: copy.where } : {}),
    });
  }

  if (s.placeholders > 0) {
    out.push({
      code: "placeholder_text",
      severity: "action",
      title: L.placeholderTitle,
      detail: L.placeholderDetail,
      where: L.placeholderWhere,
    });
  }

  // A store we found is never a blocker: the owner can publish the new site
  // with the old shop still running exactly as it did. It is an "action"
  // because somebody has to DECIDE - and the deciding is theirs, not ours.
  const store = s.commerce;
  if (store) {
    const provider = STORE_PROVIDER_LABELS[store.provider];
    const named = store.confidence === "high" && provider !== "";
    out.push({
      code: "store_detected",
      severity: "action",
      title: named ? L.storeTitleHigh(provider) : L.storeTitleLow,
      detail: named
        ? L.storeDetailHigh(provider, store.productCountEstimate)
        : L.storeDetailLow(store.evidence.slice(0, 2).join(", ")),
    });
  }

  if (input.hasContact === false) {
    out.push({
      code: "contact_missing",
      severity: "action",
      title: L.contactTitle,
      detail: L.contactDetail,
      where: L.contactWhere,
    });
  }

  if ((input.droppedAssets ?? 0) > 0) {
    out.push({
      code: "assets_skipped",
      severity: "action",
      title: L.assetsTitle(input.droppedAssets!),
      detail: L.assetsDetail,
      where: L.assetsWhere,
    });
  }

  // Only the embeds that really did fall out. A captured lane puts the films
  // and maps it recognised back as blocks of ours, and counting those as
  // dropped sends the owner looking for something that is already on the page.
  const embedsLost = lostEmbedCount(s, input.embedsPromoted, input.embedsReplaced);
  if (embedsLost > 0) {
    out.push({
      code: "embeds_dropped",
      severity: "action",
      title: L.embedsTitle(embedsLost),
      detail: L.embedsDetail,
    });
  }

  // Only worth saying when the source HAD motion. A still source that imports
  // still has nothing to review.
  if (s.motionLibs.length > 0 && input.motionCarried) {
    const libs = s.motionLibs.join(", ");
    const notes = (input.motionNotes ?? []).map((note) => {
      switch (note.code) {
        case "blur-differs":
          return L.motionNoteBlur(note.loadPx, note.scrollPx);
        case "parallax-unmapped":
          return L.motionNoteParallax(note.count);
        case "attrs-unread":
          return L.motionNoteAttrs(note.families.join(", "));
        case "smooth-scroll":
          return L.motionNoteSmoothScroll;
      }
    });
    // The measured wording is a different promise from the fallback one, so it
    // gets its own sentence rather than a hedge that covers both.
    const head = input.motionMeasured
      ? L.motionMeasuredDetail(libs)
      : L.motionDetail(libs);
    out.push({
      code: "motion_rebuilt",
      severity: "info",
      title: L.motionTitle,
      detail: [head, ...notes].join(" "),
      where: L.motionWhere,
    });
  }

  return out.sort((a, b) => ORDER.indexOf(a.code) - ORDER.indexOf(b.code));
}
