// GENERATED by scripts/mirror-import.ts from HH-Studio/simple-site-builder:lib/import/sectionProposal.ts
// Do not edit. Run `bun scripts/mirror-import.ts --sync-from-app <appRoot>`.

import type { SectionType } from "../../../convex/model/sections";
import { SECTION_REGISTRY } from "../../../lib/sections/registry";
import { isGapEmpty, missingForVariant } from "../sections/variantRequirements";
import { observeBlock, splitBlocksAt } from "./layoutObserve";
import type { LayoutShape } from "../sections/layoutShape";
import { decodeHtmlEntities } from "../html/entities";

// ---------------------------------------------------------------------------
// The prompt and the parser for the optional pass that lets a model name the
// BLOCK an imported band should become. Pure and dependency-free so it is unit
// testable; the network call lives in `convex/import/sectionProposals.ts`.
//
// What this is FOR. `buildPageSections` runs a ladder of deterministic
// detectors, and every one of them is gated on evidence it can prove - a
// Swedish or English heading it recognises, a real repeat, a price pattern. A
// source that says "Vad ingår hos oss" instead of "Våra tjänster", or that is
// written in Polish, or that leads with a statement the detectors have no
// keyword for, falls through to the generic `highlights` grid. So the block a
// page actually IS gets flattened, and the 144 layout variants the registry
// offers are reduced to a handful of defaults.
//
// Four rules bound what a proposal is allowed to change, and they are the
// reason this can be shipped on the flagship path at all:
//
//   1. **The model returns a LABEL, never content.** `sectionType`,
//      `variantKey`, `confidence` and nothing else. Every word, price, phone
//      number and picture on the imported page still comes from the
//      deterministic extraction in `htmlToSections.ts`. A model that is allowed
//      to write a phone number will eventually write a wrong one, and no amount
//      of prompt care makes that safe.
//   2. **Both enums are closed to the registry.** A `sectionType` outside
//      `SECTION_REGISTRY`, or a `variantKey` that is not one of THAT type's own
//      variants, is discarded at parse time and the deterministic choice stands.
//   3. **Below the confidence floor, the deterministic choice wins.**
//   4. **A re-type may never invent or drop a field.** `applySectionProposals`
//      only re-types through `RETYPE_FAMILY`, whose members carry a
//      structurally identical content model, and only when every item already
//      holds what the target requires.
//
// Structure, not screenshots (the plan's open question, settled 2026-08-16).
// The plan sketched a per-band screenshot and a vision model. But
// `layoutObserve.ts` already extracts the band's structure - repeat detection,
// item roles, media weight, carousel vs stack - and `layoutShape.ts` already
// ranks that structure against every registry type. Feeding those to an
// ordinary text model needs no crop, no upload, no storage path and no vision
// pricing, and leaves every safety property above unchanged. If the structural
// signal later proves too thin to separate two layouts, the screenshot route is
// still open behind this same seam: `SectionBand` grows a field and the parser
// does not change.
//
// What the band digest does NOT carry, and why (2026-08-17, backlog 2643). It
// used to end with `closest=`, the ranking `layoutShape.assessShape` gives the
// band, offered to the model as a prior. Measured over the fidelity corpus's 48
// bands that prior is not a weak signal, it is filler: 36 of the 48 were topped
// by `booking` (19) or `video` (17), and NEITHER type appears in a single one of
// the corpus's 75 truth labels. Nor do `illustration`, `imported`, `newsletter`,
// `comparison-slider`, `restaurant-menu` or `events`, all of which it named,
// while `about`, `image`, `gallery` and `rich-text` - types the pages really are
// - it never named once. It ranked the dentist hero as
// `video,newsletter,statement` and the contact band as `pricing,services,footer`.
// So the field is gone rather than repaired: `assessShape` is shared with
// `convex/layoutIdeas.ts` and `convex/importWholeSiteNode.ts`, where it scores a
// shape for a different purpose, and re-scoring it to serve this prompt would
// change those two without measuring them. Repairing it stays open in `2643`.
// ---------------------------------------------------------------------------

/** Below this, the deterministic choice stands. Deliberately high: the cost of
 *  a wrong label is an owner opening a rebuilt page that says something their
 *  page did not, and the cost of a missing label is what we already ship. */
export const PROPOSAL_CONFIDENCE_FLOOR = 0.7;

/** Bands per page we describe to the model. `splitBlocksAt` already caps at 12;
 *  this is the request-shaping half of the same bound. */
export const MAX_PROPOSAL_BANDS = 12;

/** Longest text sample per band. Enough for the model to tell a process from a
 *  service list, short enough that twelve of them fit one small request. */
const BAND_TEXT_CHARS = 300;

export type SectionBand = {
  /** Position in the band list. The id the model answers with. */
  index: number;
  /** Byte offset in the source HTML - the join key back to a built section. */
  at: number;
  /** The sanitized, size-capped markup that produced this observation. Kept
   *  local for deterministic fallback extraction and never sent to a model. */
  html: string;
  /** The band's own heading, verbatim from the source. */
  heading: string;
  /** Structure only: roles, repeat, media weight, flow. Never content. */
  shape: LayoutShape;
  /** How many times the repeated card/row occurs (0 = nothing repeats). */
  itemCount: number;
  /** A short prose sample, so "so här går det till" can be told from a price
   *  list. Read by the model, never written back to the page. */
  text: string;
};

function stripTags(html: string): string {
  return decodeHtmlEntities(html.replace(/<[^>]+>/g, " "))
    .replace(/\s+/g, " ")
    .trim();
}

function headingOf(block: string): string {
  const match = block.match(/<h([1-4])[^>]*>([\s\S]*?)<\/h\1>/i);
  return match ? stripTags(match[2]).slice(0, 120) : "";
}

/**
 * How many times the band's card or row occurs.
 *
 * Counted from the markup rather than from the observed shape on purpose. A
 * shape's `itemRoles` is null whenever the repeated element carries no
 * recognised role, which is exactly what a list of bare labels
 * (`<li>Tak</li><li>Fasad</li>`) looks like - so reading the count off the
 * shape reported "nothing repeats" for the plainest repeat there is. The count
 * is a separate signal and is allowed to disagree with the roles.
 */
function repeatCount(block: string): number {
  const items = [...block.matchAll(/<li\b/gi)].length;
  if (items >= 3) return items;
  const classed = new Map<string, number>();
  for (const match of block.matchAll(
    /<(div|article|a)\b[^>]*class=["']([^"']+)["']/gi,
  )) {
    const first = match[2].trim().split(/\s+/)[0];
    if (!first) continue;
    const key = `${match[1].toLowerCase()}.${first}`;
    classed.set(key, (classed.get(key) ?? 0) + 1);
  }
  const most = Math.max(0, ...classed.values());
  return most >= 3 ? most : 0;
}

/**
 * Describe every band on a page, structurally plus a text sample.
 *
 * Deterministic and pure, so the caller that builds the request and the caller
 * that applies the answer can each compute the list independently and get the
 * same indices - there is no band list to carry between them.
 */
export function bandsOf(html: string): SectionBand[] {
  return splitBlocksAt(html)
    .slice(0, MAX_PROPOSAL_BANDS)
    .map((block, index) => {
      const shape = observeBlock(block.html);
      return {
        index,
        at: block.at,
        html: block.html,
        heading: headingOf(block.html),
        shape,
        itemCount: repeatCount(block.html),
        text: stripTags(block.html).slice(0, BAND_TEXT_CHARS),
      };
    });
}

/** The catalogue the model chooses from: every registry type, what it is for,
 *  and its own layout keys. Built from `SECTION_REGISTRY` so a section type
 *  added tomorrow joins the choice without anyone remembering this file - the
 *  same reason `whenToUse` exists ("the exact spec an LLM block-selector
 *  reads", registry.ts). */
export function sectionCatalogue(): string {
  return Object.values(SECTION_REGISTRY)
    .map((def) => {
      const variants = def.variants.map((v) => v.key).join("|");
      return `${def.type}: ${def.whenToUse.en.slice(0, 130)} [${variants}]`;
    })
    .join("\n");
}

export const SECTION_PROPOSAL_SYSTEM_PROMPT = [
  "You are rebuilding a small business's existing website with a fixed catalogue of blocks.",
  "For each numbered band of the source page, name the block type and layout that best matches WHAT THE BAND IS.",
  "",
  "Rules:",
  "- Choose only from the catalogue below. A type or layout key that is not listed is discarded.",
  "- The layout key must belong to the type you chose.",
  '- Judge the band\'s PURPOSE, not its wording. "Så går det till", "Vad händer sedan" and "Steg för steg" are all a process block.',
  "- Never invent content. You are labelling bands; the text and pictures are taken from the page itself.",
  '- confidence is 0..1. Below 0.7 the label is ignored, so use a low number when you are unsure rather than guessing.',
  "",
  'Reply with JSON only: [{"i":0,"type":"services","variant":"grid-3","confidence":0.9}]. No prose, no code fence.',
  "",
  "Catalogue (type: what it is for [layout keys]):",
  sectionCatalogue(),
].join("\n");

/** One band's line in the request. Structure and a text sample; no markup, no
 *  class names, no image URLs, no colours. */
export function describeBand(band: SectionBand, currentType?: string): string {
  const bits = [`#${band.index}`];
  if (currentType) bits.push(`current=${currentType}`);
  if (band.heading) bits.push(`heading="${band.heading}"`);
  bits.push(`roles=${band.shape.roles.join("+") || "-"}`);
  bits.push(`item_roles=${band.shape.itemRoles?.join("+") ?? "-"}`);
  if (band.itemCount > 0) bits.push(`repeats=${band.itemCount}`);
  bits.push(`media=${band.shape.media}`);
  bits.push(`flow=${band.shape.flow}`);
  if (band.text) bits.push(`text="${band.text}"`);
  return bits.join(" ");
}

export type SectionProposal = {
  sectionType: SectionType;
  /** Absent when the model named no layout, or named one this type does not
   *  have. The type's default is then used, exactly as today. */
  variantKey?: string;
  confidence: number;
};

function isSectionType(value: string): value is SectionType {
  return Object.prototype.hasOwnProperty.call(SECTION_REGISTRY, value);
}

/**
 * Accept a model reply, keeping only what is safe to act on.
 *
 * Everything is validated against the bands that were actually sent: an index
 * we did not ask about, a type outside the registry, a confidence that is not a
 * number in 0..1. A layout key that does not belong to the chosen type is
 * dropped on its own and the type survives - naming the right block with the
 * wrong layout is still a better answer than nothing. An unparseable reply
 * yields an empty map and every deterministic choice stands.
 */
export function parseProposalResponse(
  text: string,
  bands: readonly SectionBand[],
): Map<number, SectionProposal> {
  const out = new Map<number, SectionProposal>();
  let rows: unknown;
  try {
    // Models still fence JSON now and then despite being told not to.
    const cleaned = text
      .trim()
      .replace(/^```(?:json)?\s*/i, "")
      .replace(/```\s*$/, "")
      .trim();
    const start = cleaned.indexOf("[");
    const end = cleaned.lastIndexOf("]");
    if (start === -1 || end <= start) return out;
    rows = JSON.parse(cleaned.slice(start, end + 1));
  } catch {
    return out;
  }
  if (!Array.isArray(rows)) return out;

  for (const row of rows) {
    if (typeof row !== "object" || row === null) continue;
    const r = row as { i?: unknown; type?: unknown; variant?: unknown; confidence?: unknown };
    if (typeof r.i !== "number" || !Number.isInteger(r.i)) continue;
    if (!bands.some((b) => b.index === r.i)) continue;
    if (typeof r.type !== "string") continue;
    const sectionType = r.type.trim().toLowerCase();
    if (!isSectionType(sectionType)) continue;
    if (typeof r.confidence !== "number" || !Number.isFinite(r.confidence)) continue;
    const confidence = Math.min(1, Math.max(0, r.confidence));

    const proposal: SectionProposal = { sectionType, confidence };
    if (typeof r.variant === "string") {
      const key = r.variant.trim();
      if (SECTION_REGISTRY[sectionType].variants.some((v) => v.key === key)) {
        proposal.variantKey = key;
      }
    }
    out.set(r.i, proposal);
  }
  return out;
}

// --- applying a proposal ----------------------------------------------------

/**
 * Section types whose content models are structurally IDENTICAL, so one can be
 * re-typed into another by renaming the array and nothing else.
 *
 * This is the whole re-typing surface on purpose. `highlights`, `services` and
 * `process` all hold a heading plus a list of `{title, description, icon?}`
 * cards, which is why the detector ladder drops every unrecognised card list
 * into `highlights` - and why moving one to the block it actually is costs
 * nothing and invents nothing. Anything outside this set would need a field the
 * source did not give us (a `certifications` logo, a `social-proof` figure),
 * and filling that from a model is exactly what rule 1 forbids.
 */
const RETYPE_FAMILY = {
  highlights: "items",
  services: "items",
  process: "steps",
} as const satisfies Partial<Record<SectionType, string>>;

/**
 * What each member can actually HOLD, from its own entry in the `sectionContent`
 * validator (`convex/model/sections.ts`).
 *
 * This is the guard against the quiet half of a bad conversion. Refusing to
 * INVENT a field is the obvious rule and it is only half of rule 4: moving a
 * band to a type that cannot hold one of its fields would silently DROP that
 * field, and for `items[].media` that means an imported photograph the owner
 * put there disappears from the page and is then reported as never referenced.
 * So a conversion is refused unless the target can hold every key the source
 * band actually carries, and the move copies those keys rather than a
 * hand-picked three.
 *
 * Kept as an explicit list, not derived from the validator: it is the thing a
 * reviewer has to check by eye against the schema, and a derivation would make
 * a schema change silently widen what a model is allowed to move.
 */
const RETYPE_FIELDS: Record<RetypeType, { section: readonly string[]; item: readonly string[] }> = {
  highlights: {
    section: ["type", "heading", "intro", "media", "cta"],
    item: ["title", "description", "icon", "media", "label", "bullets"],
  },
  services: {
    section: ["type", "eyebrow", "heading", "intro", "media"],
    item: ["title", "description", "priceText", "bullets", "icon", "media", "cta", "serviceId"],
  },
  process: {
    section: ["type", "heading", "eyebrow", "footerHeading", "footerCta"],
    item: ["title", "description", "icon"],
  },
};

type RetypeType = keyof typeof RETYPE_FAMILY;

function isRetypeType(type: string): type is RetypeType {
  return Object.prototype.hasOwnProperty.call(RETYPE_FAMILY, type);
}

/** Blocks whose position and purpose are OURS, not the source's. The hero is
 *  the top of the page by definition and its layout is read off a real render;
 *  the contact form and the footer are ones we add. A proposal about the band
 *  they sit in is still consumed - the band belongs to them - but it is not
 *  reported as a rejection, because "the model thinks band 0 is a banner" is
 *  noise on every page rather than evidence of anything. */
const OURS: ReadonlySet<string> = new Set(["hero", "contact", "footer"]);

/** Every key the object actually carries a value under. `undefined` does not
 *  count: the builders spread optional fields conditionally, so a key is only
 *  ever present when it holds something. */
function filledKeys(record: Record<string, unknown>): string[] {
  return Object.keys(record).filter((key) => record[key] !== undefined);
}

function copyKeys(
  record: Record<string, unknown>,
  keys: readonly string[],
): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const key of keys) if (record[key] !== undefined) out[key] = record[key];
  return out;
}

/**
 * Move content from one member of the family to another, or `null` when it
 * cannot be done honestly.
 *
 * Three ways it refuses, and each is a real conversion we could have written
 * and should not:
 *
 *   • **the target cannot hold a field the band carries.** A highlights card
 *     with a picture cannot become a process step, because `process.steps` has
 *     no media slot and the picture would vanish.
 *   • **the target REQUIRES a field the band does not have.**
 *     `highlights.items[].description` and `process.steps[].description` are
 *     required where `services.items[].description` is optional, so a services
 *     band whose cards have no description becomes neither. Writing `""` to
 *     satisfy the validator would be the import inventing an empty paragraph on
 *     every card.
 *   • **the band is not shaped like the family at all** - no array, an empty
 *     one, a card with no title, no heading.
 */
export function retypeContent(
  from: RetypeType,
  to: RetypeType,
  content: unknown,
): Record<string, unknown> | null {
  if (from === to) return null;
  if (typeof content !== "object" || content === null) return null;
  const record = content as Record<string, unknown>;
  const fields = RETYPE_FIELDS[to];
  const cards = record[RETYPE_FAMILY[from]];
  if (!Array.isArray(cards) || cards.length === 0) return null;
  if (typeof record.heading !== "string" || !record.heading) return null;

  // The source array's own name is not a field of the target; every OTHER key
  // the band carries has to have somewhere to land.
  const sectionKeys = filledKeys(record).filter((key) => key !== RETYPE_FAMILY[from]);
  if (sectionKeys.some((key) => !fields.section.includes(key))) return null;

  const needsDescription = to !== "services";
  const moved: Record<string, unknown>[] = [];
  for (const raw of cards) {
    if (typeof raw !== "object" || raw === null) return null;
    const card = raw as Record<string, unknown>;
    if (typeof card.title !== "string" || !card.title) return null;
    if (needsDescription && typeof card.description !== "string") return null;
    if (filledKeys(card).some((key) => !fields.item.includes(key))) return null;
    moved.push(copyKeys(card, fields.item));
  }

  return {
    ...copyKeys(record, fields.section),
    type: to,
    [RETYPE_FAMILY[to]]: moved,
  };
}

/** What a proposal did, or why it did nothing. One row per proposal that
 *  cleared the floor, so a wrong call on a real site is traceable to the thing
 *  that made it - and so the rejected ones say which conversion to build next. */
export type AppliedProposal = {
  band: number;
  from: string;
  to: SectionType;
  variant?: string;
  confidence: number;
  outcome: "retyped" | "variant" | "retyped+variant" | "agreed" | "ours" | "rejected";
  /** Set on `rejected`: why. */
  reason?:
    | "low-confidence"
    | "no-conversion"
    | "content-incompatible"
    | "variant-unfillable"
    /** A detector had already chosen this layout from evidence, so the
     *  proposal's was not applied. Separable from `agreed` on purpose: over a
     *  corpus they are different findings. */
    | "variant-from-evidence";
};

/** The minimum shape `applySectionProposals` needs. Kept structural so
 *  `htmlToSections.ts` does not have to export its private `BuiltSection`. */
export type ProposableSection = {
  type: string;
  content: unknown;
  variant?: string;
  at?: number;
};

/** Fields a section keeps the source's own wording in. Same list, and the same
 *  order, that `bandKeyOf` uses in `htmlToSections.ts` to attribute a measured
 *  band to a section. */
const HEADING_FIELDS = ["heading", "headline", "title", "name"] as const;

function headingOfSection(section: ProposableSection): string | undefined {
  const content = section.content;
  if (!content || typeof content !== "object") return undefined;
  const record = content as Record<string, unknown>;
  for (const field of HEADING_FIELDS) {
    const value = record[field];
    if (typeof value === "string" && value.trim()) return normalizeHeading(value);
  }
  return undefined;
}

function normalizeHeading(value: string): string {
  return value.toLowerCase().replace(/\s+/g, " ").trim();
}

/**
 * Pair each band with the section built from it.
 *
 * Two joins, and the second one is not a nicety. The offset join is the exact
 * one - a section's `at` is the byte where its evidence sat - but only some
 * detectors record it, and a fidelity run over 14 real pages found that **62%
 * of proposals never reached a section at all** because the section they were
 * about carried no offset. A pass that cannot reach the sections it is about is
 * inert, which is what that run measured before this existed.
 *
 * So a section with no offset is matched on the HEADING it carried through from
 * the source, against the band's own heading. That is the same join
 * `bandKeyOf` already uses to attribute a measured band, and it is safe for the
 * same reason: a heading is close to unique on a real page, and a section whose
 * heading we invented ("Kontakta oss" on the form we add) does not match any
 * band's, so it is left alone exactly as before.
 *
 * Offsets win. A heading match never overrides one, and never steals a band an
 * offset already claimed.
 */
function pairBands<T extends ProposableSection>(
  built: readonly T[],
  bands: readonly SectionBand[],
): Map<number, number> {
  /** section index -> band index */
  const pairs = new Map<number, number>();
  const claimed = new Set<number>();

  built.forEach((section, i) => {
    if (section.at === undefined) return;
    let found: SectionBand | undefined;
    for (const band of bands) {
      if (band.at > section.at) break;
      found = band;
    }
    if (!found || claimed.has(found.index)) return;
    claimed.add(found.index);
    pairs.set(i, found.index);
  });

  const byHeading = new Map<string, number>();
  for (const band of bands) {
    if (claimed.has(band.index) || !band.heading) continue;
    const key = normalizeHeading(band.heading);
    // A heading that appears on two bands identifies neither.
    byHeading.set(key, byHeading.has(key) ? -1 : band.index);
  }

  built.forEach((section, i) => {
    if (pairs.has(i)) return;
    const heading = headingOfSection(section);
    if (!heading) return;
    const band = byHeading.get(heading);
    if (band === undefined || band === -1 || claimed.has(band)) return;
    claimed.add(band);
    pairs.set(i, band);
  });

  if (process.env.SAJT_PAIR_DEBUG) {
    console.error(`PAIRDBG bands=${bands.length} sections=${built.length} withAt=${built.filter((b) => b.at !== undefined).length} paired=${pairs.size} types=${built.map((b) => b.type + (b.at === undefined ? '' : '@')).join(',')} bandHeads=${bands.map((b) => b.heading.slice(0,18)).join('|')}`);
  }
  return pairs;
}

/**
 * Apply the proposals to a page's built sections.
 *
 * Returns a NEW array; the input is never mutated. Two things can change and
 * nothing else:
 *
 *   • the layout, but only where the deterministic pass left it to the type's
 *     default. A variant a detector chose came from evidence (a measured hero
 *     layout, a counted repeat, a real `<tabs>` widget) and a model must not
 *     argue with a measurement.
 *   • the type, but only inside `RETYPE_FAMILY` and only when
 *     `retypeContent` can move every card without inventing a field.
 *
 * Everything else - the hero, the footer, the contact form, every band whose
 * content model the proposal cannot express - is returned exactly as it came in.
 */
export function applySectionProposals<T extends ProposableSection>(
  built: readonly T[],
  proposals: ReadonlyMap<number, SectionProposal>,
  bands: readonly SectionBand[],
): { sections: T[]; applied: AppliedProposal[] } {
  const applied: AppliedProposal[] = [];
  if (proposals.size === 0) return { sections: [...built], applied };

  // One band, one section - `pairBands` enforces it, so two detectors that both
  // fired inside one band (a gallery and its caption, say) cannot both be
  // re-typed by a single label.
  const pairs = pairBands(built, bands);
  const byIndex = new Map(bands.map((b) => [b.index, b]));

  const sections = built.map((section, i) => {
    const bandIndex = pairs.get(i);
    const band = bandIndex === undefined ? undefined : byIndex.get(bandIndex);
    if (!band) return section;
    const proposal = proposals.get(band.index);
    if (!proposal) return section;
    if (OURS.has(section.type)) {
      // Recorded rather than dropped. It is noise when you are reading a single
      // import's report, and it is the only way to tell "the pass never reached
      // this band" from "it reached it and had nothing to do" when you are
      // measuring the pass over a corpus - a distinction a first fidelity run
      // got wrong in exactly this spot.
      applied.push({
        band: band.index,
        from: section.type,
        to: proposal.sectionType,
        confidence: proposal.confidence,
        outcome: "ours",
      });
      return section;
    }

    if (proposal.confidence < PROPOSAL_CONFIDENCE_FLOOR) {
      applied.push({
        band: band.index,
        from: section.type,
        to: proposal.sectionType,
        confidence: proposal.confidence,
        outcome: "rejected",
        reason: "low-confidence",
      });
      return section;
    }

    let next: T = section;
    let retyped = false;

    if (proposal.sectionType !== section.type) {
      if (!isRetypeType(section.type) || !isRetypeType(proposal.sectionType)) {
        applied.push({
          band: band.index,
          from: section.type,
          to: proposal.sectionType,
          confidence: proposal.confidence,
          outcome: "rejected",
          reason: "no-conversion",
        });
        return section;
      }
      const content = retypeContent(section.type, proposal.sectionType, section.content);
      if (!content) {
        applied.push({
          band: band.index,
          from: section.type,
          to: proposal.sectionType,
          confidence: proposal.confidence,
          outcome: "rejected",
          reason: "content-incompatible",
        });
        return section;
      }
      // A layout the OLD type had is meaningless on the new one, so it goes
      // with the type. The proposal's own key, or the new type's default, then
      // decides - never a stale key from the block this used to be.
      const rest = { ...next } as Record<string, unknown>;
      delete rest.variant;
      next = { ...rest, type: proposal.sectionType, content } as unknown as T;
      retyped = true;
    }

    let variantSet = false;
    if (proposal.variantKey && next.variant !== undefined && !retyped) {
      applied.push({
        band: band.index,
        from: section.type,
        to: proposal.sectionType,
        variant: proposal.variantKey,
        confidence: proposal.confidence,
        outcome: "rejected",
        reason: "variant-from-evidence",
      });
      return section;
    }
    if (proposal.variantKey && next.variant === undefined) {
      // A layout that needs a field or a third card the band does not have
      // would render an empty column. `missingForVariant` is the same check the
      // editor's layout picker runs, so a proposal can only reach a layout an
      // owner could have picked by hand.
      const gap = missingForVariant(next.type, proposal.variantKey, next.content);
      if (isGapEmpty(gap)) {
        next = { ...next, variant: proposal.variantKey } as T;
        variantSet = true;
      } else if (!retyped) {
        applied.push({
          band: band.index,
          from: section.type,
          to: proposal.sectionType,
          variant: proposal.variantKey,
          confidence: proposal.confidence,
          outcome: "rejected",
          reason: "variant-unfillable",
        });
        return section;
      }
    }

    if (!retyped && !variantSet) {
      applied.push({
        band: band.index,
        from: section.type,
        to: proposal.sectionType,
        confidence: proposal.confidence,
        outcome: "agreed",
      });
      return section;
    }
    applied.push({
      band: band.index,
      from: section.type,
      to: proposal.sectionType,
      ...(variantSet ? { variant: proposal.variantKey } : {}),
      confidence: proposal.confidence,
      outcome: retyped && variantSet ? "retyped+variant" : retyped ? "retyped" : "variant",
    });
    return next;
  });

  return { sections, applied };
}
