// GENERATED by scripts/mirror-import.ts from HH-Studio/simple-site-builder:lib/import/structureDetect.ts
// Do not edit. Run `bun scripts/mirror-import.ts --sync-from-app <appRoot>`.

import { decodeHtmlEntities } from "../html/entities";
import {
  DOCUMENT_EXTENSIONS,
  stripDocumentExtension,
} from "../uploads/documentTypes";
import { attributeValue } from "../html/attributes";
import { safeDecodeURIComponent } from "../net/url";
import {
  ILLUSTRATION_LIMITS,
  safePathData,
  safeStrokeWidth,
  safeViewBox,
} from "../../../lib/sections/illustration";

// ---------------------------------------------------------------------------
// Structural detectors for the website import (backlog 1725 item 10).
//
// The measurement boundary decides how an imported page LOOKS; the section
// vocabulary decides what it IS, and the vocabulary is the bigger remaining
// accuracy lever. `htmlToSections.ts` already detects twenty section types;
// this module adds the next nine, kept out of that file because it is 2 000
// lines already and each detector here is independently testable.
//
// One rule, inherited from every detector that came before: **gated on real
// structure, never on a keyword alone, and no section emitted rather than a
// wrong one.** A heading that says "Dokument" over no downloadable file, an
// Instagram band with no pictures, or a comparison table built from a layout
// grid are all worse than the section simply not existing — the owner can add
// what we missed, but cannot tell that what we invented is wrong without
// checking the source themselves.
//
// Pure + regex-only (same constraint as `htmlToSections.ts`) so every detector
// runs inside a Convex action and unit-tests without a DOM.
// ---------------------------------------------------------------------------

function decode(s: string): string {
  return decodeHtmlEntities(s).trim();
}

function text(s: string): string {
  return decode(s.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim());
}

/** Absolute URL from a possibly-relative href, or null when it is neither. */
function absolute(href: string, baseUrl: string): string | null {
  try {
    const u = new URL(href, baseUrl);
    return u.protocol === "http:" || u.protocol === "https:" ? u.toString() : null;
  } catch {
    return null;
  }
}

/** The `<body>` of the document, or the whole string when there is no body tag
 *  (a fragment, a paste). Detectors that must not read chrome start here. */
export function bodyOf(html: string): { html: string; offset: number } {
  const m = html.match(/<body\b[^>]*>([\s\S]*)<\/body>/i);
  if (!m) return { html, offset: 0 };
  return { html: m[1], offset: (m.index ?? 0) + m[0].indexOf(m[1]) };
}

/** Header/nav/footer runs, as [start, end) offsets into `html`. A link inside
 *  one of these is site chrome: the same PDF linked from every page's footer is
 *  not that page's document list. */
function chromeRanges(html: string): Array<[number, number]> {
  const out: Array<[number, number]> = [];
  for (const tag of ["header", "nav", "footer"] as const) {
    const re = new RegExp(`<${tag}\\b[^>]*>[\\s\\S]*?<\\/${tag}>`, "gi");
    for (const m of html.matchAll(re)) {
      const at = m.index ?? 0;
      out.push([at, at + m[0].length]);
    }
  }
  return out;
}

function inChrome(at: number, ranges: ReadonlyArray<[number, number]>): boolean {
  return ranges.some(([start, end]) => at >= start && at < end);
}

// --- documents -------------------------------------------------------------

/** Only the extensions the commit path will actually keep. The section's asset
 *  kind is `document`, and `convex/portability.ts` byte-sniffs every one of
 *  them (lib/uploads/documentSniff.ts) — so offering .xlsx or .pptx here would
 *  build items whose file is guaranteed to be dropped, which is the "title with
 *  nothing to download" this detector exists to avoid. */
const DOCUMENT_HREF = new RegExp(
  `(?:${DOCUMENT_EXTENSIONS.map((ext) => ext.replace(".", "\\.")).join("|")})(?:$|[?#])`,
  "i",
);

const DOCUMENTS_HEADING =
  /\b(dokument|blanketter|nedladdning|ladda\s+ner|filer|prislist|villkor|broschyr|downloads?|documents?|forms?|brochures?|price\s*list)\b/i;

export type DetectedDocuments = {
  at: number;
  heading?: string;
  items: Array<{ title: string; url: string }>;
};

/**
 * Downloadable files the page links to.
 *
 * Two ways in, because a real site publishes files two ways: a labelled block
 * ("Blanketter", one file under it is a genuine list of one), or an unlabelled
 * run of at least two file links, which is a download list whatever it is
 * called. A single unlabelled file is left alone — it is usually one inline
 * link inside prose ("see our terms"), and lifting it into its own band both
 * loses the sentence and invents a section.
 *
 * Chrome is excluded: the terms PDF in a footer belongs to every page, so it
 * would otherwise arrive as a "Dokument" band at the bottom of all of them.
 */
export function detectDocuments(html: string, baseUrl: string): DetectedDocuments | null {
  const chrome = chromeRanges(html);
  const seen = new Set<string>();
  const links: Array<{ title: string; url: string; at: number }> = [];
  for (const m of html.matchAll(/<a\b([^>]*)>([\s\S]*?)<\/a>/gi)) {
    const at = m.index ?? 0;
    if (inChrome(at, chrome)) continue;
    const href = m[1].match(/\bhref=["']([^"']+)["']/i)?.[1];
    if (!href || !DOCUMENT_HREF.test(href)) continue;
    const url = absolute(decode(href), baseUrl);
    if (!url || seen.has(url)) continue;
    // The link's own words, then its title attribute, then the file name. A
    // link with none of the three ("Ladda ner" alone is fine, an icon-only
    // link is not) is skipped rather than titled with the file's hash.
    const label =
      text(m[2]) ||
      (attributeValue(m[1], "title") ?? "") ||
      titleFromFilename(url);
    if (label.length < 2 || label.length > 120) continue;
    seen.add(url);
    links.push({ title: label.slice(0, 120), url, at });
  }
  if (links.length === 0) return null;

  const heading = headingAbove(html, links[0].at, DOCUMENTS_HEADING);
  // A labelled block takes one; an unlabelled run needs two to be a list.
  if (!heading && links.length < 2) return null;
  return {
    at: heading?.at ?? links[0].at,
    ...(heading ? { heading: heading.text } : {}),
    items: links.slice(0, 12).map(({ title, url }) => ({ title, url })),
  };
}

/** "arsredovisning-2024.pdf" → "Arsredovisning 2024". Only ever a fallback. */
function titleFromFilename(url: string): string {
  const base = stripDocumentExtension(
    url.split("?")[0].split("#")[0].split("/").pop() ?? "",
  )
    .replace(/[-_]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
  if (!/[a-zA-ZåäöÅÄÖ]{2}/.test(base)) return "";
  return base.charAt(0).toUpperCase() + base.slice(1);
}

/** How far above a block its label may sit. Same reasoning as the newsletter
 *  detector's reach: without a distance gate the "nearest preceding heading"
 *  is whatever the page last said, which put "Vanliga frågor" on a footer
 *  signup box. */
const HEADING_REACH = 1200;

/** The nearest h2/h3/h4 above `at` that `test` accepts, within reach. */
function headingAbove(
  html: string,
  at: number,
  test: RegExp,
): { text: string; at: number } | null {
  const found = [...html.matchAll(/<h([234])[^>]*>([\s\S]*?)<\/h\1>/gi)]
    .map((m) => ({ text: text(m[2]), at: m.index ?? 0 }))
    .filter(
      (h) =>
        h.text.length > 1 &&
        h.text.length <= 80 &&
        h.at < at &&
        at - h.at <= HEADING_REACH &&
        test.test(h.text),
    )
    .pop();
  return found ?? null;
}

/** The nearest h2/h3/h4 above `at` within reach, whatever it says. */
function anyHeadingAbove(html: string, at: number): { text: string; at: number } | null {
  return headingAbove(html, at, /./);
}

// --- banner ----------------------------------------------------------------

/** The announcement strip's own markup. `role="alert"` is the accessible form;
 *  the class names are what the three builders that ship one actually emit
 *  (Shopify `announcement-bar`, Webflow/Squarespace `promo|topbar`, WordPress
 *  theme `notice-bar`). Deliberately anchored to the class TOKEN, so a
 *  "banner-image" hero does not become a promo strip. */
const BANNER_ATTR =
  /\brole=["']alert["']|\b(?:class|id)=["'][^"']*\b(?:announcement(?:-bar)?|promo-?bar|top-?bar|notice-?bar|alert-?bar)\b/i;

export type DetectedBanner = { at: number; text: string; ctaUrl?: string; ctaLabel?: string };

/**
 * The single-line promo strip at the top of a page.
 *
 * Gated on the element's own role/class rather than on its position, because
 * "the first div in the body" is the header on most sites. Length is the
 * second gate: the strip is one sentence. Anything longer is a hero or a
 * cookie notice that happened to carry `role="alert"`, and neither is a
 * banner. A cookie/consent bar is excluded outright — we are not importing
 * somebody else's consent UI onto a site that has its own.
 */
export const CONSENT_TEXT =
  /\b(cookies?|kakor|samtycke|consent|gdpr|integritetspolicy|privacy\s+policy)\b/i;

export function detectBanner(html: string, baseUrl: string): DetectedBanner | null {
  const { html: body, offset } = bodyOf(html);
  for (const block of balancedBlocks(body, "div|section|aside|p")) {
    if (!BANNER_ATTR.test(block.attrs)) continue;
    const inner = block.inner;
    const line = text(inner);
    if (line.length < 8 || line.length > 160) continue;
    if (CONSENT_TEXT.test(line)) continue;
    const link = inner.match(/<a\b([^>]*)>([\s\S]*?)<\/a>/i);
    const href = link?.[1].match(/\bhref=["']([^"']+)["']/i)?.[1];
    const ctaUrl = href ? absolute(decode(href), baseUrl) : null;
    const ctaLabel = link ? text(link[2]) : "";
    return {
      at: offset + block.at,
      // The link's words are part of the strip's sentence; keeping them in
      // both the text and the button label says everything twice.
      text: (ctaLabel && line.endsWith(ctaLabel)
        ? line.slice(0, line.length - ctaLabel.length).trim()
        : line
      ).slice(0, 200),
      ...(ctaUrl && ctaLabel.length >= 2 && ctaLabel.length <= 40
        ? { ctaUrl, ctaLabel: ctaLabel.slice(0, 40) }
        : {}),
    };
  }
  return null;
}

// --- instagram -------------------------------------------------------------

const INSTAGRAM_BLOCK = /\b(?:class|id)=["'][^"']*\b(?:instagram|insta-?feed|ig-?feed|sb_instagram)\b/i;
/** The closing boundary has to include the quote that ends the attribute: with
 *  only `[/?#]|$`, `href="https://instagram.com/nordvikbygg"` matched nothing,
 *  because `$` is the end of the whole document and every real handle in a
 *  page is followed by a quote. */
const INSTAGRAM_HANDLE = /instagram\.com\/([A-Za-z0-9._]{1,30})(?:["'\s/?#]|$)/i;
/** Instagram's own URL namespace, not somebody's handle. */
const INSTAGRAM_RESERVED = /^(?:p|reel|reels|tv|explore|accounts|stories|share)$/i;

export type DetectedInstagram = { at: number; handle?: string; imageUrls: string[] };

/**
 * The source's Instagram feed band.
 *
 * A feed widget renders as a block of thumbnails, so the gate is that block
 * plus at least three pictures inside it. The handle alone is NOT enough: an
 * Instagram icon in the footer is a social link, which the import already
 * carries as one, and turning it into a full band would put an empty grid on
 * the page.
 *
 * The pictures are the ones the widget had cached in its markup at the moment
 * we fetched. That is the honest thing to carry — the section stores images
 * "cached at publish; no live API in render", so an imported feed is a
 * snapshot of a feed, and the owner replaces it when it goes stale.
 */
export function detectInstagram(html: string, baseUrl: string): DetectedInstagram | null {
  const { html: body, offset } = bodyOf(html);
  for (const block of balancedBlocks(body, "div|section|ul|aside")) {
    if (!INSTAGRAM_BLOCK.test(block.attrs)) continue;
    const inner = block.inner;
    const urls: string[] = [];
    for (const img of inner.matchAll(/<img\b([^>]*)>/gi)) {
      const src =
        img[1].match(/\bsrc=["']([^"']+)["']/i)?.[1] ??
        img[1].match(/\bdata-src=["']([^"']+)["']/i)?.[1];
      if (!src || /^data:/i.test(src)) continue;
      const url = absolute(decode(src), baseUrl);
      if (url && !urls.includes(url)) urls.push(url);
      if (urls.length >= 9) break;
    }
    if (urls.length < 3) continue;
    const handleMatch = inner.match(INSTAGRAM_HANDLE) ?? html.match(INSTAGRAM_HANDLE);
    const handle =
      handleMatch && !INSTAGRAM_RESERVED.test(handleMatch[1]) ? handleMatch[1] : undefined;
    return {
      at: offset + block.at,
      ...(handle ? { handle } : {}),
      imageUrls: urls,
    };
  }
  return null;
}

// --- booking ---------------------------------------------------------------

/** Booking engines a Swedish small business actually uses, plus the
 *  international ones. Matched on HOST, never on a word in the copy: "boka tid"
 *  in a sentence is an intention, a link to bokadirekt.se is a booking system. */
const BOOKING_HOSTS =
  /(?:^|\.)(?:bokadirekt\.se|boka\.se|timecenter\.se|bokamera\.se|easypractice\.net|calendly\.com|cal\.com|setmore\.com|acuityscheduling\.com|app\.acuityscheduling\.com|simplybook\.(?:me|it)|squareup\.com|fresha\.com|treatwell\.se|bokadirekt\.com)$/i;

export type DetectedBooking = { at: number; url: string; ctaLabel?: string; heading?: string };

/**
 * A third-party booking system the source linked to or embedded.
 *
 * Carried as `{ kind: "provider", url }` — the URL only. The renderer derives
 * the provider and builds the frame or the button, exactly as it does for a
 * link the owner pastes by hand. The source's own `<iframe>`/`<script>` widget
 * is never stored: "external source code is evidence, never runtime" (owner
 * directive, roadmap §19) and the `embed` source kind exists for a snippet the
 * OWNER chose, not one we lifted off a stranger's page.
 */
export function detectBooking(html: string, baseUrl: string): DetectedBooking | null {
  const hostOf = (raw: string): string | null => {
    const url = absolute(decode(raw), baseUrl);
    if (!url) return null;
    try {
      return BOOKING_HOSTS.test(new URL(url).hostname) ? url : null;
    } catch {
      return null;
    }
  };
  // An embedded widget first: a site that frames its calendar means the
  // booking to happen on the page, so the imported band should too.
  for (const m of html.matchAll(/<iframe\b([^>]*)>/gi)) {
    const src = m[1].match(/\bsrc=["']([^"']+)["']/i)?.[1];
    const url = src ? hostOf(src) : null;
    if (!url) continue;
    const at = m.index ?? 0;
    const heading = anyHeadingAbove(html, at);
    return { at, url, ...(heading ? { heading: heading.text } : {}) };
  }
  for (const m of html.matchAll(/<a\b([^>]*)>([\s\S]*?)<\/a>/gi)) {
    const href = m[1].match(/\bhref=["']([^"']+)["']/i)?.[1];
    const url = href ? hostOf(href) : null;
    if (!url) continue;
    const at = m.index ?? 0;
    const label = text(m[2]);
    const heading = anyHeadingAbove(html, at);
    return {
      at,
      url,
      ...(label.length >= 2 && label.length <= 40 ? { ctaLabel: label } : {}),
      ...(heading ? { heading: heading.text } : {}),
    };
  }
  return null;
}

// --- comparison ------------------------------------------------------------

export type DetectedComparison = {
  at: number;
  heading?: string;
  columns: string[];
  rows: Array<{ label: string; cells: string[] }>;
};

/** A cell's text, with the tick/cross marks builders draw as icons resolved to
 *  the characters the section stores. An icon-only cell would otherwise arrive
 *  empty and the row would read as "not included" for every column. */
function cellText(cellHtml: string): string {
  const plain = text(cellHtml);
  if (plain) return plain.slice(0, 80);
  if (/\b(?:check|tick|yes|included|fa-check|icon-check)\b/i.test(cellHtml)) return "✓";
  if (/\b(?:cross|times|close|no|excluded|fa-times|icon-close)\b/i.test(cellHtml)) return "–";
  return "";
}

/**
 * A real comparison table.
 *
 * Gated on `<table>` with a genuine header row, because the alternative — a
 * CSS grid that LOOKS like a table — cannot be told apart from a pricing grid,
 * a services grid or a footer's link columns without computed styles, and each
 * of those already has a better home. A table with one data column is a
 * definition list, not a comparison.
 *
 * The first header cell is the row-label column and is dropped from `columns`:
 * it is usually empty or says "Funktion", and the section renders row labels
 * from `rows[].label` already.
 */
export function detectComparison(html: string): DetectedComparison | null {
  for (const table of html.matchAll(/<table\b[^>]*>([\s\S]*?)<\/table>/gi)) {
    const inner = table[1];
    const rows = [...inner.matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi)].map((r) => r[1]);
    if (rows.length < 3) continue; // a header plus at least two rows
    const cellsOf = (row: string) =>
      [...row.matchAll(/<(t[hd])\b[^>]*>([\s\S]*?)<\/\1>/gi)].map((c) => ({
        header: c[1].toLowerCase() === "th",
        html: c[2],
      }));
    const head = cellsOf(rows[0]);
    // The header row must actually be marked up as one. Without this every
    // opening-hours and price table on the web became a comparison.
    if (head.length < 3 || !head.slice(1).every((c) => c.header)) continue;
    const columns = head.slice(1).map((c) => text(c.html).slice(0, 60));
    if (columns.some((c) => c.length === 0)) continue;
    const body: Array<{ label: string; cells: string[] }> = [];
    for (const row of rows.slice(1)) {
      const cells = cellsOf(row);
      if (cells.length !== head.length) continue; // a spanning row is a group title
      const label = text(cells[0].html).slice(0, 80);
      if (!label) continue;
      body.push({ label, cells: cells.slice(1).map((c) => cellText(c.html)) });
      if (body.length >= 12) break;
    }
    if (body.length < 2) continue;
    const at = table.index ?? 0;
    const heading = anyHeadingAbove(html, at);
    return {
      at,
      ...(heading ? { heading: heading.text } : {}),
      columns,
      rows: body,
    };
  }
  return null;
}

// --- bento (portfolio / case grid) -----------------------------------------

const PORTFOLIO_HEADING =
  /\b(portfolio|portf(?:ö|o)lj|projekt|referenser|case[ s]|arbeten|v(?:å|a)ra\s+jobb|our\s+work|projects?|recent\s+work|selected\s+work)\b/i;

export type DetectedBento = {
  at: number;
  heading: string;
  cells: Array<{ title: string; description?: string; imageUrl?: string }>;
};

/**
 * The work grid: projects, cases, references — a picture and a name each.
 *
 * `bento` rather than `gallery` because these cells are NAMED: a gallery is
 * photographs, and dropping the project titles is exactly the fidelity loss
 * this item exists to close. Gated on a portfolio-shaped heading AND at least
 * three titled items with a picture, so an ordinary photo grid stays a gallery
 * and a titled list with no pictures stays highlights.
 */
export function detectBento(html: string, baseUrl: string): DetectedBento | null {
  const blocks = [...html.matchAll(/<h2[^>]*>([\s\S]*?)<\/h2>([\s\S]*?)(?=<h2[\s>]|$)/gi)];
  for (const block of blocks) {
    const heading = text(block[1]);
    if (heading.length < 2 || heading.length > 80 || !PORTFOLIO_HEADING.test(heading)) continue;
    const cells: DetectedBento["cells"] = [];
    // Every picture in the block, with where it sat, so a title can be joined
    // to the NEAREST one.
    //
    // Neither direction alone works, and picking the wrong one is silent. A
    // card whose caption sits under its picture puts the image BEFORE the
    // title; a card that captions above puts it after. Reading only the markup
    // after the title gave every cell the NEXT cell's photo, because a title's
    // tail runs to the next heading and the next cell's image sits inside it.
    const artwork = [...block[2].matchAll(/<img\b[^>]*\bsrc=["']([^"']+)["']/gi)]
      .map((m) => ({ src: m[1], at: m.index ?? 0 }))
      .filter((a) => !/^data:/i.test(a.src));
    const usedArt = new Set<number>();
    // Each cell is a small heading plus the markup that follows it, the same
    // shape `repeatedItemsUnder` reads for services and team.
    for (const item of block[2].matchAll(
      /<(h[345])[^>]*>([\s\S]*?)<\/\1>([\s\S]*?)(?=<h[1-5][\s>]|$)/gi,
    )) {
      const title = text(item[2]);
      if (title.length < 2 || title.length > 80) continue;
      const rest = item[3];
      const titleAt = item.index ?? 0;
      // Nearest unclaimed picture in either direction. Claiming it stops two
      // cards from rendering the same photo when one of them has none.
      const nearest = artwork
        .filter((a) => !usedArt.has(a.at))
        .sort((a, b) => Math.abs(a.at - titleAt) - Math.abs(b.at - titleAt))[0];
      if (nearest) usedArt.add(nearest.at);
      const src = nearest?.src;
      const imageUrl = src ? absolute(decode(src), baseUrl) : null;
      const description = text(
        (rest.match(/<p\b[^>]*>([\s\S]*?)<\/p>/i) ?? [, ""])[1] ?? "",
      ).slice(0, 240);
      cells.push({
        title: title.slice(0, 80),
        ...(description.length >= 20 ? { description } : {}),
        ...(imageUrl ? { imageUrl } : {}),
      });
      if (cells.length >= 9) break;
    }
    const withArt = cells.filter((c) => c.imageUrl);
    if (cells.length < 3 || withArt.length < 3) continue;
    return { at: block.index ?? 0, heading: heading.slice(0, 80), cells };
  }
  return null;
}

// --- legal -----------------------------------------------------------------

const LEGAL_TITLE =
  /\b(integritetspolicy|personuppgiftspolicy|cookiepolicy|cookie-?policy|k(?:ö|o)pvillkor|allm(?:ä|a)nna\s+villkor|anv(?:ä|a)ndarvillkor|villkor|gdpr|privacy\s+policy|terms\s+(?:of\s+(?:service|use)|and\s+conditions)|cookie\s+notice|legal\s+notice|imprint)\b/i;

export type DetectedLegal = { heading: string; blocks: LegalBlock[] };
export type LegalBlock =
  | { kind: "h"; level?: 2 | 3; text: string }
  | { kind: "p"; text: string }
  | { kind: "ul"; items: string[] };

/**
 * A whole policy PAGE, kept as structured prose.
 *
 * Page-level on purpose: a privacy policy is not a band inside a marketing
 * page, it is a page whose entire body is one long document, and running the
 * ordinary detectors over it produced a "Det vi gör" highlights grid built
 * from its section headings. Emitted only when the page's own title says what
 * it is AND the body carries enough prose to be a policy rather than a link to
 * one.
 *
 * Blocks, never raw HTML — the constrained content model holds. Anything that
 * is not a heading, paragraph or list (a table of sub-processors, an embedded
 * consent widget) is dropped rather than flattened into a paragraph that reads
 * as our own sentence.
 */
export function detectLegal(html: string, pageTitle?: string): DetectedLegal | null {
  const h1 = text(html.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)?.[1] ?? "");
  const docTitle = text(html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1] ?? "");
  const heading = [h1, pageTitle ?? "", docTitle].find(
    (candidate) => candidate.length > 2 && candidate.length <= 120 && LEGAL_TITLE.test(candidate),
  );
  if (!heading) return null;

  const { html: body } = bodyOf(html);
  // Chrome carries the page's menu and the site-wide footer; a policy's own
  // prose is everything else.
  const main = body.match(/<main\b[^>]*>([\s\S]*)<\/main>/i)?.[1] ?? stripChrome(body);
  const blocks: LegalBlock[] = [];
  let prose = 0;
  for (const m of main.matchAll(/<(h2|h3|p|ul|ol)\b[^>]*>([\s\S]*?)<\/\1>/gi)) {
    const tag = m[1].toLowerCase();
    if (tag === "ul" || tag === "ol") {
      const items = [...m[2].matchAll(/<li\b[^>]*>([\s\S]*?)<\/li>/gi)]
        .map((li) => text(li[1]))
        .filter((t) => t.length > 0 && t.length <= 500)
        .slice(0, 40);
      if (items.length > 0) {
        blocks.push({ kind: "ul", items });
        prose += items.join(" ").length;
      }
      continue;
    }
    const value = text(m[2]);
    if (!value) continue;
    if (tag === "p") {
      if (value.length > 2000) continue;
      blocks.push({ kind: "p", text: value });
      prose += value.length;
    } else if (value.length <= 120) {
      blocks.push({ kind: "h", level: tag === "h2" ? 2 : 3, text: value });
    }
    if (blocks.length >= 120) break;
  }
  // A page that merely LINKS to its policy has a title and almost no prose.
  if (prose < 400) return null;
  // Trailing headings with nothing under them are the footer's leftovers.
  while (blocks.length > 0 && blocks[blocks.length - 1].kind === "h") blocks.pop();
  return blocks.length > 0 ? { heading: heading.slice(0, 120), blocks } : null;
}

function stripChrome(html: string): string {
  return html
    .replace(/<header\b[^>]*>[\s\S]*?<\/header>/gi, " ")
    .replace(/<nav\b[^>]*>[\s\S]*?<\/nav>/gi, " ")
    .replace(/<footer\b[^>]*>[\s\S]*?<\/footer>/gi, " ");
}

// --- social-proof (stats) --------------------------------------------------

/** The figure itself: "500+", "25", "98 %", "4,8", "12 000". A bare year
 *  ("2019") is excluded — a founding date under a label is prose, and every
 *  copyright line in a footer would otherwise count as a statistic. */
const STAT_VALUE = /^(?:\+?\d[\d\s.,]{0,9}(?:\s?(?:%|\+|k|K|M|år|years?|st|kr|SEK))?|\d+[.,]\d+)$/;

export type DetectedSocialProof = {
  at: number;
  heading?: string;
  stats: Array<{ value: string; label: string }>;
};

/**
 * The counters band — "500+ nöjda kunder · 25 år i branschen · 4,8 i betyg".
 *
 * Read as PAIRS of adjacent inline elements: a short numeric token and the
 * short words beside it. Two structural gates keep prose out: the value has to
 * parse as a figure, and there have to be at least three pairs, because two
 * numbers next to each other on a page is a price and a phone number as often
 * as it is a statistic.
 *
 * Nothing is computed. The value is the source's own string, kept verbatim
 * including its "+" — a figure this software derived would be the software
 * making a claim about someone's business.
 */
export function detectSocialProof(html: string): DetectedSocialProof | null {
  const { html: body, offset } = bodyOf(html);
  const clean = stripChrome(body);
  const stats: Array<{ value: string; label: string }> = [];
  let at: number | null = null;
  // A stat is two sibling leaf elements inside one wrapper. Matching the pair
  // directly (rather than every element and then pairing) is what keeps a
  // heading followed by a paragraph from counting.
  for (const m of clean.matchAll(
    /<(div|li|dl)\b[^>]*>\s*(?:<(?:dt|div|span|p|h[2-6])\b[^>]*>\s*)?<(span|strong|b|p|div|h[2-6]|dt)\b[^>]*>([^<]{1,12})<\/\2>\s*<(span|small|p|div|dd|h[2-6])\b[^>]*>([^<]{2,60})<\/\4>/gi,
  )) {
    const value = decode(m[3]);
    const label = decode(m[5]);
    if (!STAT_VALUE.test(value)) continue;
    if (!/[a-zA-ZåäöÅÄÖ]{2}/.test(label)) continue;
    if (at === null) at = offset + (m.index ?? 0);
    stats.push({ value: value.slice(0, 20), label: label.slice(0, 60) });
    if (stats.length >= 6) break;
  }
  if (stats.length < 3 || at === null) return null;
  const heading = anyHeadingAbove(clean, at - offset);
  return { at, ...(heading ? { heading: heading.text } : {}), stats };
}

// --- image (a standalone figure) -------------------------------------------

export type DetectedImage = { at: number; url: string; caption?: string; alt?: string };

/**
 * A `<figure>` with a caption: one picture the page deliberately gave words to.
 *
 * The gate is the caption, not the picture. Every other loose image on a page
 * is already handled — hero, about, gallery, logos — and the ones that fall
 * through are decoration; promoting one of those to its own band would put a
 * spacer graphic in the middle of the owner's page. A `<figcaption>` is the
 * source saying this one matters.
 *
 * Returns every captioned figure so the caller can skip the ones another
 * section already claimed.
 */
export function detectCaptionedImages(html: string, baseUrl: string): DetectedImage[] {
  const { html: body, offset } = bodyOf(html);
  const out: DetectedImage[] = [];
  for (const m of body.matchAll(/<figure\b[^>]*>([\s\S]*?)<\/figure>/gi)) {
    const inner = m[1];
    const caption = text(inner.match(/<figcaption\b[^>]*>([\s\S]*?)<\/figcaption>/i)?.[1] ?? "");
    if (caption.length < 2 || caption.length > 240) continue;
    const img = inner.match(/<img\b([^>]*)>/i);
    if (!img) continue;
    const src = img[1].match(/\bsrc=["']([^"']+)["']/i)?.[1];
    if (!src || /^data:/i.test(src)) continue;
    const url = absolute(decode(src), baseUrl);
    if (!url) continue;
    const alt = attributeValue(img[1], "alt") ?? "";
    out.push({
      at: offset + (m.index ?? 0),
      url,
      caption: caption.slice(0, 240),
      ...(alt ? { alt: alt.slice(0, 200) } : {}),
    });
    if (out.length >= 6) break;
  }
  return out;
}

// --- before/after ----------------------------------------------------------

/** The two labels, in the languages a Swedish small-business site writes them.
 *
 *  Word-bounded on purpose, and the boundary does real work here: `\befter\b`
 *  refuses `eftermiddag` and `efterfrågan`, and `\bföre\b` refuses `företag` —
 *  the single most common word on a Swedish business page, and the one that
 *  would otherwise label half of every site "before". */
const BEFORE_WORD = /\b(?:före|innan|before|förr)\b/i;
// NOT "nu". "Boka nu" is on half the buttons on a Swedish small-business page,
// so it would label whichever picture happened to sit near one.
const AFTER_WORD = /\b(?:efter|efteråt|after|resultat|result)\b/i;
/** The same two, as the class/id tokens a builder emits (`ba__before`,
 *  `is-after`, `img_efter`). Kept apart from the prose test because `_` IS a
 *  word character, so `\bbefore\b` does not match inside `ba__before` — the
 *  class name every builder actually writes. `classTokens` normalises the
 *  separators away first, which is what makes a word boundary usable here. */
const BEFORE_TOKEN = /\b(?:before|foere|fore|innan)\b/i;
const AFTER_TOKEN = /\b(?:after|efter)\b/i;
const classTokens = (attrs: string): string =>
  (attrs.match(/\b(?:class|id)=["']([^"']*)["']/i)?.[1] ?? "").replace(/[^a-z0-9]+/gi, " ");

export type DetectedBeforeAfter = {
  at: number;
  heading?: string;
  pairs: Array<{ beforeUrl: string; afterUrl: string; label?: string }>;
};

/**
 * The "Före / Efter" pair — two photographs of the same thing, captioned as a
 * transformation. A tandläkare, a salong, a städfirma and a fönsterputsare all
 * have one, and until now the import took both pictures into the gallery pool
 * and threw the relationship away, which is the whole content.
 *
 * Gated on structure AND labels together, because neither is enough alone:
 *
 * - **Exactly two pictures in the block.** One is a photo; three or more is a
 *   gallery. This is what keeps the detector off the case it would otherwise
 *   ruin — a portfolio grid whose captions happen to mention "efter".
 * - **One labelled before and the other after.** The label may sit in the
 *   image's own `alt`/`title`, in its `class`/`id`, or in the text beside it
 *   inside the block. A keyword alone never fires: the word must land on a
 *   picture, and the OTHER picture must carry the opposite word. Two images
 *   both captioned "Efter" is a gallery with a repeated caption, not a pair.
 * - **Order is read, not assumed.** A source that puts the after shot first
 *   (common — it is the better photo) is stored the right way round rather
 *   than backwards, which would be worse than not detecting it.
 *
 * Returns every pair it finds so one band can carry a whole series, and the
 * caller owns the URLs: a before/after photo must never also be offered to the
 * hero or the gallery, which is the ordering trap every picture-owning
 * detector in this file is wired around.
 */
export function detectBeforeAfter(html: string, baseUrl: string): DetectedBeforeAfter | null {
  const { html: body, offset } = bodyOf(html);
  const chrome = chromeRanges(body);
  const pairs: DetectedBeforeAfter["pairs"] = [];
  const seen = new Set<string>();
  let at: number | null = null;

  for (const block of balancedBlocks(body)) {
    if (inChrome(block.at, chrome)) continue;
    const imgs = [...block.inner.matchAll(/<img\b([^>]*)>/gi)];
    if (imgs.length !== 2) continue;

    // Split the block at the second picture, so each half holds one image and
    // the words that belong to it. Reading the whole block for both labels
    // would let one caption decide both slots.
    const cut = imgs[1].index ?? 0;
    const halves = [block.inner.slice(0, cut), block.inner.slice(cut)];
    const slots = halves.map((half, i) => {
      const attrs = imgs[i][1];
      // The image's own words first, then the words printed beside it. An
      // `alt="Före behandling"` is the source being explicit; a `<figcaption>`
      // is the source being explicit to the visitor.
      const own = `${attrs} ${attributeValue(attrs, "alt") ?? ""}`;
      const beside = text(half);
      const cls = classTokens(attrs);
      return {
        before: BEFORE_WORD.test(own) || BEFORE_WORD.test(beside) || BEFORE_TOKEN.test(cls),
        after: AFTER_WORD.test(own) || AFTER_WORD.test(beside) || AFTER_TOKEN.test(cls),
        url: (() => {
          const src =
            attrs.match(/\bsrc=["']([^"']+)["']/i)?.[1] ??
            attrs.match(/\bdata-src=["']([^"']+)["']/i)?.[1];
          if (!src || /^data:/i.test(src)) return null;
          return absolute(decode(src), baseUrl);
        })(),
      };
    });
    if (!slots[0].url || !slots[1].url || slots[0].url === slots[1].url) continue;

    // Exactly one of the two is the "before". A slot carrying both words, or
    // neither, has told us nothing.
    const first = slots[0].before && !slots[0].after;
    const second = slots[1].before && !slots[1].after;
    const firstAfter = slots[0].after && !slots[0].before;
    const secondAfter = slots[1].after && !slots[1].before;
    let beforeUrl: string | null = null;
    let afterUrl: string | null = null;
    if (first && secondAfter) [beforeUrl, afterUrl] = [slots[0].url, slots[1].url];
    else if (firstAfter && second) [beforeUrl, afterUrl] = [slots[1].url, slots[0].url];
    if (!beforeUrl || !afterUrl) continue;

    // Innermost-first means the wrapper around a pair is visited after the
    // pair itself; both would match, and the outer one would repeat it.
    const key = `${beforeUrl}|${afterUrl}`;
    if (seen.has(key)) continue;
    seen.add(key);
    if (at === null) at = block.at;
    const label = text(halves[0]).replace(BEFORE_WORD, " ").replace(/\s+/g, " ").trim();
    pairs.push({
      beforeUrl,
      afterUrl,
      ...(label.length >= 2 && label.length <= 60 ? { label: label.slice(0, 60) } : {}),
    });
    if (pairs.length >= 6) break;
  }

  if (pairs.length === 0 || at === null) return null;
  const heading = anyHeadingAbove(body, at);
  return { at: offset + at, ...(heading ? { heading: heading.text } : {}), pairs };
}

// --- cta-band --------------------------------------------------------------

/** A link that is an ACTION, not prose. Either the source styles it as a
 *  button, or its href is one of the three things a small-business site's
 *  closing ask actually points at. */
const CTA_ATTR = /\b(?:class|role)=["'][^"']*\b(?:btn|button|cta|knapp)\b/i;
const CTA_HREF =
  /^(?:tel:|mailto:)|\b(?:boka|bokadirekt|calendly|kontakt|contact|offert|book|booking|quote)\b/i;
/** A band whose ask is to accept cookies, log in, or read a policy is not the
 *  page's call to action. */
const CTA_NOT = /\b(cookies?|kakor|samtycke|consent|gdpr|logga\s+in|log\s?in|sign\s?in|integritetspolicy|privacy\s+policy)\b/i;

/** One button, already sorted into the `ctaTarget` kind it belongs to. A phone
 *  or email ask is not an "external URL": the product has `phone` and `email`
 *  targets that render as a real tel:/mailto: affordance, and forcing one
 *  through `external` would fail its https validation on the way in. Mirrors
 *  the union's shape without importing the Convex model into a pure module. */
export type DetectedCtaAction =
  | { label: string; kind: "external"; url: string }
  | { label: string; kind: "phone"; value: string }
  | { label: string; kind: "email"; value: string };

/** Block elements as **balanced** [open, close] pairs, innermost first.
 *
 *  The `/<div\b[^>]*>([\s\S]*?)<\/div>/` pattern the older detectors in this
 *  file used is not nesting-aware: it stops at the FIRST `</div>`, so on a
 *  page built by Webflow, Elementor or Squarespace — which is most of the
 *  pages this import exists for — a band's captured "inner" is cut off partway
 *  through, usually before the thing being detected. That fails safe (a miss,
 *  not a wrong section) and is exactly why it went unnoticed, but a miss on
 *  div-soup means the detector never fires on the sources that matter.
 *
 *  A single depth-tracking pass over the open/close tokens instead. Innermost
 *  first, because the tightest block carrying the marker is the band; its
 *  wrapper is the page. Self-closing and void forms are ignored (a `<div/>` is
 *  not a container).
 *
 *  **The stack is tag-aware**, which matters as soon as a caller asks for `p`:
 *  an unclosed `<p>` — legal HTML and common in real pages — would otherwise
 *  swallow the `</div>` of the band around it and hand back a block whose
 *  boundaries are nonsense. A close pops to its own matching open, discarding
 *  the unclosed elements above it; a close with no open at all is ignored
 *  rather than throwing, because real pages have those too.
 *
 *  `attrs` is the open tag's own attribute text, so a caller can gate on the
 *  element's class/id/role without re-finding it. */
function balancedBlocks(
  html: string,
  tags = "section|div|aside",
): Array<{ at: number; attrs: string; inner: string }> {
  const out: Array<{ at: number; attrs: string; inner: string }> = [];
  const stack: Array<{ tag: string; at: number; innerAt: number; attrs: string }> = [];
  const re = new RegExp(`<(/?)(${tags})\\b([^>]*)>`, "gi");
  for (const m of html.matchAll(re)) {
    const at = m.index ?? 0;
    const tag = m[2].toLowerCase();
    if (m[1] === "/") {
      let depth = stack.length - 1;
      while (depth >= 0 && stack[depth].tag !== tag) depth--;
      if (depth < 0) continue; // a stray close
      const open = stack[depth];
      stack.length = depth; // drop this open and anything left unclosed inside it
      out.push({ at: open.at, attrs: open.attrs, inner: html.slice(open.innerAt, at) });
      continue;
    }
    if (/\/\s*$/.test(m[3])) continue; // <div />
    stack.push({ tag, at, innerAt: at + m[0].length, attrs: m[3] });
    // A pathological page must not build an unbounded stack.
    if (stack.length > 200) return out;
  }
  return out;
}

export type DetectedCtaBand = {
  at: number;
  headline: string;
  subtext?: string;
  primary: DetectedCtaAction;
  secondary?: DetectedCtaAction;
};

/**
 * The closing "Redo att boka? [Boka tid]" band — a heading, at most one
 * supporting line, and one or two buttons, and nothing else.
 *
 * Every gate here exists to keep it from firing on a band that is something
 * else, because the section it would emit is one an owner then has to delete:
 *
 * - **Position.** A hero is also a heading plus a button, and it owns the top
 *   of the page. This runs only over the back half of the body, which is what
 *   a closing ask IS — it is the one band whose meaning is partly its place.
 * - **Emptiness.** Past the heading, the supporting line and the button
 *   labels, the band holds almost no text. Anything more is an `about` or a
 *   `statement` that happens to end with a link.
 * - **No form, no picture, no list.** A form is `contact`/`lead-form`; a
 *   picture makes it a `banner` or a `bento` cell, and taking one here would
 *   spend a photo the gallery pool has already been offered (the ordering trap
 *   `structureDetect`'s other detectors are wired around).
 * - **One or two links.** Three is a nav or a card grid.
 *
 * Returns null rather than a half-band: `cta-band` requires a `primaryCta`, so
 * a heading whose button we could not resolve is not one.
 */
export function detectCtaBand(html: string, baseUrl: string): DetectedCtaBand | null {
  const { html: body, offset } = bodyOf(html);
  const chrome = chromeRanges(body);
  const backHalf = body.length / 2;
  for (const block of balancedBlocks(body)) {
    const at = block.at;
    if (at < backHalf) continue;
    if (inChrome(at, chrome)) continue;
    const inner = block.inner;
    if (/<(?:form|input|textarea|select|img|picture|table|ul|ol)\b/i.test(inner)) continue;
    const heading = inner.match(/<h([1-4])\b[^>]*>([\s\S]*?)<\/h\1>/i);
    if (!heading) continue;
    // Exactly one heading: two means this is a wrapper around several bands.
    if ((inner.match(/<h[1-4]\b/gi) ?? []).length !== 1) continue;
    const headline = text(heading[2]);
    if (headline.length < 4 || headline.length > 120) continue;

    const links = [...inner.matchAll(/<a\b([^>]*)>([\s\S]*?)<\/a>/gi)];
    if (links.length < 1 || links.length > 2) continue;
    const actions: DetectedCtaAction[] = [];
    for (const link of links) {
      const label = text(link[2]).slice(0, 40);
      if (label.length < 2) continue;
      const href = link[1].match(/\bhref=["']([^"']+)["']/i)?.[1];
      if (!href) continue;
      const raw = decode(href).trim();
      // A button by its look OR by where it points; a bare in-prose link is
      // neither, and a band whose only link is one is not an ask.
      if (!CTA_ATTR.test(link[1]) && !CTA_HREF.test(raw)) continue;
      const tel = raw.match(/^tel:(.+)$/i);
      if (tel) {
        const value = safeDecodeURIComponent(tel[1]).replace(/\s+/g, " ").trim().slice(0, 40);
        if (value) actions.push({ label, kind: "phone", value });
        continue;
      }
      const mail = raw.match(/^mailto:([^?]+)/i);
      if (mail) {
        const value = safeDecodeURIComponent(mail[1]).trim().slice(0, 120);
        if (value) actions.push({ label, kind: "email", value });
        continue;
      }
      const url = absolute(raw, baseUrl);
      if (!url) continue;
      actions.push({ label, kind: "external", url });
    }
    if (actions.length === 0) continue;

    // What is left once the heading and the button labels are removed. A
    // closing band has one short line of reassurance here, or nothing.
    // `split().join()` rather than `replace()`: `replace` with a string takes
    // only the FIRST occurrence, and a label repeated in the band ("Boka tid.
    // Boka nu!") left the duplicate behind and inflated the leftover-text
    // measurement this gate is made of. No regex, so no escaping to get wrong.
    const whole = text(inner);
    let rest = whole.split(headline).join(" ");
    for (const a of actions) rest = rest.split(a.label).join(" ");
    const subtext = rest.replace(/\s+/g, " ").trim();
    if (subtext.length > 200) continue;
    if (CTA_NOT.test(whole)) continue;

    return {
      at: offset + at,
      headline: headline.slice(0, 120),
      ...(subtext.length >= 8 ? { subtext: subtext.slice(0, 200) } : {}),
      primary: actions[0],
      ...(actions[1] ? { secondary: actions[1] } : {}),
    };
  }
  return null;
}

// --- scroll-tabs -----------------------------------------------------------

/** A tab CONTROL: `role="tab"`, or the class every builder gives its tab
 *  buttons. `nav-link` is Bootstrap's, and it is also what a navbar uses — it
 *  only counts here because a candidate block must ALSO hold matching panes,
 *  and a navbar has none. */
const TAB_LABEL_ATTR =
  /\brole=["']tab["']|\bclass=["'][^"']*\b(?:w-tab-link|elementor-tab-title|tab-title|tab-link|nav-link)\b/i;

/** A tab PANEL. Deliberately not `tab-content`: in Bootstrap that is the
 *  wrapper AROUND the panes, so matching it would count one giant "panel"
 *  holding all the others and the pairing below would refuse the widget. In
 *  Elementor `elementor-tab-content` IS the pane, hence both spellings. */
const TAB_PANEL_ATTR =
  /\brole=["']tabpanel["']|\bclass=["'][^"']*\b(?:w-tab-pane|elementor-tab-content|tab-pane|tab-panel)\b/i;

/** Accordion markup. An accordion is a `faq`, which the import already detects,
 *  and the two look alike once you are only counting labels and panels. */
const TAB_NOT_ACCORDION = /<details\b|\bclass=["'][^"']*\b(?:accordion|collapse)\b/i;

/** How far above the widget its own heading may sit. Enough for a builder's
 *  wrapper divs and a lead-in paragraph, short enough that the previous
 *  section's title cannot be mistaken for this band's. */
const TAB_HEADING_REACH = 600;

export type DetectedScrollTabs = {
  at: number;
  heading?: string;
  intro?: string;
  tabs: Array<{ label: string; title?: string; description: string }>;
};

/**
 * A real tab widget — the "Behandlingar / Priser / Om oss" strip a clinic,
 * salon or gym puts one set of labels above one set of panels.
 *
 * Today the import destroys it: every panel's prose is flattened into the page
 * and the relationship between a label and the panel it opens — the whole
 * content — is thrown away, usually leaving one band of run-on text where the
 * source had four readable ones.
 *
 * **A tab widget is a behaviour, so the gate is the widget, never a heading.**
 * A list of headings with paragraphs under them is `highlights` or `process`,
 * and emitting `scroll-tabs` there would be exactly the wrong-section-is-worse
 * -than-none case this file is built around. What is required:
 *
 * - **Labels and panels are both present, and there are the same number.** This
 *   is the load-bearing gate. It is what a tab widget structurally IS, it is
 *   what a heading list is not, and it is also the honest limit: unequal counts
 *   mean we cannot say which label opens which panel, and a section that pairs
 *   them wrongly reads as correct.
 * - **The labels sit together.** Every recogniser here keys off a tab-strip
 *   class or `role="tab"`, which a builder only emits for a control group.
 * - **Not an accordion.** `<details>` or an `accordion`/`collapse` class means
 *   the labels and panels interleave — that is a `faq`, already detected.
 * - **Two to eight tabs**, each with a label and real prose in its panel. One
 *   is not a widget; a panel with nothing to read cannot fill `description`,
 *   which the section requires.
 * - **Not chrome.** A `nav-link` run inside `<nav>` is a navigation bar.
 *
 * **It deliberately takes no pictures.** A tab may carry `media`, but claiming
 * one here would spend a photo the gallery pool has already been offered — the
 * ordering trap the other detectors in this file are wired around — and the
 * band is readable without it. A tab's image stays available to the gallery.
 */
export function detectScrollTabs(html: string): DetectedScrollTabs | null {
  const { html: body, offset } = bodyOf(html);
  const chrome = chromeRanges(body);
  // `aside` is in the candidate set because a sidebar tab strip is a real
  // shape; `main` deliberately is not — it would make the whole page one
  // candidate block and let a label from one band pair with a panel from
  // another. Innermost-first already prefers the tightest wrapper.
  for (const block of balancedBlocks(body, "div|section|article|aside")) {
    if (inChrome(block.at, chrome)) continue;
    const inner = block.inner;
    // The block's OWN attributes count too: `class="accordion"` sits on the
    // wrapper, so testing only its contents let every accordion through.
    if (TAB_NOT_ACCORDION.test(inner) || TAB_NOT_ACCORDION.test(block.attrs)) continue;
    if (!TAB_PANEL_ATTR.test(inner) || !TAB_LABEL_ATTR.test(inner)) continue;

    const parts = balancedBlocks(inner, "div|section|a|li|button|article|p|span");
    // Document order, and drop anything nested inside a sibling already kept:
    // a pane that wraps its own `.tab-pane`-classed child would otherwise be
    // counted twice and break the equal-count gate on a widget that is fine.
    //
    // Nesting is decided by POSITION, not by "is one inner a substring of the
    // other". Two panels can legitimately hold identical markup — a strip whose
    // panes differ only in a picture, say — and a substring test would drop the
    // second one as though it were a child, quietly turning a good widget into
    // a count mismatch. `indexOf` from the element's own offset finds where its
    // inner actually starts, so the span is exact.
    const pick = (re: RegExp) => {
      const kept: Array<{ at: number; inner: string; end: number }> = [];
      for (const p of [...parts].sort((a, b) => a.at - b.at)) {
        if (!re.test(p.attrs)) continue;
        const start = inner.indexOf(p.inner, p.at);
        const end = start < 0 ? p.at : start + p.inner.length;
        if (kept.some((k) => p.at > k.at && p.at < k.end)) continue;
        kept.push({ at: p.at, inner: p.inner, end });
      }
      return kept;
    };
    const labels = pick(TAB_LABEL_ATTR);
    const panels = pick(TAB_PANEL_ATTR);
    if (labels.length < 2 || labels.length > 8) continue;
    if (labels.length !== panels.length) continue;

    const tabs: DetectedScrollTabs["tabs"] = [];
    for (let i = 0; i < labels.length; i++) {
      const label = text(labels[i].inner).slice(0, 40);
      if (label.length < 2) break;
      // A panel's own heading is the tab's title, and it must come OUT of the
      // description or the section renders the same line twice.
      const h = panels[i].inner.match(/<h([2-4])\b[^>]*>([\s\S]*?)<\/h\1>/i);
      const title = h ? text(h[2]).slice(0, 120) : "";
      const rest = h ? panels[i].inner.split(h[0]).join(" ") : panels[i].inner;
      const description = text(rest).slice(0, 600);
      if (description.length < 20) break;
      tabs.push({ label, ...(title.length >= 2 ? { title } : {}), description });
    }
    // Half a tab strip is a wrong section, not a smaller one: the labels that
    // survived would silently point at the wrong panels.
    if (tabs.length !== labels.length) continue;

    // The band's own heading is the LAST one ABOVE the widget, not one inside
    // it. A builder wraps the tab control in its own div, so the `<h2>` that
    // titles the band lives in the section around it and never in `inner` —
    // the same "nearest heading above" join the measured-band mapping uses.
    // Bounded by distance, because a heading far up the page belongs to
    // whatever sits between it and here, not to this widget.
    const before = body.slice(Math.max(0, block.at - TAB_HEADING_REACH), block.at);
    const headings = [...before.matchAll(/<h([1-3])\b[^>]*>([\s\S]*?)<\/h\1>/gi)];
    const bandHeading = headings[headings.length - 1];
    const heading = bandHeading ? text(bandHeading[2]).slice(0, 120) : "";
    // The lead-in is what sits between that heading and the widget.
    const afterHeading = bandHeading
      ? before.slice((bandHeading.index ?? 0) + bandHeading[0].length)
      : before;
    const intro = text(afterHeading).slice(0, 280);

    return {
      at: offset + block.at,
      ...(heading.length >= 3 ? { heading } : {}),
      ...(intro.length >= 12 ? { intro } : {}),
      tabs,
    };
  }
  return null;
}

// --- illustration ----------------------------------------------------------

/** A drawable SVG element that is NOT a `<path>`. The section model can express
 *  paths and nothing else — deliberately, because a path cannot carry a URL, an
 *  event attribute or a `foreignObject` — so an `<svg>` holding any of these
 *  cannot be imported without silently redrawing it. */
const SVG_NOT_PATH =
  /<(circle|ellipse|rect|line|polyline|polygon|text|tspan|image|use|foreignObject|clipPath|mask|filter|linearGradient|radialGradient|pattern|symbol|marker|style|script|animate\w*)\b/i;

/** An icon, not a drawing. Every page has a dozen of these — chevrons, social
 *  glyphs, a burger menu — and each one would import as its own band. */
const SVG_IS_ICON = /\bclass=["'][^"']*\b(?:icon|logo|arrow|chevron|caret|burger|social)\b/i;

/** Below this the `<svg>` is a glyph. A 24×24 or 32×32 box is the icon
 *  convention; a real line drawing is hundreds of units across. */
const SVG_MIN_EXTENT = 120;
/** One or two paths is a glyph even at a large viewBox. */
const SVG_MIN_PATHS = 3;

export type DetectedIllustration = {
  at: number;
  viewBox: string;
  paths: Array<{ d: string; fill?: string; stroke?: string; strokeWidth?: number }>;
};

/**
 * An inline line drawing — the hand-drawn figure an agency template puts beside
 * a "Så gör vi" block. Today the import destroys it outright: every prose
 * extractor in this pipeline strips `<svg>` before reading, so the drawing does
 * not become a weaker section, it becomes nothing.
 *
 * **Shape is imported; colour is not, on purpose.** A source path's fill is a
 * hex, and there is no honest mapping from a hex onto the site's closed ink
 * token set — so a path keeps only whether it is FILLED or STROKED and takes
 * its colour from the site. That is the behaviour `lib/sections/illustration.ts`
 * is built for ("an imported drawing recolours with the site instead of
 * freezing the source's palette"), and it is why this is worth importing at all
 * rather than storing the source's markup.
 *
 * The gates, each of which exists to refuse a different wrong band:
 *
 * - **Paths only.** An `<svg>` holding a `<rect>`, a `<text>`, a gradient or a
 *   `<use>` is refused rather than imported without them. Dropping elements
 *   would hand the owner a drawing that is missing pieces and looks like ours.
 * - **Not an icon.** A glyph is refused three ways — by its class, by a viewBox
 *   under 120 units, and by having fewer than three paths — because a page has
 *   many and each would otherwise arrive as its own section.
 * - **Not chrome.** The logo in the header is an inline `<svg>` too.
 * - **Every path re-validated** through the section's own `safePathData` /
 *   `safeViewBox` / `safeStrokeWidth`, so an import cannot put anything in a
 *   `d` attribute that an owner-authored drawing could not.
 *
 * One drawing per page: the first that qualifies. A template that repeats the
 * motif in every band would otherwise import as five identical sections.
 */
export function detectIllustration(html: string): DetectedIllustration | null {
  const { html: body, offset } = bodyOf(html);
  const chrome = chromeRanges(body);
  for (const m of body.matchAll(/<svg\b([^>]*)>([\s\S]*?)<\/svg>/gi)) {
    const at = m.index ?? 0;
    if (inChrome(at, chrome)) continue;
    const attrs = m[1];
    const inner = m[2];
    if (SVG_IS_ICON.test(attrs)) continue;
    if (SVG_NOT_PATH.test(inner)) continue;

    const viewBox = safeViewBox(attrs.match(/\bviewBox=["']([^"']+)["']/i)?.[1]);
    if (!viewBox) continue;
    const [, , width, height] = viewBox.split(" ").map(Number);
    if (width < SVG_MIN_EXTENT || height < SVG_MIN_EXTENT) continue;

    // The root's own paint is the default every path inherits.
    const rootFill = attrs.match(/\bfill=["']([^"']+)["']/i)?.[1]?.trim().toLowerCase();
    const rootStroke = attrs.match(/\bstroke=["']([^"']+)["']/i)?.[1]?.trim().toLowerCase();

    const paths: DetectedIllustration["paths"] = [];
    let dropped = false;
    for (const p of inner.matchAll(/<path\b([^>]*?)\/?>/gi)) {
      if (paths.length >= ILLUSTRATION_LIMITS.paths) break;
      const pa = p[1];
      const d = safePathData(decode(pa.match(/\bd=["']([^"']+)["']/i)?.[1] ?? ""));
      if (!d) {
        // A path this model cannot store is not a path we quietly leave out:
        // the drawing would arrive with a line missing and look intentional.
        dropped = true;
        break;
      }
      const fill = (pa.match(/\bfill=["']([^"']+)["']/i)?.[1] ?? rootFill ?? "")
        .trim()
        .toLowerCase();
      const stroke = (pa.match(/\bstroke=["']([^"']+)["']/i)?.[1] ?? rootStroke ?? "")
        .trim()
        .toLowerCase();
      const strokeWidth = safeStrokeWidth(
        Number(pa.match(/\bstroke-width=["']([^"']+)["']/i)?.[1]),
      );
      paths.push({
        d,
        // Only the two facts that survive the hop honestly: whether this path
        // is filled, and whether it is drawn. The ink itself is the site's.
        ...(fill === "none" ? { fill: "none" } : {}),
        ...(stroke && stroke !== "none" ? { stroke: "ink" } : {}),
        ...(strokeWidth !== undefined ? { strokeWidth } : {}),
      });
    }
    if (dropped) continue;
    if (paths.length < SVG_MIN_PATHS) continue;

    return { at: offset + at, viewBox, paths };
  }
  return null;
}

// --- contact form fields ---------------------------------------------------

/** Field types the section model accepts. Anything else on the source form is
 *  mapped onto the nearest of these or dropped — never rendered as-is. */
export type DetectedFormField = {
  key: string;
  label: string;
  type:
    | "text"
    | "email"
    | "phone"
    | "address"
    | "postalCode"
    | "city"
    | "country"
    | "textarea"
    | "select";
  required: boolean;
  options?: string[];
  placeholder?: string;
};

/** A form we must never read as the page's contact form. A password field is a
 *  login, and a lone search box is a search box. */
const FORM_NOT_CONTACT =
  /type=["']?password["']?|\brole=["']search["']|\bclass=["'][^"']*\b(?:search|login|signin|sign-in|logga-in)\b|\bid=["'][^"']*\b(?:search|login)\b/i;

/** Mailchimp and friends hide a text input off-screen and treat anything typed
 *  into it as a bot. Importing it would put a mystery box on the owner's form —
 *  and the same trap already caught the newsletter detector. */
const FORM_HONEYPOT =
  /tabindex=["']?-1|aria-hidden=["']?true|\b(?:honeypot|hp_|_gotcha|bot-field)\b|display\s*:\s*none|visibility\s*:\s*hidden|position\s*:\s*absolute\s*;\s*left\s*:\s*-/i;

/** Fewer than this and it is a search box or a signup, not a contact form.
 *  More and it is a checkout, a booking widget or an application form — none of
 *  which the `contact` section is, and each of which would arrive as a wall of
 *  inputs the owner has to delete one at a time. */
const FORM_MIN_FIELDS = 2;
const FORM_MAX_FIELDS = 10;

function fieldKey(raw: string, taken: Set<string>): string {
  const base =
    raw
      .toLowerCase()
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "")
      .replace(/[^a-z0-9]+/g, "_")
      .replace(/^_+|_+$/g, "")
      .slice(0, 32) || "field";
  let key = base;
  let n = 2;
  while (taken.has(key)) key = `${base}_${n++}`;
  taken.add(key);
  return key;
}

/**
 * The fields the source's own contact form actually asked for.
 *
 * The import has always emitted a `contact` section and has always **invented**
 * its three fields — name, email, message — whatever the source asked. So a
 * builder whose form collected "Telefon", "Adress" and "Typ av uppdrag" got an
 * imported form that silently stopped collecting them, and the owner had no way
 * to know except by comparing the two forms field by field. That is content
 * loss dressed as a working import, and it is the same failure the structural
 * detectors exist to stop.
 *
 * Returns null when the page has no form we should read, and null means "keep
 * the three defaults" — the defaults are a working form, so a miss here costs
 * nothing while a wrong read costs the owner a form that asks the wrong things.
 *
 * The gates:
 *
 * - **Never a login or a search box.** A `password` input, or a search role or
 *   class, refuses the whole form.
 * - **Never a newsletter signup.** One email input and nothing else cannot
 *   clear `FORM_MIN_FIELDS`, which is also what keeps this off the footer
 *   subscribe box `detectNewsletter` already owns.
 * - **Honeypots are dropped, not imported.** A hidden text input is how a
 *   builder catches bots; on the owner's new form it would be a mystery box.
 * - **Two to ten fields.** More than ten is a checkout or an application form.
 * - **It must be able to capture a reply.** A form with no email and no phone
 *   field produces leads nobody can answer, so we keep our defaults instead —
 *   the one case where the source's own structure is worse than ours.
 */
export function detectFormFields(html: string): DetectedFormField[] | null {
  const { html: body } = bodyOf(html);
  for (const form of body.matchAll(/<form\b([^>]*)>([\s\S]*?)<\/form>/gi)) {
    const inner = form[2];
    if (FORM_NOT_CONTACT.test(form[1]) || FORM_NOT_CONTACT.test(inner)) continue;

    // `for="id"` wins over every other guess: it is the label the page shows.
    const labelFor = new Map<string, string>();
    for (const l of inner.matchAll(/<label\b([^>]*)>([\s\S]*?)<\/label>/gi)) {
      const forId = l[1].match(/\bfor=["']([^"']+)["']/i)?.[1];
      const words = text(l[2]).replace(/\s*\*\s*$/, "").trim();
      if (forId && words) labelFor.set(forId, words);
    }

    const fields: DetectedFormField[] = [];
    const taken = new Set<string>();
    let refused = false;
    // `input` is a VOID element and `textarea`/`select` are not, so they cannot
    // share one pattern: a single alternation that required either `/>` or a
    // closing tag matched no plain `<input name="x">` at all — which is how
    // every real form is written. Collected separately and re-sorted into
    // document order, because the order of the fields IS part of the form.
    const controls = [
      ...[...inner.matchAll(/<input\b([^>]*?)\/?>/gi)].map((m) => ({
        at: m.index ?? 0,
        tag: "input",
        attrs: m[1],
        body: "",
      })),
      ...[...inner.matchAll(/<(textarea|select)\b([^>]*?)>([\s\S]*?)<\/\1>/gi)].map(
        (m) => ({
          at: m.index ?? 0,
          tag: m[1].toLowerCase(),
          attrs: m[2],
          body: m[3],
        }),
      ),
    ].sort((a, b) => a.at - b.at);
    for (const c of controls) {
      const tag = c.tag;
      const attrs = c.attrs;
      const type = (attrs.match(/\btype=["']([^"']+)["']/i)?.[1] ?? "").toLowerCase();
      if (tag === "input" && ["hidden", "submit", "button", "image", "reset"].includes(type)) {
        continue;
      }
      if (tag === "input" && ["checkbox", "radio", "file"].includes(type)) {
        // The model has no field for these. Dropping one silently would change
        // what the form asks, so the whole read is refused and the defaults
        // stand — an honest miss instead of a quiet edit.
        refused = true;
        break;
      }
      if (FORM_HONEYPOT.test(attrs)) continue;

      const name = attrs.match(/\bname=["']([^"']+)["']/i)?.[1] ?? "";
      const id = attrs.match(/\bid=["']([^"']+)["']/i)?.[1] ?? "";
      const placeholder = decode(attrs.match(/\bplaceholder=["']([^"']+)["']/i)?.[1] ?? "");
      const aria = decode(attrs.match(/\baria-label=["']([^"']+)["']/i)?.[1] ?? "");
      const label = (labelFor.get(id) || aria || placeholder || name || "").trim();
      if (!label || label.length > 60) continue;

      let kind: DetectedFormField["type"] = "text";
      let options: string[] | undefined;
      if (tag === "textarea") kind = "textarea";
      else if (tag === "select") {
        kind = "select";
        options = [...c.body.matchAll(/<option\b[^>]*>([\s\S]*?)<\/option>/gi)]
          .map((o) => text(o[1]))
          .filter((o) => o.length > 0 && o.length <= 60)
          .slice(0, 20);
        // A select with nothing to choose from is a broken control, not a field.
        if (options.length < 2) continue;
      } else if (type === "email") kind = "email";
      else if (type === "tel") kind = "phone";
      else if (/^(street-address|address-line1)$/i.test(
        attrs.match(/\bautocomplete=["']([^"']+)["']/i)?.[1] ?? "",
      )) kind = "address";
      else if (/^postal-code$/i.test(
        attrs.match(/\bautocomplete=["']([^"']+)["']/i)?.[1] ?? "",
      )) kind = "postalCode";
      else if (/^address-level2$/i.test(
        attrs.match(/\bautocomplete=["']([^"']+)["']/i)?.[1] ?? "",
      )) kind = "city";
      else if (/^country(?:-name)?$/i.test(
        attrs.match(/\bautocomplete=["']([^"']+)["']/i)?.[1] ?? "",
      )) kind = "country";

      if (fields.length >= FORM_MAX_FIELDS) {
        refused = true;
        break;
      }
      fields.push({
        key: fieldKey(name || id || label, taken),
        label: label.slice(0, 60),
        type: kind,
        required: /\brequired\b|\baria-required=["']?true/i.test(attrs),
        ...(options ? { options } : {}),
        ...(placeholder && placeholder !== label
          ? { placeholder: placeholder.slice(0, 80) }
          : {}),
      });
    }

    if (refused) continue;
    if (fields.length < FORM_MIN_FIELDS) continue;
    if (!fields.some((f) => f.type === "email" || f.type === "phone")) continue;
    return fields;
  }
  return null;
}

// --- rich-text -------------------------------------------------------------

/** Comparison key for a run of prose: enough of it to be certain, loose enough
 *  to survive a detector's own truncation (FAQ answers are cut at 600 chars).
 *
 *  Exported because `htmlToSections` keys its "already claimed" set the same
 *  way, and two copies of this rule drifting apart would let a paragraph count
 *  as claimed in one file and unclaimed in the other — which is precisely how
 *  the same sentence ends up on two sections. */
export function proseKey(s: string): string {
  return s.replace(/\s+/g, " ").trim().slice(0, 80).toLowerCase();
}

export type RichTextBlock =
  | { kind: "h"; level: 3; text: string }
  | { kind: "p"; text: string }
  | { kind: "ul"; items: string[] };

/** At least this many paragraphs before a leftover run counts as an article.
 *  Two paragraphs under one subheading is a story, and `about` renders it. */
const RICH_MIN_PARAGRAPHS = 3;

/** And at least this much prose. A page can have three short lines and a
 *  subheading without having written anything long-form. */
const RICH_MIN_CHARS = 400;

/** A list item long enough to be a point and short enough not to be a
 *  paragraph that happened to be marked up as one. */
const RICH_ITEM_MIN = 2;
const RICH_ITEM_MAX = 200;

/**
 * The structure inside the owner's own leftover prose — its subheadings, its
 * bullet lists, and the order they came in.
 *
 * **This is a replacement, not an extra band.** It reads exactly the paragraphs
 * `about` was about to render and nothing else, so it can never put the same
 * words on two sections: the caller emits `rich-text` INSTEAD of `about`, from
 * the same pool, at the same position. That is the whole reason it takes the
 * kept paragraphs as an argument rather than re-reading the page — a detector
 * that found its own prose would be competing with `about` for it.
 *
 * What it recovers is real and was a total loss until now. `about.body` is one
 * string, so a long-form page — a treatment write-up, a method, a policy, an
 * "Så går det till" article — imported as a wall of joined text: every `h3` the
 * owner wrote to break it up was gone, and every bulleted list had its bullets
 * flattened into the paragraph before it.
 *
 * Gates, all of them structural:
 *
 * - **Three or more kept paragraphs, and 400+ characters of them.** Below that
 *   there is nothing to structure and `about` is the right band.
 * - **At least one subheading or one list inside the run.** This is the load-
 *   bearing gate: without it the blocks would be a list of `p`s, which is
 *   exactly what `about` already renders, and swapping the section type would
 *   change nothing but the owner's editor.
 * - **Nothing another section already claimed.** A subheading a `faq`, `process`
 *   or `pricing` band was built from, or a list whose items are somebody else's
 *   copy, is skipped — a heading is not free just because its paragraph was.
 * - **Not chrome.** A footer's fine print is not the owner's article.
 *
 * `h4` is emitted at level 3 with `h3`: the section deliberately has no h1 and
 * only two levels, and a source's h4 under an h3 is a sub-sub-point whose depth
 * we cannot render anyway. Flattening it keeps the words; inventing a level
 * would not.
 */
export function detectRichTextBlocks(
  html: string,
  keptParagraphs: readonly string[],
  claimed: ReadonlySet<string>,
): RichTextBlock[] | null {
  if (keptParagraphs.length < RICH_MIN_PARAGRAPHS) return null;
  const totalChars = keptParagraphs.reduce((n, p) => n + p.length, 0);
  if (totalChars < RICH_MIN_CHARS) return null;

  const wanted = new Set(keptParagraphs.map(proseKey));
  const chrome = chromeRanges(html);

  // The span the article occupies: from the first kept paragraph to the end of
  // the last. Bounding it matters — an unclaimed `h3` three sections further
  // down the page belongs to whatever band sits there, not to this one.
  //
  // Both ends reach one element outward across whitespace ONLY, because an
  // article's first subheading sits immediately above its first paragraph and
  // a trailing "…så här går det till:" list sits immediately below its last —
  // both are plainly the article's, and both were being dropped. Whitespace is
  // the whole allowance: anything with so much as a wrapper element between it
  // and the prose belongs to whatever wrapped it, not to this run.
  const paras = [...html.matchAll(/<p\b[^>]*>([\s\S]*?)<\/p>/gi)]
    .map((m) => ({ at: m.index ?? 0, end: (m.index ?? 0) + m[0].length, text: text(m[1]) }))
    .filter((p) => wanted.has(proseKey(p.text)) && !inChrome(p.at, chrome));
  if (paras.length < RICH_MIN_PARAGRAPHS) return null;
  const start = paras[0].at;
  const end = paras[paras.length - 1].end;

  type Found = { at: number; block: RichTextBlock };
  const found: Found[] = paras.map((p) => ({ at: p.at, block: { kind: "p", text: p.text } }));

  /** In the article's run — inside the prose, or touching it across whitespace. */
  const inSpan = (at: number, elementEnd: number): boolean => {
    if (at >= start && at <= end) return true;
    // `elementEnd <= start` is not implied by `at < start`: in tag soup an `h3`
    // can WRAP the first paragraph, and then the backwards slice below is the
    // empty string, which reads as "only whitespace between them" and lets an
    // element that swallowed the article count as its subheading. Deliberately
    // untested: every wrap long enough to reach the prose also blows the 120-
    // character heading cap, so no honest fixture fails without this line. It
    // stays because the cap is a different rule that could be relaxed.
    if (at < start && elementEnd <= start) return /^\s*$/.test(html.slice(elementEnd, start));
    return false;
  };

  for (const m of html.matchAll(/<h([34])\b[^>]*>([\s\S]*?)<\/h\1>/gi)) {
    const at = m.index ?? 0;
    if (!inSpan(at, at + m[0].length)) continue;
    if (inChrome(at, chrome)) continue;
    const value = text(m[2]);
    if (value.length < 2 || value.length > 120) continue;
    if (claimed.has(proseKey(value))) continue;
    found.push({ at, block: { kind: "h", level: 3, text: value } });
  }

  for (const m of html.matchAll(/<(ul|ol)\b[^>]*>([\s\S]*?)<\/\1>/gi)) {
    const at = m.index ?? 0;
    if (!inSpan(at, at + m[0].length)) continue;
    // A footer's link list sits between two of the article's paragraphs on
    // plenty of real pages, so the span alone does not exclude chrome.
    if (inChrome(at, chrome)) continue;
    const items = [...m[2].matchAll(/<li\b[^>]*>([\s\S]*?)<\/li>/gi)]
      .map((li) => text(li[1]))
      .filter((v) => v.length >= RICH_ITEM_MIN && v.length <= RICH_ITEM_MAX)
      .slice(0, 20);
    if (items.length < 2) continue;
    // A list whose points are somebody else's copy — a services grid's item
    // titles, an FAQ's questions — is that section's, not this article's.
    if (items.some((v) => claimed.has(proseKey(v)))) continue;
    found.push({ at, block: { kind: "ul", items } });
  }

  // Structure is the point. A run of plain paragraphs is what `about` already
  // renders, and swapping the type for it would be churn.
  if (!found.some((f) => f.block.kind !== "p")) return null;

  found.sort((a, b) => a.at - b.at);
  return found.map((f) => f.block);
}

/** How many items a bare list needs before it is a page's content rather than
 *  a stray pair of links. Three is the same bar `highlights` renders against. */
const LOOSE_LIST_MIN_ITEMS = 3;
/** An item longer than this is prose, and prose belongs to `about` or
 *  `rich-text`, both of which read the page's paragraphs. */
const LOOSE_LIST_ITEM_MAX = 90;

/**
 * A page whose only content is a LIST.
 *
 * `<h1>Catering</h1><ul><li>Frukostlåda</li><li>Kontorsfika</li>…</ul>` is a
 * real shape on real sites — a services page, a menu page, a "det här ingår"
 * page — and until now it imported as nothing at all: `about` and `rich-text`
 * both read paragraphs, `services` and `highlights` both need a heading with
 * content under it, so a page with a heading and a bare list produced a hero, a
 * contact band and a footer, and the list was gone. Found by running the CLI
 * importer over the multipage golden fixture, whose `services.html` is exactly
 * this shape (2026-08-16).
 *
 * Deliberately narrow, because a page with any other content already has a band
 * that reads it: the caller passes `hasContentBand` and this returns null when
 * something else already speaks for the page. Every other gate is structural —
 * outside header/nav/footer, three or more items, each short enough to be a
 * label rather than a sentence, and nothing another band already claimed.
 */
export function detectLooseList(
  html: string,
  claimed: ReadonlySet<string>,
): { items: string[] } | null {
  const body = bodyOf(html);
  const chrome = chromeRanges(html);
  for (const m of body.html.matchAll(/<(ul|ol)\b[^>]*>([\s\S]*?)<\/\1>/gi)) {
    const at = (m.index ?? 0) + body.offset;
    if (inChrome(at, chrome)) continue;
    const items = [...m[2].matchAll(/<li\b[^>]*>([\s\S]*?)<\/li>/gi)]
      .map((li) => text(li[1]))
      .filter((v) => v.length >= RICH_ITEM_MIN && v.length <= LOOSE_LIST_ITEM_MAX)
      .slice(0, 12);
    if (items.length < LOOSE_LIST_MIN_ITEMS) continue;
    // A list of links is navigation wearing a different tag — a sitemap, a
    // language switcher, a category rail. Only a list that is mostly TEXT is
    // this page's content.
    const linked = [...m[2].matchAll(/<a\b[^>]*>/gi)].length;
    if (linked >= items.length) continue;
    if (items.some((v) => claimed.has(proseKey(v)))) continue;
    return { items };
  }
  return null;
}

// --- an explicitly grouped gallery ------------------------------------------

/** Wrapper classes/ids that mean "these pictures belong together as a gallery".
 *  Deliberately narrow: a `grid` or a `row` is a layout, a `gallery` is a
 *  statement about the content. */
const GALLERY_BLOCK =
  /(?:^|[\s_"'-])(?:gallery|galleri|bildgalleri|photo-?grid|image-?grid|portfolio-?grid|lightbox)(?:$|[\s_"'-])/i;

/**
 * Pictures the SOURCE grouped as a gallery, in document order.
 *
 * Why this exists: the gallery band was built from whatever the hero, About and
 * the picture-owning detectors left over, so a page with exactly three
 * photographs inside a `.gallery` wrapper lost its gallery — the hero took one,
 * About took another, and the third had nowhere to go and was reported as
 * "never referenced". The source had already said those three belong together,
 * and an explicit grouping outranks our ranking.
 *
 * Returns null below three pictures: a gallery is three photographs, and one or
 * two inside a wrapper is a layout choice, not a band. Chrome is excluded — a
 * footer's partner strip is not this page's gallery.
 */
export function detectGalleryGroup(html: string, baseUrl: string): string[] | null {
  const { html: body, offset } = bodyOf(html);
  const chrome = chromeRanges(html);
  for (const block of balancedBlocks(body, "div|section|ul|figure")) {
    if (!GALLERY_BLOCK.test(block.attrs)) continue;
    if (inChrome(offset + block.at, chrome)) continue;
    const urls: string[] = [];
    for (const img of block.inner.matchAll(/<img\b([^>]*)>/gi)) {
      const src =
        img[1].match(/\bsrc=["']([^"']+)["']/i)?.[1] ??
        img[1].match(/\bdata-src=["']([^"']+)["']/i)?.[1];
      if (!src || /^data:/i.test(src)) continue;
      const url = absolute(decode(src), baseUrl);
      if (url && !urls.includes(url)) urls.push(url);
      if (urls.length >= 12) break;
    }
    if (urls.length >= 3) return urls;
  }
  return null;
}

// --- opening hours written as ordinary text ---------------------------------
//
// Why this exists, measured. The importer read opening hours from one place
// only: the page's schema.org `openingHoursSpecification`. Almost no small
// business site has that. What every one of them DOES have is a weekday and a
// time range printed on the page, and over the fidelity corpus that is a whole
// labelled block the import produced nothing for - the dentist's contact page
// scored 0% body fidelity while its own markup said "Måndag 08:00-18:00" five
// times in a row (backlog 2643). Hours are also the single fact a visitor is
// most often on the page to find, so losing them is not a layout miss.
//
// Deterministic and conservative: a weekday NAME next to a time range, or next
// to a word that means closed. A bare time ("Telefontid: 08:00-20:00") is not
// hours, and neither is a weekday with nothing beside it.

/** Weekday words we accept, longest first so "söndag" is not read as "sön" and
 *  then left with "dag" hanging. Swedish and English only: those are the two
 *  languages the importer's own copy speaks. */
const WEEKDAYS: ReadonlyArray<{ key: OpeningDayKey; words: readonly string[] }> = [
  { key: "mon", words: ["måndag", "mandag", "monday", "mån", "mon"] },
  { key: "tue", words: ["tisdag", "tuesday", "tis", "tue"] },
  { key: "wed", words: ["onsdag", "wednesday", "ons", "wed"] },
  { key: "thu", words: ["torsdag", "thursday", "tors", "tor", "thu"] },
  { key: "fri", words: ["fredag", "friday", "fre", "fri"] },
  { key: "sat", words: ["lördag", "lordag", "saturday", "lör", "sat"] },
  { key: "sun", words: ["söndag", "sondag", "sunday", "sön", "sun"] },
];

export type OpeningDayKey = "mon" | "tue" | "wed" | "thu" | "fri" | "sat" | "sun";

const DAY_ORDER: readonly OpeningDayKey[] = ["mon", "tue", "wed", "thu", "fri", "sat", "sun"];

/** Built from the words above rather than typed out a second time. The bare
 *  unaccented three-letter forms ("man", "lor", "son") are deliberately absent:
 *  "man" and "son" are ordinary words, and a page that writes "man 08:00-17:00"
 *  is rarer than one that would be misread. */
const DAY_BY_WORD: ReadonlyMap<string, OpeningDayKey> = new Map(
  WEEKDAYS.flatMap(({ key, words }) => words.map((w) => [w, key] as const)),
);

const DAY_WORDS = [...DAY_BY_WORD.keys()].sort((a, b) => b.length - a.length);
const DAY_PATTERN = DAY_WORDS.join("|");
const CLOSED_WORD = /^(stängt|stangt|closed)$/i;

const HOURS_RE = new RegExp(
  // day, optionally a range of days, then a separator, then a time range or a
  // word meaning closed.
  `\\b(${DAY_PATTERN})\\b\\.?` +
    `(?:\\s*[-–—]\\s*|\\s+(?:till|to|t\\.o\\.m\\.?)\\s+)?(?:\\b(${DAY_PATTERN})\\b\\.?)?` +
    `[\\s|:.]{0,6}` +
    `(?:(\\d{1,2})[:.](\\d{2})\\s*[-–—]\\s*(\\d{1,2})[:.](\\d{2})|(stängt|stangt|closed))`,
  "gi",
);

function clock(hour: string, minute: string): string | null {
  const h = Number(hour);
  const m = Number(minute);
  if (!Number.isFinite(h) || !Number.isFinite(m) || h > 24 || m > 59) return null;
  return `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}`;
}

// --- printed branch addresses ----------------------------------------------

/** A map the page embeds or links to. The signal that an address beside it is
 *  meant to be FOUND, rather than mentioned in a sentence. */
const MAP_TARGET =
  /<iframe[^>]+src=["'][^"']*(?:google\.[a-z.]+\/maps|maps\.google|openstreetmap\.org|kartor\.eniro)[^"']*["']|<a[^>]+href=["'][^"']*(?:google\.[a-z.]+\/maps|maps\.app\.goo\.gl)[^"']*["']/gi;

/**
 * One printed line that is a whole Swedish address: a street with a house
 * number, a postcode, and optionally the town. Anchored on purpose - the loose
 * "a postcode appears somewhere" reading matched the phone number
 * "08-545 875 00" on the dentist's contact page.
 */
const PRINTED_ADDRESS =
  /^([\p{L}][\p{L}.'’\-\s]{2,48}?\s+\d+\s?[A-Za-z]?)\s*[,\s]\s*(\d{3}\s?\d{2})\s*,?\s*([\p{Lu}][\p{L}\-\s]{1,30})?$/u;

/** A line about reaching someone, not about where they are. */
const CONTACT_WORD = /\b(tel|telefon|phone|fax|mobil|e-?post|mail)\b/i;
const PRINTED_PHONE = /(?:tel|telefon|phone)[:.\s]*((?:\+46|0)[\d\s\-()]{6,16}\d)/i;

export type DetectedBranch = {
  name?: string;
  street: string;
  postalCode: string;
  city?: string;
  phone?: string;
  /** Where the address sits in the document, so the band holding it is not
   *  also imported as a call-to-action band saying the same thing. */
  at: number;
};

/**
 * The addresses a page PRINTS, read from its own markup.
 *
 * The importer's `location` block has only ever been built from a declared
 * address - schema.org, OpenGraph, or the scraped contact block - which is one
 * address, and most small sites declare none. A restaurant with two places
 * prints both, each next to its own map, and both arrived as call-to-action
 * bands whose headline was the whole address run together with the phone
 * number and the opening hours (backlog 2643, moggesushi).
 *
 * Every field is the source's own text. The reader is deliberately narrow: an
 * address only counts when a map sits within a short window of it, the line
 * has to parse as a whole address on its own, and a line naming a telephone or
 * an e-mail is skipped rather than parsed. Returns the addresses in document
 * order, deduplicated by street and postcode.
 */
export function detectPrintedBranches(html: string): DetectedBranch[] {
  const { html: body, offset } = bodyOf(html);
  const chrome = chromeRanges(body);
  const out = new Map<string, DetectedBranch>();
  for (const map of body.matchAll(MAP_TARGET)) {
    const mapAt = map.index ?? 0;
    if (inChrome(mapAt, chrome)) continue;
    // The address is printed above its map far more often than below it, so the
    // window leans backwards. Both sides are read: two of the eleven client
    // sites put the caption under the frame.
    const from = Math.max(0, mapAt - 1200);
    const window = body.slice(from, mapAt + 600);
    const lines = window
      .replace(/<br\s*\/?>/gi, "\n")
      .replace(/<\/(p|div|td|h[1-6]|li|a|strong|em|font|span)>/gi, "\n")
      .replace(/<[^>]+>/g, " ")
      .split("\n")
      .map((line) => decode(line).replace(/\s+/g, " ").trim())
      .filter(Boolean);
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      if (CONTACT_WORD.test(line)) continue;
      const parsed = line.match(PRINTED_ADDRESS);
      if (!parsed) continue;
      const above = lines.slice(Math.max(0, i - 3), i);
      const street = parsed[1].trim().slice(0, 120);
      const postalCode = parsed[2].replace(/\s+/, " ");
      const key = `${street.toLowerCase()}|${postalCode}`;
      if (out.has(key)) continue;
      const city = (parsed[3] ?? "").trim();
      // The name is the nearest line above that is neither an address nor a way
      // of contacting someone: "MOGGE SUSHI ÖSTERMALM" over its own address.
      const name = [...above]
        .reverse()
        .find(
          (candidate) =>
            !CONTACT_WORD.test(candidate) &&
            !PRINTED_ADDRESS.test(candidate) &&
            candidate.length > 2 &&
            candidate.length <= 60,
        );
      out.set(key, {
        ...(name ? { name: name.slice(0, 60) } : {}),
        street,
        postalCode,
        ...(city ? { city: city.slice(0, 80) } : {}),
        ...(above.map((l) => l.match(PRINTED_PHONE)?.[1]).find(Boolean)
          ? { phone: above.map((l) => l.match(PRINTED_PHONE)?.[1]).find(Boolean)!.trim().slice(0, 40) }
          : {}),
        // The postcode's own digits, which survive entity decoding, so branches
        // come back in the order the page prints them rather than in map order.
        at: offset + from + Math.max(0, window.indexOf(postalCode)),
      });
    }
  }
  return [...out.values()].sort((a, b) => a.at - b.at);
}

export type DetectedOpeningHours = {
  heading?: string;
  at?: number;
  days: Array<{ day: OpeningDayKey; closed: boolean; open?: string; close?: string }>;
  /** The source lines this was read from, so the prose bands can claim them and
   *  the page does not print its hours twice. */
  claimed: string[];
};

/** A heading that announces hours, used as the section's own heading rather
 *  than the label we would otherwise invent. */
const HOURS_HEADING = /(öppettider|oppettider|öppet\b|opening\s+hours|our\s+hours|hours)/i;

/**
 * Opening hours a page prints as ordinary text.
 *
 * The document is flattened to one line per element so a day in its own cell
 * stays next to the time in the cell beside it, which is how nearly every one
 * of these tables is marked up. A day range ("Mån - Fre 08:00-17:00") expands
 * across the days it names; a day named twice keeps the FIRST reading, because
 * a page that lists Monday in a table and again in a footer strip means the
 * table.
 *
 * Returns null below two distinct days with a time. One day and one range is a
 * sentence about a holiday, not a week.
 */
export function detectOpeningHours(html: string): DetectedOpeningHours | null {
  const body = bodyOf(html);
  const chrome = chromeRanges(html);
  // One line per element, so "Måndag" and "08:00-18:00" in adjacent cells are
  // adjacent lines rather than one run - and so a day in one paragraph cannot
  // pair with a time three paragraphs later.
  const found = new Map<OpeningDayKey, { open?: string; close?: string }>();
  const claimed: string[] = [];
  let at: number | undefined;

  // Chrome is blanked, not skipped afterwards: nearly every one of these sites
  // repeats its hours in the site footer, so scanning the whole document gave
  // every page an opening-hours block and cost more in precision than the one
  // real block gained. A footer's hours belong to the site, not to this page.
  let scanned = body.html;
  for (const [start, end] of chromeRanges(body.html)) {
    scanned = scanned.slice(0, start) + " ".repeat(end - start) + scanned.slice(end);
  }

  const flat = decode(scanned.replace(/<[^>]+>/g, "\n"))
    .replace(/[   ]/g, " ")
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
    .join(" | ");

  for (const m of flat.matchAll(HOURS_RE)) {
    const from = DAY_BY_WORD.get(m[1].toLowerCase());
    if (!from) continue;
    const to = m[2] ? DAY_BY_WORD.get(m[2].toLowerCase()) : undefined;
    const closed = Boolean(m[7]) && CLOSED_WORD.test(m[7]);
    const open = m[3] && m[4] ? clock(m[3], m[4]) : null;
    const close = m[5] && m[6] ? clock(m[5], m[6]) : null;
    if (!closed && (!open || !close)) continue;

    const start = DAY_ORDER.indexOf(from);
    const endIndex = to ? DAY_ORDER.indexOf(to) : start;
    // A backwards range ("Sön - Mån") wraps the week; a range longer than the
    // week is not a range at all.
    const span: OpeningDayKey[] = [];
    for (let i = 0; i < DAY_ORDER.length; i++) {
      const day = DAY_ORDER[(start + i) % DAY_ORDER.length];
      span.push(day);
      if (DAY_ORDER[(start + i) % DAY_ORDER.length] === DAY_ORDER[endIndex]) break;
    }
    for (const day of span) {
      if (found.has(day)) continue;
      found.set(day, closed ? {} : { open: open ?? undefined, close: close ?? undefined });
    }
    claimed.push(m[0].trim());
  }

  const withTime = [...found.values()].filter((v) => v.open && v.close).length;
  if (found.size < 2 || withTime < 1) return null;

  // The heading that announces them, and where it sat, so the block lands where
  // the source put its hours instead of at the end of the ladder.
  const headingMatch = [...body.html.matchAll(/<h([1-6])\b[^>]*>([\s\S]*?)<\/h\1>/gi)].find((h) =>
    HOURS_HEADING.test(text(h[2])),
  );
  const heading = headingMatch ? text(headingMatch[2]).slice(0, 80) : undefined;
  if (headingMatch) {
    const headingAt = body.offset + (headingMatch.index ?? 0);
    if (!inChrome(headingAt, chrome)) at = headingAt;
  }

  return {
    ...(heading ? { heading } : {}),
    ...(at !== undefined ? { at } : {}),
    days: DAY_ORDER.map((day) => {
      const hit = found.get(day);
      return hit && hit.open && hit.close
        ? { day, closed: false, open: hit.open, close: hit.close }
        : { day, closed: true };
    }),
    claimed,
  };
}


// --- a roster of people ------------------------------------------------------
//
// Why this exists, measured. `teamMembersUnder` is gated on a heading it
// recognises ("Vårt team", "Medarbetare", "Our team") plus subheadings under
// it. A real staff page usually satisfies neither: the dentist's roster is
// titled "Vi som jobbar här" and every person is their own repeated card, so
// the page imported as a highlights strip, a gallery of eight faces and a
// paragraph - 0% body fidelity against a truth label of one `team` block
// (backlog 2643). Eight portraits torn away from the eight names beside them is
// also the worst kind of loss: the page still looks full and says nothing.
//
// The gate here is STRUCTURE plus the shape of a person's name, never wording,
// which is the whole point: a roster in Polish, or titled "Vilka är vi", reads
// exactly the same to this.

/**
 * Where the element opening at `at` closes, by depth.
 *
 * Returns the end of the document when the tag never balances, which is the
 * safe direction: an unbalanced roster card is one that ran to the end of the
 * page anyway.
 */
function closingTagEnd(html: string, at: number, tag: string): number {
  const pattern = new RegExp(`<(/?)${tag}\\b[^>]*>`, "gi");
  pattern.lastIndex = at;
  let depth = 0;
  for (let m = pattern.exec(html); m; m = pattern.exec(html)) {
    if (m[1] === "/") {
      depth--;
      if (depth === 0) return m.index + m[0].length;
    } else if (!/\/>\s*$/.test(m[0])) {
      depth++;
    }
  }
  return html.length;
}

/** Markers that mean a picture is furniture rather than a portrait. */
const TEAM_NON_PHOTO = /(icon|logo|sprite|favicon|badge|symbol|pixel|spacer|placeholder)/i;

/** Lowercase particles a Swedish or European surname legitimately carries. */
const NAME_PARTICLE = /^(af|av|de|del|della|der|di|do|dos|du|la|le|van|von|zu)$/;

/**
 * Does this read as a person's NAME rather than a product or a sentence?
 *
 * Two to four words, each starting with a capital (a hyphenated surname counts
 * once), no digits and no sentence punctuation. It is what separates "Ahmed
 * Al-Karwi" from "Restoring volume and creating definition", and it is doing
 * the work a keyword list would otherwise do badly in one language.
 */
/**
 * Two limits here are deliberate, and both were raised in review (2026-08-18).
 *
 * A ONE-WORD name is refused. A mononym is a real name, but a single
 * capitalised word is also every product, service and category label on the
 * web, and this gate is the only thing standing between a promo row and three
 * invented members of staff. The cost is a roster that lists first names only.
 *
 * A script with NO CASE - Arabic, Hebrew, CJK, Thai - is refused too, because
 * the capital test cannot see a capital there. A cased script whose capitals
 * differ from its lowercase, Cyrillic and Greek included, passes normally. The
 * importer's own copy speaks sv/en/pl and no corpus page exercises the
 * caseless path; loosening it without evidence would trade a missing roster for
 * an invented one, which is the worse of the two.
 */
export function looksLikePersonName(value: string): boolean {
  const text = value.trim();
  if (text.length < 4 || text.length > 40) return false;
  if (/[0-9]/.test(text)) return false;
  // Punctuation ANYWHERE, not only at the end. A screen-reader-only heading
  // often reads "Carolina Carholt, Tandläkare", which is three capitalised
  // words and would otherwise pass as a name with the job title glued on.
  if (/[.!?,:;]/.test(text)) return false;
  const words = text.split(/\s+/);
  if (words.length < 2 || words.length > 4) return false;
  return words.every((word) => {
    if (NAME_PARTICLE.test(word)) return true;
    const first = word[0];
    return first !== undefined && first === first.toLocaleUpperCase() && first !== first.toLocaleLowerCase();
  });
}

/** A line under a name that reads as a job title: short, and not a sentence.
 *  A trailing full stop is allowed because "Leg. Tandläkare" carries one. */
function looksLikeJobTitle(value: string): boolean {
  return value.length >= 2 && value.length <= 40 && !/[!?]$/.test(value);
}

export type DetectedTeam = {
  at: number;
  heading?: string;
  members: Array<{ name: string; role?: string; photoUrl?: string }>;
};

/** Below three, a repeat is a coincidence. A two-person business writes its two
 *  people as prose far more often than as a card grid. */
const TEAM_MIN_MEMBERS = 3;

/**
 * A roster of people, read from a repeated card rather than from a heading.
 *
 * The card is found the same way `findRepeat` finds one: three or more sibling
 * elements sharing their first class token. Inside each, the name is the FIRST
 * heading that reads as a person's name - which matters, because a real page
 * often carries two headings per card (a screen-reader-only "Carolina Carholt,
 * Tandläkare" above the visible "Carolina Carholt") and the tidy one is not
 * always first in the markup.
 *
 * Two acceptance conditions beyond the name shape, either of which is enough,
 * because a services grid can also be Title Case:
 *
 *   • a role line REPEATS across cards ("Leg. Tandläkare" under three of the
 *     eight), which a list of distinct services essentially never does; or
 *   • every card carries a photo, which is what a roster is.
 */
export function detectTeamCards(html: string, baseUrl: string): DetectedTeam | null {
  const body = bodyOf(html);
  const chrome = chromeRanges(body.html);

  const byClass = new Map<string, number[]>();
  for (const m of body.html.matchAll(/<(article|div|li)\b[^>]*class=["']([^"']+)["'][^>]*>/gi)) {
    const first = m[2].trim().split(/\s+/)[0];
    if (!first) continue;
    const at = m.index ?? 0;
    if (inChrome(at, chrome)) continue;
    const key = `${m[1].toLowerCase()}.${first}`;
    const seen = byClass.get(key);
    if (seen) seen.push(at);
    else byClass.set(key, [at]);
  }

  let best: DetectedTeam | null = null;
  for (const [key, hits] of byClass) {
    if (hits.length < TEAM_MIN_MEMBERS) continue;
    const members: Array<{ name: string; role?: string; photoUrl?: string }> = [];
    const roles: string[] = [];
    let withPhoto = 0;

    // The LAST card has no next sibling to end it, so slicing to the end of the
    // document hands it everything after the roster - which is how the eighth
    // dentist, the one with no portrait yet, was given the page's partner logo
    // as her photograph. Its own closing tag is where it ends: a width estimated
    // from the cards before it only happens to exclude the logo, and would still
    // have reached an ordinary photograph sitting a little closer. (2643)
    const tag = key.split(".")[0];
    for (let i = 0; i < hits.length; i++) {
      const end = hits[i + 1] ?? closingTagEnd(body.html, hits[i], tag);
      const card = body.html.slice(hits[i], end);
      const headings = [...card.matchAll(/<h([1-6])\b[^>]*>([\s\S]*?)<\/h\1>/gi)].map((h) =>
        text(h[2]),
      );
      const name = headings.find((h) => looksLikePersonName(h));
      // Every card has to be a person. A grid where the fourth tile is "Join
      // the team" or a service is not a roster, and taking the first three
      // would publish a staff list that is missing whoever came after.
      if (!name) break;
      const lines = card
        .replace(/<h([1-6])\b[^>]*>[\s\S]*?<\/h\1>/gi, " ")
        .replace(/<a\b[^>]*>[\s\S]*?<\/a>/gi, " ")
        .split(/<\/(?:p|div|span|li|td)\s*>|<br\s*\/?>/i)
        .map((line) => text(line))
        .filter((line) => line.length > 0 && line !== name);
      const role = lines.find((line) => looksLikeJobTitle(line));
      // A logo or an icon is not somebody's face. Same list the band builders
      // use, and it earns its keep here: the roster's last card fell back to the
      // group's partner logo before this.
      const photo = [...card.matchAll(/<img\b[^>]*>/gi)]
        .filter((img) => !TEAM_NON_PHOTO.test(img[0]))
        .map((img) => img[0].match(/\ssrc=["']([^"']+)["']/i)?.[1])
        .find((src): src is string => Boolean(src));
      let photoUrl: string | undefined;
      if (photo) {
        const abs = absolute(decode(photo), baseUrl);
        if (abs && !/^data:/i.test(abs) && !/\.svg(?:$|[?#])/i.test(abs)) {
          photoUrl = abs;
          withPhoto++;
        }
      }
      if (role) roles.push(role);
      members.push({ name, ...(role ? { role } : {}), ...(photoUrl ? { photoUrl } : {}) });
    }

    if (members.length < TEAM_MIN_MEMBERS || members.length !== hits.length) continue;

    // A services grid can be Title Case too, and a three-card promo row with a
    // photo on each tile passes everything above: "Botox Treatments" / "Filler
    // Treatments" / "Skin Care" imported as three members of staff, which is not
    // a layout mistake but invented people on a real business's website.
    //
    // What separates them is that a product range shares a NOUN and a roster
    // does not. More than half the names carrying one word in common is a
    // catalogue. Half rather than any, so two colleagues who share a surname
    // still arrive.
    const wordShare = new Map<string, number>();
    for (const member of members) {
      for (const word of new Set(
        member.name
          .toLocaleLowerCase()
          .split(/[\s-]+/)
          .filter((w) => w.length >= 3),
      )) {
        wordShare.set(word, (wordShare.get(word) ?? 0) + 1);
      }
    }
    if ([...wordShare.values()].some((n) => n * 2 > members.length)) continue;

    const roleRepeats = roles.length !== new Set(roles).size;
    if (!roleRepeats && withPhoto < members.length) continue;
    // The biggest roster on the page wins: a staff grid nested inside an outer
    // wrapper matches on both class tokens, and the inner one is the people.
    if (!best || members.length > best.members.length) {
      const at = hits[0];
      // The roster's own title: the nearest heading above the first card that
      // is NOT one of the names. The dentist page calls it "Vi som jobbar här",
      // which no keyword list would have found and which is the owner's word
      // for it.
      const above = [...body.html.matchAll(/<h([1-3])\b[^>]*>([\s\S]*?)<\/h\1>/gi)]
        .filter((h) => (h.index ?? 0) < at)
        .map((h) => text(h[2]))
        .filter((h) => h.length > 1 && h.length <= 80 && !looksLikePersonName(h))
        .pop();
      best = { at: body.offset + at, ...(above ? { heading: above } : {}), members };
    }
  }

  return best;
}
