// GENERATED by scripts/mirror-import.ts from HH-Studio/simple-site-builder:lib/net/url.ts
// Do not edit. Run `bun scripts/mirror-import.ts --sync-from-app <appRoot>`.

// ---------------------------------------------------------------------------
// URL guards shared by the import flows (Convex actions) and the static-export
// route (Next). Pure + dependency-free so it is trivially unit-testable and
// usable from both runtimes (default Convex V8 + edge-runtime - no node:dns).
//
// SSRF posture: we reject every URL whose host is an IP literal in a private /
// reserved range, for BOTH IPv4 and IPv6 - including the forms a naive hostname
// regex misses: `[::1]`, `[fd00::1]` (ULA), `[fe80::1]` (link-local) and the
// IPv4-mapped `[::ffff:169.254.169.254]`. WHATWG `URL` normalises IPv4 written
// in decimal / hex / octal into dotted-decimal *before* we classify it, so those
// encodings are not a bypass. What we CANNOT do in this runtime is resolve a DNS
// name to its IP, so a public hostname that resolves to a private address
// (DNS-rebinding / attacker-controlled A record) is a documented residual - the
// shared `safeFetch` mitigates the common literal-IP redirect variant by
// re-validating every redirect hop. See lib/net/safeFetch.ts + BACKLOG.md.
// ---------------------------------------------------------------------------

/** `decodeURIComponent` that cannot end an import.
 *
 *  A single malformed escape anywhere in a crawled page — `tel:%ZZ`, a link to
 *  `/50%rabatt`, a Google Fonts URL with a stray `%` — throws a `URIError`, and
 *  every caller below sits inside the import's parse pass, so one broken link
 *  on one page aborted the whole site. Found by running the CLI over a real
 *  customer export (2026-08-16). The raw text is the honest fallback; callers
 *  validate the shape afterwards. */
export function safeDecodeURIComponent(value: string): string {
  try {
    return decodeURIComponent(value);
  } catch {
    return value;
  }
}

/** Parse a dotted-quad IPv4 string into its 4 bytes, or null if it is not one.
 *  Strict: exactly four 1–3 digit octets, each 0–255 (no octal/hex - callers see
 *  the already-normalised `URL.hostname`). */
function ipv4ToBytes(host: string): number[] | null {
  const parts = host.split(".");
  if (parts.length !== 4) return null;
  const bytes: number[] = [];
  for (const p of parts) {
    if (!/^\d{1,3}$/.test(p)) return null;
    const n = Number(p);
    if (n > 255) return null;
    bytes.push(n);
  }
  return bytes;
}

/** Parse an IPv6 literal (no surrounding brackets) into its 16 bytes, or null.
 *  Handles `::` zero-compression and a trailing embedded IPv4 (`::ffff:1.2.3.4`)
 *  and drops a zone id (`fe80::1%eth0`). */
function ipv6ToBytes(input: string): number[] | null {
  let s = input.toLowerCase();
  const pct = s.indexOf("%");
  if (pct !== -1) s = s.slice(0, pct); // strip zone id; classify the address
  if (s.length === 0 || s.includes(":::")) return null;

  // A trailing embedded IPv4 becomes the final two hextets.
  if (s.includes(".")) {
    const m = s.match(/^(.*:)([0-9.]+)$/);
    if (!m) return null;
    const v4 = ipv4ToBytes(m[2]);
    if (!v4) return null;
    const hi = ((v4[0] << 8) | v4[1]).toString(16);
    const lo = ((v4[2] << 8) | v4[3]).toString(16);
    s = m[1] + hi + ":" + lo;
  }

  const halves = s.split("::");
  if (halves.length > 2) return null;

  const toGroups = (str: string): number[] | null => {
    if (str === "") return [];
    const out: number[] = [];
    for (const g of str.split(":")) {
      if (!/^[0-9a-f]{1,4}$/.test(g)) return null;
      out.push(parseInt(g, 16));
    }
    return out;
  };

  const head = toGroups(halves[0]);
  if (head === null) return null;

  let groups: number[];
  if (halves.length === 2) {
    const tail = toGroups(halves[1]);
    if (tail === null) return null;
    const missing = 8 - head.length - tail.length;
    if (missing < 0) return null;
    groups = [...head, ...new Array(missing).fill(0), ...tail];
  } else {
    groups = head;
  }
  if (groups.length !== 8) return null;

  const bytes: number[] = [];
  for (const g of groups) {
    if (g < 0 || g > 0xffff) return null;
    bytes.push((g >> 8) & 0xff, g & 0xff);
  }
  return bytes;
}

/** True for an IPv4 in any range that must never be fetched server-side. Covers
 *  the SSRF-critical blocks (loopback / RFC1918 / link-local incl. cloud metadata
 *  169.254.169.254 / CGNAT) plus TEST-NET / benchmark / multicast / reserved. */
function isReservedIPv4(b: number[]): boolean {
  const [a, c, d] = b;
  if (a === 0) return true; //                0.0.0.0/8   "this network"
  if (a === 10) return true; //               10.0.0.0/8  private
  if (a === 127) return true; //              127.0.0.0/8 loopback
  if (a === 100 && c >= 64 && c <= 127) return true; // 100.64/10 CGNAT
  if (a === 169 && c === 254) return true; //  169.254/16 link-local (metadata)
  if (a === 172 && c >= 16 && c <= 31) return true; // 172.16/12 private
  if (a === 192 && c === 0 && d === 0) return true; // 192.0.0/24 IETF protocol
  if (a === 192 && c === 0 && d === 2) return true; // 192.0.2/24 TEST-NET-1
  if (a === 192 && c === 168) return true; //  192.168/16 private
  if (a === 198 && (c === 18 || c === 19)) return true; // 198.18/15 benchmark
  if (a === 198 && c === 51 && d === 100) return true; // 198.51.100/24 TEST-NET-2
  if (a === 203 && c === 0 && d === 113) return true; // 203.0.113/24 TEST-NET-3
  if (a >= 224) return true; //                224/4 multicast + 240/4 reserved
  return false;
}

/** True for an IPv6 in any private / reserved range.
 *
 *  Every form that CARRIES an IPv4 address inside it is unwrapped and the
 *  embedded address classified instead: IPv4-mapped, IPv4-compatible, NAT64,
 *  6to4 and Teredo. Each of those is a real route to the embedded address, so
 *  reading only the IPv6 prefix would let `64:ff9b::a9fe:a9fe` through as an
 *  ordinary global address when it is the cloud metadata service with a
 *  translator in front of it. Kept identical to `reserved6` in
 *  `lib/net/publicUrlScript.ts` and to `isReservedIPv6` in
 *  `services/render-adapter/src/publicAddress.ts`. */
function isReservedIPv6(b: number[]): boolean {
  // IPv4-mapped ::ffff:a.b.c.d → classify the embedded IPv4.
  if (b.slice(0, 10).every((x) => x === 0) && b[10] === 0xff && b[11] === 0xff) {
    return isReservedIPv4([b[12], b[13], b[14], b[15]]);
  }
  // NAT64 64:ff9b::/96 (RFC 6052): the last four bytes ARE an IPv4 address and
  // a translator carries the packet to it.
  if (
    b[0] === 0x00 &&
    b[1] === 0x64 &&
    b[2] === 0xff &&
    b[3] === 0x9b &&
    b.slice(4, 12).every((x) => x === 0)
  ) {
    return isReservedIPv4([b[12], b[13], b[14], b[15]]);
  }
  // 6to4 2002::/16 (RFC 3056): bytes 2-5 are the IPv4 of the tunnel endpoint.
  if (b[0] === 0x20 && b[1] === 0x02) {
    return isReservedIPv4([b[2], b[3], b[4], b[5]]);
  }
  // Teredo 2001::/32 (RFC 4380): bytes 4-7 are the server's IPv4, and the last
  // four are the client's, obfuscated by XOR with 0xff. `2001:db8::/32` is the
  // documentation prefix and is NOT this - it has `0d b8` where Teredo has two
  // zero bytes.
  if (b[0] === 0x20 && b[1] === 0x01 && b[2] === 0x00 && b[3] === 0x00) {
    if (isReservedIPv4([b[4], b[5], b[6], b[7]])) return true;
    return isReservedIPv4([b[12] ^ 0xff, b[13] ^ 0xff, b[14] ^ 0xff, b[15] ^ 0xff]);
  }
  // ::/96 is entirely special-use (::, ::1 loopback, ::a.b.c.d) - never public.
  if (b.slice(0, 12).every((x) => x === 0)) return true;
  const b0 = b[0];
  const b1 = b[1];
  if (b0 === 0xff) return true; //                       ff00::/8  multicast
  if ((b0 & 0xfe) === 0xfc) return true; //              fc00::/7  unique-local
  if (b0 === 0xfe && (b1 & 0xc0) === 0x80) return true; // fe80::/10 link-local
  if (b0 === 0xfe && (b1 & 0xc0) === 0xc0) return true; // fec0::/10 site-local
  return false;
}

/** True for hosts that must never be fetched server-side (SSRF guard). Accepts a
 *  bare hostname (as produced by `URL.hostname`, so IPv6 keeps its brackets) and
 *  classifies IP literals; non-IP names are only blocked when they are obviously
 *  internal (`localhost`, `*.local`, `*.internal`) - DNS is not resolved here. */
export function isPrivateHostname(host: string): boolean {
  let h = host.trim().toLowerCase();
  if (h.endsWith(".")) h = h.slice(0, -1); // FQDN root dot
  if (h.startsWith("[") && h.endsWith("]")) h = h.slice(1, -1); // IPv6 brackets
  if (h === "") return true;

  if (h === "localhost" || h.endsWith(".localhost")) return true;

  const v4 = ipv4ToBytes(h);
  if (v4) return isReservedIPv4(v4);

  const v6 = ipv6ToBytes(h);
  if (v6) return isReservedIPv6(v6);

  // A DNS name we cannot resolve in this runtime: block the obviously-internal
  // suffixes (mDNS / cloud-internal, incl. metadata.google.internal).
  if (h.endsWith(".local") || h.endsWith(".internal")) return true;
  return false;
}

/** True when `host` is an IP literal rather than a DNS name. Accepts a bare
 *  hostname in the shape `URL.hostname` produces, so an IPv6 literal still has
 *  its brackets. It says nothing about whether the address is public - that is
 *  `isPrivateHostname`'s job - only that there is no name here to resolve, so a
 *  caller that refuses a dotless LAN name must not refuse this too. */
export function isIpLiteralHostname(host: string): boolean {
  let h = host.trim().toLowerCase();
  if (h.endsWith(".")) h = h.slice(0, -1);
  if (h.startsWith("[") && h.endsWith("]")) h = h.slice(1, -1);
  if (h === "") return false;
  return ipv4ToBytes(h) !== null || ipv6ToBytes(h) !== null;
}

/** True when a RESOLVED address must never be connected to. Unlike
 *  `isPrivateHostname` this fails CLOSED on anything it cannot parse as an IP:
 *  its only caller is the DNS-pinning lookup in `convex/netFetch.ts`, where the
 *  input is always a literal address returned by `dns.lookup`, so an
 *  unparseable value means something is wrong and must not be dialled.
 *
 *  This is the half `isPrivateHostname` structurally cannot do — it classifies
 *  IP *literals* in a URL, and a hostname whose A record points at 127.0.0.1
 *  passes it. Blocking that requires resolving first, which requires node:dns,
 *  which is why this pairs with a Node-runtime action. (Backlog 0331.) */
export function isBlockedAddress(ip: string): boolean {
  const h = ip.trim().toLowerCase().replace(/^\[|\]$/g, "");
  const v4 = ipv4ToBytes(h);
  if (v4) return isReservedIPv4(v4);
  const v6 = ipv6ToBytes(h);
  if (v6) return isReservedIPv6(v6);
  return true; // not an address we can classify - fail closed
}

/** Filter a DNS answer down to the addresses that may be connected to.
 *
 *  Inspects the WHOLE answer rather than the first record: a rebinding domain
 *  can return a public address alongside `127.0.0.1`, and picking the first
 *  entry would let the blocked one through on the next connection attempt.
 *  Returns an empty array when nothing survives, which the caller must treat as
 *  a hard failure — never as "fall back to unfiltered resolution". */
export function allowedAddresses<T extends { address: string }>(
  answer: readonly T[],
): T[] {
  return answer.filter((a) => !isBlockedAddress(a.address));
}

/** Parse a string into a public http(s) URL, or null. Rejects every other
 *  protocol (file:, data:, javascript:, ftp:, …), embedded credentials
 *  (`http://user@host`) and private / reserved hosts. */
export function parseHttpUrl(raw: string): URL | null {
  let u: URL;
  try {
    u = new URL(raw);
  } catch {
    return null;
  }
  if (u.protocol !== "http:" && u.protocol !== "https:") return null;
  if (u.username !== "" || u.password !== "") return null;
  if (isPrivateHostname(u.hostname)) return null;
  return u;
}

/** True when `raw` is a safe, public http(s) URL. */
export function isHttpUrl(raw: string): boolean {
  return parseHttpUrl(raw) !== null;
}
