// GENERATED by scripts/mirror-import.ts from HH-Studio/simple-site-builder:lib/brand.ts
// Do not edit. Run `bun scripts/mirror-import.ts --sync-from-app <appRoot>`.

/** Product brand name shown to users. Renamed from "Snabbsite" to
 *  "Snabbsite" by owner directive 2026-08-21 (plan
 *  docs/plans/verifying/P1-2026-08-21-rename-snabbsajt-to-snabbsite.md).
 *  Still swappable from this single constant. The domain (snabbsajt.com,
 *  switching to snabbsite.com later) and internal code/table names are
 *  unaffected. */
export const BRAND_NAME = "Snabbsite";
