// GENERATED by scripts/mirror-import.ts from HH-Studio/simple-site-builder:lib/sections/openingHours.ts
// Do not edit. Run `bun scripts/mirror-import.ts --sync-from-app <appRoot>`.

// Weekday names and the open/closed vocabulary for the opening-hours section.
//
// Deliberately a lib data module rather than a `lib/i18n.ts` dict entry: these
// strings belong to the CUSTOMER'S site, not the admin UI, and they are read by
// both worlds - `components/site-sections/opening-hours/OpeningHours.tsx`
// (rendered site) and `components/editor/inline/InlineHours.tsx` (the inline
// editor drawn on the canvas). Living here keeps the two-world boundary intact:
// a site section imports plain data, never anything from `components/ui/`.
//
// They used to be two verbatim copies, so the editor and the rendered site could
// drift apart mid-edit - the row you typed and the row you published would have
// disagreed on what day it was (backlog 0542).

// Relative, not the "@/" alias, so a Convex function can import this module:
// the importers under convex/import/* run through the Convex bundler and reach
// lib/ by relative path (same reason `lib/sections/registry.ts` does).
import type { Locale } from "../../../lib/i18n";
import { toAdminDictLocale, type SiteLocale } from "../../../lib/i18n/site-locales";

export type DayKey = "mon" | "tue" | "wed" | "thu" | "fri" | "sat" | "sun";

/** Monday-first, matching how every SITE_LOCALE's calendar reads. */
export const DAY_KEYS: readonly DayKey[] = [
  "mon",
  "tue",
  "wed",
  "thu",
  "fri",
  "sat",
  "sun",
];

/** Visitor-facing: a published site renders these to its guests, so the table
 *  is keyed by SITE_LOCALE (twelve languages), not by the three-language admin
 *  dictionary. A German bakery's table used to read "Monday / Tuesday" inside an
 *  otherwise German page. Capitalisation follows each language's own convention
 *  (German and Turkish capitalise weekday names; Danish, Norwegian, Finnish,
 *  French and Spanish do not), because a table of proper-cased Danish weekdays
 *  reads as a translation, not as Danish. Arabic and Persian have no case, and
 *  their week conventionally starts on Saturday rather than Monday.
 *
 *  The order stays Monday-first anyway, and that is a decision rather than an
 *  omission (2026-08-08). These are SWEDISH businesses: a bakery in Rinkeby
 *  keeps a Swedish week, is busy Monday to Friday and shut on Sunday, and its
 *  Arabic-speaking customers live that same week. Rotating the table to
 *  Saturday-first would move the days that matter into the middle of the list
 *  to satisfy a calendar convention from a country the business is not in.
 *  Revisit only if Snabbsite sells outside Sweden. */
export const WEEKDAYS: Record<SiteLocale, Record<DayKey, string>> = {
  sv: {
    mon: "Måndag",
    tue: "Tisdag",
    wed: "Onsdag",
    thu: "Torsdag",
    fri: "Fredag",
    sat: "Lördag",
    sun: "Söndag",
  },
  en: {
    mon: "Monday",
    tue: "Tuesday",
    wed: "Wednesday",
    thu: "Thursday",
    fri: "Friday",
    sat: "Saturday",
    sun: "Sunday",
  },
  pl: {
    mon: "Poniedziałek",
    tue: "Wtorek",
    wed: "Środa",
    thu: "Czwartek",
    fri: "Piątek",
    sat: "Sobota",
    sun: "Niedziela",
  },
  de: {
    mon: "Montag",
    tue: "Dienstag",
    wed: "Mittwoch",
    thu: "Donnerstag",
    fri: "Freitag",
    sat: "Samstag",
    sun: "Sonntag",
  },
  da: {
    mon: "mandag",
    tue: "tirsdag",
    wed: "onsdag",
    thu: "torsdag",
    fri: "fredag",
    sat: "lørdag",
    sun: "søndag",
  },
  no: {
    mon: "mandag",
    tue: "tirsdag",
    wed: "onsdag",
    thu: "torsdag",
    fri: "fredag",
    sat: "lørdag",
    sun: "søndag",
  },
  fi: {
    mon: "maanantai",
    tue: "tiistai",
    wed: "keskiviikko",
    thu: "torstai",
    fri: "perjantai",
    sat: "lauantai",
    sun: "sunnuntai",
  },
  fr: {
    mon: "lundi",
    tue: "mardi",
    wed: "mercredi",
    thu: "jeudi",
    fri: "vendredi",
    sat: "samedi",
    sun: "dimanche",
  },
  es: {
    mon: "lunes",
    tue: "martes",
    wed: "miércoles",
    thu: "jueves",
    fri: "viernes",
    sat: "sábado",
    sun: "domingo",
  },
  tr: {
    mon: "Pazartesi",
    tue: "Salı",
    wed: "Çarşamba",
    thu: "Perşembe",
    fri: "Cuma",
    sat: "Cumartesi",
    sun: "Pazar",
  },
  ar: {
    mon: "الاثنين",
    tue: "الثلاثاء",
    wed: "الأربعاء",
    thu: "الخميس",
    fri: "الجمعة",
    sat: "السبت",
    sun: "الأحد",
  },
  fa: {
    mon: "دوشنبه",
    tue: "سه‌شنبه",
    wed: "چهارشنبه",
    thu: "پنجشنبه",
    fri: "جمعه",
    sat: "شنبه",
    sun: "یکشنبه",
  },
};

/** Visitor-facing: `open`/`closed` label the day's state on the published site
 *  (and on the canvas, which must render what the visitor will see), so this
 *  table is keyed by SITE_LOCALE like `WEEKDAYS`. Kept separate from
 *  `HOURS_EDITOR_LABELS` on purpose — that split is what stops an owner-only
 *  string from silently needing twelve translations, and stops a visitor-facing
 *  one from silently falling back to English. */
export const HOURS_STATUS_LABELS: Record<
  SiteLocale,
  { open: string; closed: string }
> = {
  sv: { open: "Öppet", closed: "Stängt" },
  en: { open: "Open", closed: "Closed" },
  pl: { open: "Otwarte", closed: "Nieczynne" },
  de: { open: "Geöffnet", closed: "Geschlossen" },
  da: { open: "Åbent", closed: "Lukket" },
  no: { open: "Åpent", closed: "Stengt" },
  fi: { open: "Auki", closed: "Suljettu" },
  fr: { open: "Ouvert", closed: "Fermé" },
  es: { open: "Abierto", closed: "Cerrado" },
  tr: { open: "Açık", closed: "Kapalı" },
  ar: { open: "مفتوح", closed: "مغلق" },
  fa: { open: "باز", closed: "بسته" },
};

/** Visitor-facing, so SITE_LOCALE like the two tables above: the heading over
 *  the dated exceptions, and the temporary-closure banner's label. Only a
 *  restaurant publishes these today (they are projected from the canonical
 *  facts at publish time), but they are guest copy on a public page, so an
 *  English fallback inside an otherwise Finnish page would be the same bug
 *  `WEEKDAYS` was fixed for. */
export const SPECIAL_HOURS_LABELS: Record<
  SiteLocale,
  { exceptions: string; temporarilyClosed: string }
> = {
  sv: { exceptions: "Avvikande öppettider", temporarilyClosed: "Tillfälligt stängt" },
  en: { exceptions: "Special hours", temporarilyClosed: "Temporarily closed" },
  pl: { exceptions: "Godziny specjalne", temporarilyClosed: "Tymczasowo nieczynne" },
  de: {
    exceptions: "Abweichende Öffnungszeiten",
    temporarilyClosed: "Vorübergehend geschlossen",
  },
  da: { exceptions: "Særlige åbningstider", temporarilyClosed: "Midlertidigt lukket" },
  no: { exceptions: "Avvikende åpningstider", temporarilyClosed: "Midlertidig stengt" },
  fi: { exceptions: "Poikkeavat aukioloajat", temporarilyClosed: "Väliaikaisesti suljettu" },
  fr: { exceptions: "Horaires exceptionnels", temporarilyClosed: "Fermé temporairement" },
  es: { exceptions: "Horarios especiales", temporarilyClosed: "Cerrado temporalmente" },
  tr: { exceptions: "Özel çalışma saatleri", temporarilyClosed: "Geçici olarak kapalı" },
  ar: { exceptions: "ساعات عمل استثنائية", temporarilyClosed: "مغلق مؤقتًا" },
  fa: { exceptions: "ساعات کاری استثنایی", temporarilyClosed: "موقتاً تعطیل" },
};

/** "24 dec." — a dated exception, in the site's own language.
 *
 *  Parsed and formatted in UTC on purpose: the string is a CALENDAR day, so
 *  reading it in the viewer's timezone would render "23 dec." to anyone west of
 *  Greenwich. Falls back to the raw ISO string rather than throwing, so an
 *  imported oddity is shown as-is instead of blanking the row. */
export function specialDateText(date: string, lang: SiteLocale): string {
  const parsed = Date.parse(`${date}T00:00:00Z`);
  if (Number.isNaN(parsed)) return date;
  try {
    return new Intl.DateTimeFormat(lang, {
      day: "numeric",
      month: "short",
      timeZone: "UTC",
    }).format(parsed);
  } catch {
    return date;
  }
}

/** Editor-only, so it stays on the three-language admin `Locale`: `opens`/
 *  `closes` label the two time fields in the on-canvas editor (and their
 *  screen-reader names), and `break*` label the intra-day pause a
 *  lunch-and-dinner day needs. No visitor ever reads these — narrow with
 *  `toAdminDictLocale` at the call site. Wording matches the booking hours
 *  panel's `booking.hours.break` / `booking.hours.addBreak` so the two places an
 *  owner can edit the same schedule use the same word. */
export const HOURS_EDITOR_LABELS: Record<
  Locale,
  {
    opens: string;
    closes: string;
    break: string;
    addBreak: string;
    removeBreak: string;
    breakStart: string;
    breakEnd: string;
  }
> = {
  sv: {
    opens: "Öppnar",
    closes: "Stänger",
    break: "Paus",
    addBreak: "Lägg till paus",
    removeBreak: "Ta bort paus",
    breakStart: "Pausen börjar",
    breakEnd: "Pausen slutar",
  },
  en: {
    opens: "Opens",
    closes: "Closes",
    break: "Break",
    addBreak: "Add break",
    removeBreak: "Remove break",
    breakStart: "Break starts",
    breakEnd: "Break ends",
  },
  pl: {
    opens: "Otwiera",
    closes: "Zamyka",
    break: "Przerwa",
    addBreak: "Dodaj przerwę",
    removeBreak: "Usuń przerwę",
    breakStart: "Przerwa zaczyna się",
    breakEnd: "Przerwa kończy się",
  },
};

/** The editor-only strings for a site's language, narrowed to the admin
 *  dictionary's three (a Finnish site's owner still edits in sv/en/pl). */
export function hoursEditorLabels(
  lang: SiteLocale,
): (typeof HOURS_EDITOR_LABELS)[Locale] {
  return HOURS_EDITOR_LABELS[toAdminDictLocale(lang)];
}

/** Weekday name for a day key, falling back to the raw key for imported data
 *  that carries something we don't recognise. */
export function weekdayName(day: string, lang: SiteLocale): string {
  return WEEKDAYS[lang][day as DayKey] ?? day;
}

/** The windows a day is actually open, once its breaks are cut out.
 *
 *  A day is stored as one span plus optional intra-day breaks, so a bistro that
 *  serves lunch 11–14 and dinner 17–22 is `11:00–22:00` with a break at
 *  `14:00–17:00`. The renderer used to print the raw span, which told a guest
 *  the place was open at three in the afternoon — and when generation instead
 *  kept only one of the two services, the published table said "Onsdag
 *  11:00–14:00" directly above the owner's own note "Middag ons–lör 17–22"
 *  (production journey C 2026-07-26, backlog 0989).
 *
 *  Returns `[]` for a closed day or an incomplete span. Breaks that fall outside
 *  the span, or that swallow it whole, are ignored rather than trusted. */
export function openWindows(day: {
  closed?: boolean;
  open?: string;
  close?: string;
  breaks?: readonly { start: string; end: string }[];
}): { open: string; close: string }[] {
  if (day.closed || !day.open || !day.close) return [];
  if (day.close <= day.open) return [];
  const breaks = (day.breaks ?? [])
    .filter((b) => b.start && b.end && b.end > b.start)
    .filter((b) => b.end > day.open! && b.start < day.close!)
    .sort((a, b) => a.start.localeCompare(b.start));

  const windows: { open: string; close: string }[] = [];
  let cursor = day.open;
  for (const b of breaks) {
    const start = b.start > cursor ? b.start : cursor;
    if (start > cursor) windows.push({ open: cursor, close: start });
    if (b.end > cursor) cursor = b.end;
  }
  if (cursor < day.close) windows.push({ open: cursor, close: day.close });
  return windows;
}

/** Collapse the periods a listing reports for ONE weekday into the single span
 *  plus intra-day breaks that `openingDay` stores. The inverse of
 *  `openWindows`.
 *
 *  Google Places and schema.org both report a split day as TWO periods (lunch
 *  11–14, dinner 17–22). Every importer we have kept only the first and threw
 *  the rest away, so a bistro's dinner service never reached the site at all:
 *  the published table read "11:00–14:00" directly above the owner's own note
 *  "Middag ons–lör 17–22" (backlog 0989). One span 11:00–22:00 with a
 *  14:00–17:00 break says the same thing in the shape the model already has.
 *
 *  Overlapping and touching periods merge. Returns null when there is nothing
 *  usable. A day whose only period we cannot make sense of — an overnight
 *  18:00–02:00, which both sources split across two calendar days — is passed
 *  through untouched rather than dropped, so this never loses a day the old
 *  first-period-wins rule would have kept. */
export function spanWithBreaks(
  periods: readonly { open: string; close: string }[],
): {
  open: string;
  close: string;
  breaks?: { start: string; end: string }[];
} | null {
  const valid = periods
    .filter((p) => p.open && p.close && p.close > p.open)
    .sort((a, b) => a.open.localeCompare(b.open));
  if (valid.length === 0) {
    const first = periods.find((p) => p.open && p.close);
    return first ? { open: first.open, close: first.close } : null;
  }

  const merged: { open: string; close: string }[] = [];
  for (const p of valid) {
    const last = merged[merged.length - 1];
    // `<=` so two touching periods (…14:00 + 14:00…) become one span with no
    // zero-length break between them.
    if (last && p.open <= last.close) {
      if (p.close > last.close) last.close = p.close;
      continue;
    }
    merged.push({ open: p.open, close: p.close });
  }

  const breaks = merged
    .slice(0, -1)
    .map((w, i) => ({ start: w.close, end: merged[i + 1].open }));
  return {
    open: merged[0].open,
    close: merged[merged.length - 1].close,
    ...(breaks.length ? { breaks } : {}),
  };
}

const toMinutes = (hhmm: string): number => {
  const [h, m] = hhmm.split(":");
  return Number(h) * 60 + Number(m);
};

const toHhmm = (minutes: number): string =>
  `${String(Math.floor(minutes / 60)).padStart(2, "0")}:${String(minutes % 60).padStart(2, "0")}`;

/** The break to pre-fill when an owner adds one to a day: an hour in the middle
 *  of the span, snapped to the same 15-minute grid the editor's time selectors
 *  offer.
 *
 *  Placing it in the middle rather than at a fixed "12:00–13:00" matters: a
 *  break outside the day's span is ignored by `openWindows`, so a fixed default
 *  would do visibly nothing on a day that opens at 17:00 and the owner would
 *  have no idea why. Returns null when the day is too short to hold a break
 *  with opening time left on both sides — the caller hides the control. */
export function defaultBreak(
  open: string,
  close: string,
): { start: string; end: string } | null {
  const from = toMinutes(open);
  const to = toMinutes(close);
  if (!Number.isFinite(from) || !Number.isFinite(to)) return null;
  const length = 60;
  // 15 minutes of opening time on each side, so the break never swallows an end.
  if (to - from < length + 30) return null;
  const snapped = Math.round((from + to - length) / 2 / 15) * 15;
  const start = Math.min(Math.max(snapped, from + 15), to - 15 - length);
  return { start: toHhmm(start), end: toHhmm(start + length) };
}

/** "11:00–14:00, 17:00–22:00", or the closed label when the day has no window. */
export function hoursText(
  day: Parameters<typeof openWindows>[0],
  lang: SiteLocale,
): string {
  const windows = openWindows(day);
  if (windows.length === 0) return HOURS_STATUS_LABELS[lang].closed;
  return windows.map((w) => `${w.open}–${w.close}`).join(", ");
}
