// GENERATED by scripts/mirror-import.ts from HH-Studio/simple-site-builder:lib/sections/variantRequirements.ts
// Do not edit. Run `bun scripts/mirror-import.ts --sync-from-app <appRoot>`.

// ---------------------------------------------------------------------------
// What a layout NEEDS, and what a given section is missing for it.
//
// Two facts make this small, and both are worth stating because the first
// instinct is to build something much bigger:
//
// 1. **A layout swap never deletes content.** `opSetVariant` patches `variant`
//    and, at most, ADDS keys. A three-card layout swapped down to a one-card
//    layout keeps all three items; the renderer simply shows one. Swap back and
//    the third card is still there, verbatim. So there is no "content bank" to
//    build - the copy already stays, and the work is to make that visible and
//    to fill the genuinely EMPTY holes a new layout opens.
// 2. **Which holes exist is a registry fact**, declared per variant
//    (`VariantDef.requires`), not a hardcoded switch in a server file nobody
//    opens when adding a variant.
//
// Everything here is pure and content-shape agnostic on purpose: the same
// function answers "what must I fill before this swap?" (sectionOps) and
// "can I shuffle into this layout for free?" (shuffle), and it runs in the
// browser for the picker's own hints.
// ---------------------------------------------------------------------------

import { SECTION_REGISTRY, type VariantDef } from "../../../lib/sections/registry";
import type { SectionType } from "../../../convex/model/sections";

/** What a section still lacks for a layout. Empty = the swap is free. */
export type VariantGap = {
  /** Declared fields the content does not have at all. */
  fields: string[];
  /** How many more `items` the layout wants (0 = enough). */
  missingItems: number;
};

export const EMPTY_GAP: VariantGap = { fields: [], missingItems: 0 };

export function isGapEmpty(gap: VariantGap): boolean {
  return gap.fields.length === 0 && gap.missingItems === 0;
}

export function findVariantDef(
  type: string,
  variant: string,
): VariantDef | undefined {
  const def = SECTION_REGISTRY[type as SectionType];
  return def?.variants.find((v) => v.key === variant);
}

/** A field counts as PRESENT when the content has the key at all - even empty.
 *  Deliberately generous: an owner who cleared a headline meant to clear it,
 *  and re-filling it on an unrelated layout swap would be the product writing
 *  over the owner, which is the one thing auto-fill must never do. */
function hasField(content: unknown, field: string): boolean {
  if (typeof content !== "object" || content === null) return false;
  return (content as Record<string, unknown>)[field] !== undefined;
}

function itemCount(content: unknown): number {
  if (typeof content !== "object" || content === null) return 0;
  const items = (content as { items?: unknown }).items;
  return Array.isArray(items) ? items.length : 0;
}

/** What `content` is missing before `variant` of `type` can render honestly.
 *  Unknown type/variant, or a variant that declares nothing, returns an empty
 *  gap - "nothing to fill" is the correct answer for every layout that renders
 *  what it is given. */
export function missingForVariant(
  type: string,
  variant: string,
  content: unknown,
): VariantGap {
  const requires = findVariantDef(type, variant)?.requires;
  if (!requires) return EMPTY_GAP;
  const fields = (requires.fields ?? []).filter((f) => !hasField(content, f));
  const missingItems = Math.max(0, (requires.minItems ?? 0) - itemCount(content));
  return { fields, missingItems };
}

/** True when swapping to this layout costs nothing: no fill, no AI call, no
 *  wait. This is the compatibility test Shuffle uses, so shuffling is instant
 *  and free by construction rather than by luck. */
export function variantSatisfied(
  type: string,
  variant: string,
  content: unknown,
): boolean {
  return isGapEmpty(missingForVariant(type, variant, content));
}
